### ISSUE TITLE
Beer Log Management

### ISSUE THREAD

**Issue by thorrak** [thorrak/fermentrack#103]
Beer logs are associated with `Beer` objects in Fermentrack. Right now, we have creation support for `Beer` objects, but not update/delete.

We need to add support to delete `Beer` objects - and, through hooks on the delete event - also delete the corresponding log files.

**Comment by Mikmonken** [comment]
Would be great to have an option to plot gravity readings alongside at various points.

**Comment by thorrak** [comment]
@stone and I have been discussing that one actually - I need to add an issue for v3 around support for gravity sensors. Goal is to add support for Tilt & ispindel first. The way it will work is that the gravity sensor will be another top-level object - similar to the fermentation controller. You can then track gravity independently of any fermentation - or link the gravity to a fermentation controller to combine them (or use the gravity to control a beer profile).

All of this is scheduled for v3 though, so it's a ways off in terms of prioritization (though I won't guarantee v3 features won't be worked on before certain v2 features given I have a tilt I'd like to play with).

**Comment by Mikmonken** [comment]
I'm planning on getting an iSpindle after pay day so obviously would be keen to integrate too, and feedback

**Comment by thorrak** [comment]
A note on this - following the fix to add device management, devices that are deleted will be unlinked from their beer logs (but the logs won't be deleted). There should probably be an "orphaned log" list (possibly on the "Site Help" page) that displays links to download the logs (and possibly display them, at a future state).
