### ISSUE TITLE
Test/Fix Basic Arduino support

### ISSUE THREAD

**Issue by thorrak** [thorrak/fermentrack#106]
Similar to #105 there shouldn't be anything preventing the use of Fermentrack with Arduino-based controllers at the moment, but I don't have any to test with.

- [x] Build an Arduino-based controller
- [x] Test with Fermentrack's serial support (Pending #105)
- [x] Fix any bugs in Fermentrack/brewpi-script that may cause issues with Arduino support

Note - This issue is only for the basic support. Additional features will need their own issues (including serial autodetection, guided setup, etc.)

**Comment by Mikmonken** [comment]
I can support with testing this as have an Arduino available for use.

**Comment by thorrak** [comment]
So, uh, that was easy. I think that serial support + arduino support should be in and working with the next PR (which will be done in ~5 mins). @Mikmonken - If you don't mind testing it out, I would appreciate it!

**Comment by Mikmonken** [comment]
OK so I've hooked up the Arduino on the 2nd RPI (which is running the same version)
You can't add via the guided set up. When you get to the Arduino it says that it's not available yet.
but if you go via add new device advance it seems to work well.

As a side note if you try to add ESP via serial too it pre populates the advanced menu with Arduino rather than ESP.

Assigning devices seem to work fine, although they're not referred to as heat or cool rather by the D number which made it trial and error for me as I'm using a shield so can't remember what pin does what.

**Comment by thorrak** [comment]
Thanks for testing that. Interesting that the "Heat", "Cool", etc pin names aren't populated - those are actually set by a file within BrewPi-Script, so they should be the same as what you would see within BrewPi-www. Which shield are you using? Do you happen to know if your firmware reports the shield to BrewPi-Script?

On Mar 29, 2017, at 7:03 AM, Mikmonken <notifications@github.com<mailto:notifications@github.com>> wrote:


OK so I've hooked up the Arduino on the 2nd RPI (which is running the same version)
You can't add via the guided set up. When you get to the Arduino it says that it's not available yet.
but if you go via add new device advance it seems to work well.

As a side note if you try to add ESP via serial too it pre populates the advanced menu with Arduino rather than ESP.

Assigning devices seem to work fine, although they're not referred to as heat or cool rather by the D number which made it trial and error for me as I'm using a shield so can't remember what pin does what.

**Comment by Mikmonken** [comment]
It's a shield designed by Cadibrewer v1.1

I don't know if it recognises it's a shield or not, I suspect not as it seems to be a direct pin to pin wiring.

![image](https://cloud.githubusercontent.com/assets/19469569/24452653/27200fee-147c-11e7-8cab-6d6e8de14aef.jpg)


![image](https://cloud.githubusercontent.com/assets/19469569/24452625/04acf346-147c-11e7-800b-9c6e309b952c.jpg)

**Comment by thorrak** [comment]
This is good now. Closing this issue. Wooo!
