### ISSUE TITLE
Timeouts when retreiving devices from brewpi-script

### ISSUE THREAD

**Issue by thorrak** [thorrak/fermentrack#108]
Apparently the bug that caused #95 is not limited to adding new devices to the controller. I ran into the same bug when attempting to connect to the controller as part of a new installation of Fermentrack. The "retry" code I wrote doesn't appear to be working as expected. 

Need to fix this (or change the error message to prompt people to click the "reconnect" button

**Comment by thorrak** [comment]
I thought we had this resolved, but per [Mikmonken](http://www.homebrewtalk.com/showpost.php?p=7938463&postcount=689) this is still an issue. Reopening.

Next step is probably going to be to refactor the device queries in brewpi-script to have it synchronously connect to the device and retrieve the device list rather than attempt to do it asynchronously.

**Comment by Mikmonken** [comment]
seems to occur at around the 6th-7th attempt to connect a new device.

**Comment by thorrak** [comment]
I think I have a solution coded up locally. Once I get somewhere I can test it, if it doesn't cause any issues I'll push it to production. 

Basically, I'm making it so that brewpi-script treats the device info the same way it treats control constants/settings. Load them at script startup, and maintain a cache, refreshing the cache every time an update is triggered. 

There isn't a way to (easily) make it read synchronously unfortunately without refactoring the entirety of brewpi-script.
