### ISSUE TITLE
Inversion flag isn't properly sent to device on pin assignment

### ISSUE THREAD

**Issue by thorrak** [thorrak/fermentrack#116]
Per [Mikmonken](http://www.homebrewtalk.com/showpost.php?p=7938463&postcount=689) the pin inversion flag isn't properly being sent to the fermentation controller when the pin is assigned. 

Not sure if this is a bug in Fermentrack, brewpi-script, the firmware, or a combination of the three.

**Comment by Mikmonken** [comment]
Thought this might be a short of some kind on the board, but when the device is sent to cool or heat the corresponding relay does switch.
