### ISSUE TITLE
Specific Gravity Sensor Support

### ISSUE THREAD

**Issue by thorrak** [thorrak/fermentrack#130]
One of the features that I would love to see on top of support for fermentation temperature control is fermentation specific gravity monitoring. I've personally owned both a BrewBug and Tilt Hydrometer, and while only one of them is open enough to work with third party software, I'd love to see a solution built that is flexible enough to support either (or other, newer solutions!).

That said, here is how I (currently) envision (initial) Specific Gravity sensor support:

- [x] Create a new base-level object (similar to BrewPiDevice) for SpecificGravitySensors
- [x] Create one (or more) "hardware" object classes to handle communcating with an individual SG sensor
- [x] Write scripts to mediate communication with one or more SG sensors that run independently of brewpi-script
- [x] Display the results from SG sensors on a graph that is independent from that used for temperature control

And yes - longer term, the goal is to add linkage between a controller and a specific gravity sensor so that the two graphs can be combined, but for now - simply tracking fermentation (har har) is a step in the right direction.

**Comment by Mikmonken** [comment]
My iSpindel is now assembled and floating around in a bowl of water until I free up an FV.  

Currently sending the info to Ubidots which seems to display it quite nicely.  There are options to log the data onto an RPI but as it uses var/www/html I don't want to try it out in case I break fermentrack logs.

**Comment by gezzanet** [comment]
ive got a live ISpindel as well. Ubidots working. Dream would be to control ferm temp profile based on gravity of course.

**Comment by thorrak** [comment]
Gravity sensor support is now complete. iSpindel support exists as well. Additional/new features will be tracked as new issues.
