### ISSUE TITLE
Remove the need for reset_circus.sh

### ISSUE THREAD

**Issue by thorrak** [thorrak/fermentrack#138]
The shell script `reset_circus.sh` is a lazy way for me to avoid using true circus integration in Fermentrack proper. Where I currently call the script I should instead just directly interact with Circus.

**Comment by stone** [comment]
I have almost finished a fermentrack-circus-handler-python-class that we could use for this (when I worked with brewpi_spawner.py. The goal is here was to keep the code duplication to a minimum.

**Comment by thorrak** [comment]
That sounds awesome!

**Comment by stone** [comment]
I have done some progress but mostly testing and everything seems to work, I will do a PR soon and maybe we should put it in a branch to test more. 

The biggest change is the rewrite of brewpi_spawner.py (I have renamed it to processmgr.py so it will not interfere), and that change could wait..

**Comment by stone** [comment]
Just a note about which version of brewpi_spawner.py and processmgr.py which is the "new one".
https://github.com/thorrak/fermentrack/blob/master/utils/processmgr.py#L6
It is actually processmgr.py which uses the new lib and will replace brewpi_spawner.py

**Comment by thorrak** [comment]
I ended up testing your code as a replacement for reset_circus.sh and uh - it worked pretty much perfectly. I tweaked some of the code slightly to allow it to accept unicode and added a `restart_process()` function to BrewPiDevice just to make things easier, but otherwise this issue was closed by your commits two weeks back!

Good work!

**Comment by stone** [comment]
Great! I hoped to get some more work done on Fermentrack this weekend but life got in the way, good to hear that it worked good.
