### ISSUE TITLE
Create serial autodetection

### ISSUE THREAD

**Issue by thorrak** [thorrak/fermentrack#140]
Right now, we have automatic detection of mDNS-based controllers -- but this will only ever work with ESP8266-based devices that have been flashed with the BrewPi firmware. That said, it would be helpful for both flashing devices as well as setting up serial devices to have some kind of "autodetection" method which could be used to allow users to quickly detect non-WiFi devices. 

In thinking of implementing this, I see two ways that we could approach it:

## Two-Scan Method

Basically, the user would leave the device unplugged and click a "scan" button. All serial devices would be scanned and noted down. The user would then connect the device, click "scan" a second time, and a list of the devices present in the second scan but not the first would be presented. 

**Pro:** This method would detect any device - including "unofficial" Arduino clones

**Cons:** The user could (attempt to) flash an inappropriate firmware to the device. The user could potentially flash the wrong device if multiple are detected.

## "Known Device" Method

Within Fermentrack we maintain a list of "known" VIDs/PIDs that the script will use to detect official Arduino boards reporting the right hardware type. The user would be displayed a list of only these boards, and could then select the right one to flash.

**Pro:** Substantially reduced chance of damage to the device due to an inappropriate firmware being selected.

**Cons:** The user would be unable to flash/connect "unofficial" Arduino clones. Cannot provide certainty of authenticity of ESP8266-based devices (almost all have generic PIDs/VIDs). 

Any thoughts?

**Comment by stone** [comment]
I'd say Two-Scan Method, with all the clones I think that that list will be very hard to keep up to date and there is always a risk that a clone "borrow" PID/VIDs. 

When presenting the findings for the user (detected devices) we could inform about the dangers and that any devices they do not want to get flashed should be disconnected to be really sure. Flashing the wrong device is not as dangerous as instructing users to use "dd" for writing raspberry pi images ;)

**Comment by thorrak** [comment]
Two-scan method it is. I have this half-coded at the moment. Working to finish it up and integrate into the guided setup workflow. Should be done in the next few days.
