### ISSUE TITLE
Set up udev rules for serial devices from within Fermentrack

### ISSUE THREAD

**Issue by thorrak** [thorrak/fermentrack#143]
I need to test this, but I have a sneaking suspicion that if you have multiple serial controllers connected to a single Raspberry Pi you run the risk of the serial ports getting switched between them. 

It would be good to test this and - if this is the case - warn the user about the possibility when they go to set up the second serial-based controller in guided setup. 

## Current plan - Implement udev rule creation

- [ ] Create udev rule file (similar to suggested `99-arduino.rules` file on HBT) (Done in setup script)
- [ ] Test for custom udev rule file in Fermentrack
- [ ] Read/interpret custom udev rule file
- [ ] Map detected udev rules to BrewPiDevice devices
- [ ] Add script to detect attached USB devices using [pyudev](https://pyudev.readthedocs.io/en/latest/)
- [ ] Allow user to map BrewPiDevice to detected USB device & write udev rule

**Comment by stone** [comment]
I don't have access to any Arduino right now but I got some code where I have used several Arduinos and to identify them I use the generated udev device: /dev/serial/by-id/usb-Arduino__www.arduino.cc__xxxx_xxxxxxxxxxxxxxxxxxxx-if00 which is a little more specific and actually includes the serial number of the Arduino connected. I don't remember if this udev rule is there by default, but it would be very easy to check one I get to my Arduinos.

**Comment by Mikmonken** [comment]
I have a couple of Arduinos so can give this a try too.  I've seen reverence to the ID codes too. Daytrippr on the home-brew forum directed someone here to help set up multiple arduinos on one RPI http://www.homebrewtalk.com/showpost.php?p=7598995&postcount=5700

**Comment by thorrak** [comment]
Hmm. That's an interesting approach - it would absolutely work here, but I don't like forcing the user back to the shell if I can avoid it. 

I could write a script that would allow Fermentrack to create/write udev rules, but either it would have to be set permanently `sudo` or we'd have to set `/etc/udev/rules.d` as writable by Fermentrack. Either of these would require setup by a `sudo`ed user though, which means within install.sh.

Thoughts? I like the idea of the auto detect routine offering to create udev rules though. It feels much more permanent.

**Comment by stone** [comment]
I will test when I get home with a couple of genuine arduino and some clones and see how Rasbian handles them by default. If the default handling is not good enough we could always create udev rules during install/update (we need sudo for that) or as you propose make the file owned by fermentrack for future updates.

**Comment by thorrak** [comment]
So I think I have a plan for this one:

1. Create a custom udev rules file (will require existing users to SSH in, but can be done automatically for new users as part of setup)
2. After the user creates a serial device, prompt them to create a udev rule. If they choose to do so, then...
3. Detect connected USB devices & map to existing BrewPiDevices
4. Read in the custom udev rules file & map to existing BrewPiDevices
5. Prompt the user to create new udev rules for unmapped BrewPiDevices connected via serial
6. Write udev rules back out to the udev rules file

The idea is that we would have a custom class for udev rules, that would handle reading in/writing out the udev rules file. We could then map to BrewPiDevices manually.

**Comment by thorrak** [comment]
Welp, I actually don't think this will work. After we write out the udev rules, we then have to restart udev - which requires root. 

Instead, here's what I'm thinking the new game plan is:

1. Add a "udev serial" field to the BrewPiDevice model
2. Set the "udev serial" to the "ID_SERIAL" property of the USB device (retrieved via pyudev)
3. If the "udev serial" is present, do a scan using pyudev of all connected serial devices to find the current "device node" used for the device
4. Connect to that "device node"

The open questions on this one are:
How do we handle installations on systems that don't support udev?
Do we default to the "serial port" if we have a udev serial number but can't find it?

**Comment by stone** [comment]
Yep, default to "serial port" should be enough, documentation could also be updated with some information about how to do it. It's a nice to have feature but for our supported case (rasbian (soon armbian)) there will be an udev..

**Comment by thorrak** [comment]
This is now implemented. Everything should work transparently, behind the scenes. `BrewPiDevice.serial_port` is ignored if `BrewPiDevice.prefer_connecting_via_udev` is set, with `BrewPiDevice.udev_serial_number` instead being used to detect the appropriate device connected via USB.
