### ISSUE TITLE
503 error is returned on device uninstallation

### ISSUE THREAD

**Issue by thorrak** [thorrak/fermentrack#145]
Part of the device uninstallation process is to call reset_circus.sh which in turn does what the name says -- and resets Circus. Unfortunately, Chaussette is managed by Circus, which means that Fermentrack is taken down by the reset unnecessarily.

This relates to #138 which I think is being resolved by the branch 0459343e0aeebbc0abea1532ff09aad39019ab58 is part of. Guessing this can be resolved once that branch is merged in - but noting the issue here for tracking so it doesn't get forgotten.

**Comment by stone** [comment]
There is actually no need to remove the process from circus by Fermentrack django, brewpi_spawner.py will periodically query the database and stop/remove or start processes as needed. 

The relevant function is here:
https://github.com/thorrak/fermentrack/blob/master/fermentrack_django/brewpi_spawner.py#L68

**Comment by thorrak** [comment]
... damnit. That makes sense. Commenting out the offending lines & closing issue.
