### ISSUE TITLE
Handle connection problems with an exit

### ISSUE THREAD

**Issue by stone** [thorrak/fermentrack#147]
What I can see is that when this line is reached timeout has been reached. and the loop starts over again.
https://github.com/thorrak/fermentrack/blob/master/brewpi-script/brewpi.py#L934

One way to handle this is to actually just quit (os.exit(0), raise SystemExit etc) and let Circus automaticlly
start the process again.

There may be more places where this could be used or better places, I know that @thorrak  have been working with the timeout code and I'll leave this ticket for discussion.

**Comment by thorrak** [comment]
This makes a lot of sense, and is a practice that we really should employ given that in both environments -- Fermentrack (Circus) and brewpi-www (cron) -- we have something that will restart brewpi-script if it exits.
