### ISSUE TITLE
License Incompatibility with Django-Suit

### ISSUE THREAD

**Issue by darklow** [thorrak/fermentrack#150]
Hi @thorrak. Django Suit author here. I would like to let you know that you are clearly violating Django Suit license which is commercial and free only for personal and non-commercial use. Django Suit license is totally incompatible with license your app is using which means you are violating and misleading your app users. No way app your can be MIT or any other open-source compatible license if you are including commercial and limited licensed library like Django Suit.

You should remove `suit` from requirements. Or if you would like to keep it, you need to make it optional by users choice, telling them how to add it and also letting users know that Django Suit license is not compatible with your APP and provide more info about license.

More about Django Suit license:
https://github.com/darklow/django-suit#license
http://djangosuit.com/pricing/

**Comment by thorrak** [comment]
Apologies - I was under the impression that the Creative Commons Attribution-NonCommercial 3.0 license was compatible with the MIT license when used in a non-commercial setting. The requirements have been updated to exclude this.

**Comment by darklow** [comment]
Thanks. Well `MIT` and `Apache` are most permitting licenses, as long as you are attributing you can do almost anything including selling etc. While CC NonCommercial is totally different animal. I am not against using Django Suit for your project, as most of your app use cases will be for personal use, it is just your app license is as strict as strictest of your component licenses which would make your app CC Non-Commercial too and users should be aware that. Therefore feel free to add optional notes on how to add `suit` just make aware of the fact that it is free only for non-commercial use and reference link to license policy.
