### ISSUE TITLE
Add Firmware Flash Support

### ISSUE THREAD

**Issue by thorrak** [thorrak/fermentrack#172]
One major feature that Fermentrack is missing is the ability to directly download firmware from within the interface, and flash it to a device connected via Serial. This would allow most users to avoid the command line for setting up new BrewPi devices - aside from the initial installation of Fermentrack itself.

To add firmware flash support, we need the following:

- [x] Create central repository of Firmware information (fermentrack.com)
- [x] Sync central repository to local Fermentrack installation
- [x] Use serial autodetection to detect device to flash
- [x] Prompt user to select firmware to flash
- [x] Download Firmware/check checksum of Firmware to ensure validity
- [x] Trigger flash of firmware via Celery (See note)
- [x] Monitor status of flash & display to user

_NOTE_ - Triggering the flash via Celery in this context doesn't necessarily imply direct support for a specific flash type (avrdude vs. esptool). We need support for each of those as well:

- [x] Support flashing via avrdude (Arduino)
- [x] Support flashing via esptool (ESP8266)

There's a lot here to accomplish, but once this feature is in, it will likely prove incredibly useful.

**Comment by thorrak** [comment]
I cheated a bit with this issue - I've been working on this for the past week, but just now realized there wasn't an issue to track progress against. The basic code to support a good chunk of the above is now pushed, including the following:

- Support for central repository
- Serial autodetection
- User prompt to select firmware (but, it's really really ugly)
- Code to download/check firmware

The remaining code that needs to be written is avrdude/esptool support and everything Celery-related.

**Comment by thorrak** [comment]
Ugh, tagged the wrong issue.

**Comment by Mikmonken** [comment]
This may or may not be useful but Interestingly the new ISpindel Firmware allows OTA updates to the ESP8266 no idea how they do this but thought it might be useful in terms of flashing firmware.

**Comment by thorrak** [comment]
@stone actually has been working on [that exact feature](https://github.com/stone/fermentrack/commit/f0d706912cceaaeb8a264a17b83b96d1dd6d43bb). I think that many of the necessary changes to Fermentrack are done -- the remaining changes are to the ESP8266 firmware itself. 

Regardless - OTA updates are absolutely on the list, and should be supported at some point - even if it may be a bit after the serial flashing support is complete.

**Comment by thorrak** [comment]
The v2 features are done for this - pushing this to v3 to determine if I want to mess with converting the actual flashing to be celery driven

**Comment by thorrak** [comment]
With the conversion to use Huey to manage firmware flashing, this is now complete.
