### ISSUE TITLE
Beer Profile import - time error

### ISSUE THREAD

**Issue by Mikmonken** [thorrak/fermentrack#174]
Importing the profile posted on home-brew talk  as follows.

    =====================================================
    | Brulosopher Fast Lager (Low-Mid SG, Liquid Yeast) |
    | Standard Profile                                  |
    =====================================================
    | 6d               | 52.00 F                        |
    | 7d 12h           | 67.00 F                        |
    | 11d              | 67.00 F                        |
    | 15d              | 33.00 F                        |
    | 20d              | 33.00 F                        |
    =====================================================

Whilst converts to ˚c out is below, note 7d 12h is amended to 12h and becomes the start of profile, exports ˚f

below is the export log i get from importing the above (if that makes sense)

    =====================================================
    | Brulosopher Fast Lager (Low-Mid SG, Liquid Yeast) |
    | Standard Profile                                  |
    =====================================================
    | 12h      | 67.00 F                                |
    | 6d       | 52.00 F                                |
    | 11d      | 67.00 F                                |
    | 15d      | 33.00 F                                |
    | 20d      | 33.00 F                                |
    =====================================================

**Comment by thorrak** [comment]
This was fixed in the commit I just pushed (and tagged with the wrong issue number)
