### ISSUE TITLE
ValueError when creating new fermentation profiles.

### ISSUE THREAD

**Issue by stone** [thorrak/fermentrack#175]
When creating a new fermentation profile an error is thrown:

    ValueError at /fermentation_profile/10/edit/
    max() arg is an empty sequence

The code is:
    
    max_ttl_string = max([x.ttl_to_string() for x in point_set], key=len) 

I have not had time to look into it, but a guess is that max() gets an empty
list as there is no points yet in the fermentation profile.

**Comment by thorrak** [comment]
Yep, your pull should have fixed this. Closing.
