### ISSUE TITLE
A couple of doco changes to Raspi setup 

### ISSUE THREAD

**Issue by gezzanet** [thorrak/fermentrack#190]
Prepare the Raspberry Pi - [Video]
1.	Download the latest version of Raspbian from here. I recommend the Lite version as I prefer headless installations, but the full version works as well.
2.	Burn Raspbian to your SD card using these instructions. 
3.	WiFi now, thus preventing having to find an ethernet cable
4.	Plug the SD card into your Raspberry Pi, connect the Pi to ethernet (if you did not configure WiFi), and plug in power, screen and keyboard.
5.	Locate the IP address for your Raspberry Pi This can generally be done by executing arp -a | grep raspberry however you can also locate your Raspberry Pi by logging into your router and looking for the device. You will need the IP address to log in to Putty
6.	NEW - Enable SSH on your Raspberry Pi by writing an empty file named "ssh" to the root of the SD card. If you enable SSH you wont need your Keyboard and screen anymore because you will be able to log into it with a program like Putty.
7.	Optional, NEW - Configure WiFi - See the note below if you want to configure Update the Raspberry Pi software by running sudo apt-get update and sudo apt-get upgrade. This can take a long time depending on your internet connection as it has to go and get the updates and then install them.
8.	Run raspi-config and configure the Pi. At a minimum, expand the filesystem (option 1).
9.	Update the default password for the pi user using passwd
10.	Optional - Configure WiFi on your Raspberry Pi (if needed)

**Comment by thorrak** [comment]
Apologies -- What changed here?

**Comment by gezzanet** [comment]
Sorry not a lot. Just added bits to remind a noob like me. just new to GitHub so working out best way to help out. I can resend later with changes highlighted.

**Comment by thorrak** [comment]
Oh, no worries at all!

If you want, you should be able to edit the documentation directly. You'll want to edit the docs that are in this path:

https://github.com/thorrak/fermentrack/tree/master/docs_mkdocs/docs

The docs that are in the regular /docs path are what gets generated semi-automatically via the link above. To edit the documents you can tinker with git on your local computer, or potentially use the built-in editor GitHub provides. To use that, go to the document you want to edit, click the "pencil" icon in the upper right corner of the file, and make the changes you want to make.

You'll need to then commit those changes -- GitHub should give you instructions on how to do so at the bottom of the edited page.

Alternatively, feel free to send edits either here, through GitHub's issue system, or on HBT. Happy to take all the help we can get!
