### ISSUE TITLE
Devices swapped names

### ISSUE THREAD

**Issue by Mikmonken** [thorrak/fermentrack#198]
Ok really weird bug. My two Fermentrack devices have swapped names.

![img_1005](https://user-images.githubusercontent.com/19469569/29485656-6155c64c-84cd-11e7-9cf5-0412f666741e.PNG)

OLAG has been fermenting a Kolsch for 2 months, went to start fermenting a new beer and it stopped communicating. I refreshed the devices and then my sous vide seemingly became my fern chamber, but only through name as there isn't any power going to me sous vide as that assigned device isn't on.

**Comment by Mikmonken** [comment]
Attached are the logs.

Points that might be important..

OLAG had been running/logging for about 2 months.
SOusvide has not been turned on for a few months.

there have been a couple of occasions where OLAG has just stopped communicating with RPI, a reboot has prompted it to kick in again.

[SOusvide stderr.log.txt](https://github.com/thorrak/fermentrack/files/1236245/SOusvide.stderr.log.txt)
[Sousvide stdout.log.txt](https://github.com/thorrak/fermentrack/files/1236242/Sousvide.stdout.log.txt)
[OLAG stderr.log.txt](https://github.com/thorrak/fermentrack/files/1236243/OLAG.stderr.log.txt)
[OLAG stdout.log4.txt](https://github.com/thorrak/fermentrack/files/1236244/OLAG.stdout.log4.txt)

**Comment by Mikmonken** [comment]
Deleting and reinstalling has solved the issue but still very strange

**Comment by Mikmonken** [comment]
Not sure if it's related but the device lost connection again after around 18hrs. And uninstall and reinstall of the device restablishes connection with no issues seemingly, even without a reboot so am assuming the wemos device is OK

**Comment by thorrak** [comment]
This is really weird. Out of curiousity, how are you connecting the interface to the script? Do you have "Useinetsocket" checked, or are you connecting via serial?

**Comment by Mikmonken** [comment]
Both were connected over wifi, I'm not at home to check in more detail at the moment but yes it was very odd.

**Comment by thorrak** [comment]
No worries - I'm thinking of the connection between brewpi-script & fermentrack in this case, so socket vs. serial as opposed to wifi vs. serial for the connection between the firmware and brewpi-script.

Not sure what is getting confused in this case. It might make sense to add some kind of readable "unique identifier" to the firmware to directly validate that the script connected to the firmware it knows. No reason not to, really.

**Comment by thorrak** [comment]
@Mikmonken , Have you had this reoccur recently? I haven't seen this happen on my end, and haven't been able to figure out what could have caused it for WiFi other than the IP addresses being swapped or something.

**Comment by Mikmonken** [comment]
No nothing recurring although since the issue occurred I’ve not really used the SousVide. I’ve also rebuilt the system.
