### ISSUE TITLE
Lose conection router

### ISSUE THREAD

**Issue by lggrizendi** [thorrak/fermentrack#202]
If the esp8266 and the raspberry pi is still on and the router reboot or is turn off and on again the esp8266 don't reconnect to the router i tried  with dhcp and static ip. I have to reset or turn off and turn on the esp8266.

**Comment by thorrak** [comment]
I think that this is an issue with the firmware, not necessarily an issue with Fermentrack. That said, I went ahead and picked up a cheap router that I can use for testing this. I'm working on something else at the moment, but this will be prioritized once I'm done with that.
