### ISSUE TITLE
iSpindel Support

### ISSUE THREAD

**Issue by thorrak** [thorrak/fermentrack#207]
Add support for iSpindel SG sensors

**Comment by snoop6060** [comment]
Hows this one coming along?

**Comment by thorrak** [comment]
It's coming! It's behind a handful of small bug fixes, but that's about it. Unfortunately, I've been distracted for the past two months or so, and haven't spent nearly as much time on Fermentrack as I would have liked. Just now getting back into the swing of things - hoping to have this done within the next few weeks.
