### ISSUE TITLE
Raspbian Stretch Install Issue

### ISSUE THREAD

**Issue by thorrak** [thorrak/fermentrack#208]
Amadio on HBT reported an issue installing under Raspbian Stretch:

I just got a new Pi 3, trying to install on the latest Raspbian (STRETCH LITE September 2017).

using the automated installer I see this error message during the install

[code]::: Copying nginx configuration to /etc/nginx and activating.
sed: can't read /home/fermentrack/fermentrack-tools/nginx-configs/default-fermentrack: No such file or directory
::: Running updateCronCircus.sh from the script repo
Checking and fixing cron entries for Fermentrack
::: Starting circus process monitor.
Starting Fermentrack supervisor: circusd: /home/fermentrack/fermentrack/utils/updateCronCircus.sh: line 36: /home/fermentrack/venv/bin/circusd: No such file or directory
failed, please see logfile.[/code]

there is no  /home/fermentrack/fermentrack-tools/ directory, but there is a ~/fermentrack-tools directory

**Comment by stone** [comment]
I will have a look at this

**Comment by stone** [comment]
My pi3 is not booting.. I have to come back to this when it's up and running again..

**Comment by thorrak** [comment]
Hey there! Cougar324 and I spent time researching this one on HBT - I think it’s pip’s fault.

**Comment by thorrak** [comment]
So I _think_ this issue is resolved between two commits in [Fermentrack tools](https://github.com/thorrak/fermentrack-tools). 

The [first commit](https://github.com/thorrak/fermentrack-tools/commit/8dba8249094fa14f1cc5ef190c55525330fafb09) added a script which forces reinstallation of pip within the virtualenv. This should hopefully fix any issues that 

The [second commit](https://github.com/thorrak/fermentrack-tools/commit/6fa44cd9b10f35aa53475d18f4ac13efeb36a9b3) separately adds the '-H' flag to each call made via `sudo <fermentrack user>`. I think that some environments/installations do this by default, while in others this behavior isn't assumed. By forcing the -H flag the home directory is always redirected which is what we want in this case. 

I'm actually guessing it's the second of these changes that is the more important one - but I'm leaving the first one (for now) as it doesn't seem to cause any issues elsewhere.
