### ISSUE TITLE
Two Beer temps

### ISSUE THREAD

**Issue by bake3310** [thorrak/fermentrack#226]
I often brew 10 gallon batches split into two fermenters. I would love to be able to have temp probes in both and have both of them displayed on the chart and on the "LCD" (alternating between the two?). Seems that if the tilt could be added then this shouldn't be too much of a stretch (ok, maybe the LCD part).
I looked for this in the Brewpi forums and the answer was to use the room temp probe, but I really didn't care for that answer as I would like to also have the room temp.
I would still want the PID running off the primary (1st) beer sensor, but it would be nice to log the temp of both fermenters (and see if there is some unexpected difference between the two).

**Comment by thorrak** [comment]
Honestly, the best solution would be to build two BrewPi controllers if you don’t want to go down the room sensor route. The second controller could even be as simple as just an ESP + one/two DS18B20s. 

Within Fermentrack the current temp/gravity data for each controller can be pulled from the API pretty easily. You could then display in whatever custom fashion you like - including overlaying the temps on the same graph if you were so inclined. 

I wish that it was easier to merge data sets but when I was originally saving data points into a database Fermentrack was incredibly slow. At some point I may add pandas integration - that would make it so we could at least do post-processing easily.

**Comment by ericbeaupre** [comment]
I would like two beer temps as well. It would be nice if at a minimum the user could select which one is being actively controlled, or even better, have new modes like, "warmest beer constant."

I'm fermenting two beers now in the same chamber and one is "beer temp" and one is "room temp". The "room temp" beer is running away exothermically and I'm having to manually adjust "beer temp" beer lower to keep "room temp" beer in check.

**Comment by acremonezi** [comment]
Fermentrack is the best!

I consider this "two beers" temp tracking capability a very nice idea.
For sure, so many people would be happy with that, because a lot of people do fermenting on two or more beers into the same time using the same fridge.

Please, evaluate the idea of reconsidering this possibility again when it is possible.

Thanks in advanced.
