### ISSUE TITLE
Simple dashboard of just the LCD

### ISSUE THREAD

**Issue by snoop6060** [thorrak/fermentrack#227]
Figured I would ask before starting messing with the code (not actually  used Django, but done a bit of flask and it looks similar). 

 I want to add a url to fermentrack that displays some very simple data, a bit like the LCD view. This is as I do not have a screen on my brewpi but do have a spare phone. So figured I could add a view that simply displayed the current temperatures on the old phone that will be permantly on a dock next to the fridge. 

What is the easiest way to do this? Perhaps its already availible?

**Comment by stone** [comment]
If you request the url: http://<ip-to-fermentrack-controller>/api/lcd/<deviceid>

You will get a json with the LCD info in it, you could use something like
"JRW - Json Response Widget" (android) to show a widget with the information
on the homescreen.
