### ISSUE TITLE
Ispindel temp not changing. 

### ISSUE THREAD

**Issue by snoop6060** [thorrak/fermentrack#233]
The graphs shows its logging but the dashboard has displayed the same temp as when I added it (19.75c). Not changed in 48 hours? 

Also is there a plan to integrate this differently? It should just be an extra sensor along side the normal thermometer etc. It displays as a different controller and I had to start it logging even tho I had a beer logging with my normal controller. Ideally it would all be on the same graph and dashboard?

**Comment by snoop6060** [comment]
Sorry I should be clearer. The graph shows the ispindel is indeed logging changes. But the dashboard is not displaying the data. It's just stuck at the initial reading.

**Comment by thorrak** [comment]
I'll have to check into the dashpanel issue. I may have screwed up some javascript somewhere - it's admittedly not a language I know well.

The integration you're looking for exists & should currently be implemented. You just need to assign the gravity sensor to a temperature controller and everything should show up on a single graph.

If it doesn't work (or you're having trouble with the assignment) let me know and I'll do what I can to help.

**Comment by thorrak** [comment]
Which URL are you seeing the issue with the temperature not changing? When I look at the dashpanel for the gravity sensor it appears like the temperature panel is updating as expected when new data points are added:

![screen shot 2018-03-10 at 10 33 37 am](https://user-images.githubusercontent.com/2457900/37243877-9488257a-244e-11e8-831a-85067c12f9fc.png)

**Comment by thorrak** [comment]
I think this was fixed along with #234 in the latest pull request. If not, please reopen with additional details and let me know.
