### ISSUE TITLE
Current Values on Dashboard incorrect

### ISSUE THREAD

**Issue by Bonners87** [thorrak/fermentrack#234]
The "current values" shown for the gravity sensors on the brewery dashboard appear to report the data incorrectly. The value reported seems to be the first value stored in the log and not the latest value.

This is also the same in the sensor dashboard, assuming this is correct here as it is showing the lowest reported value which is what I believe is intended, is this correct?

**Comment by thorrak** [comment]
Just to make sure I'm looking at the right thing, what is the path to the dashboard you're having the issue with (the part after http://raspberrypi.local/ or whatever your raspi is named)

**Comment by Bonners87** [comment]
It is on the homepage dashboard, so raspberrypi.local/. 

I'm not sure if it's anything do with using the ispindel as the gravity sensor, but looking at /api/gravity I can see the results shown are the initial results only and looking at api/gravity/ispindel/{dev id } I can see the current results.

**Comment by thorrak** [comment]
Interesting - do you mean this page?

![screen shot 2018-03-10 at 10 41 36 am](https://user-images.githubusercontent.com/2457900/37244018-a9a9d276-2450-11e8-9b69-46618cef4e22.png)

The temperature values are updating fine for me, but looking at the code I think that there is an HTML error. Out of curiosity, what web browser are you using, and what gravity sensor type (Manual, Tilt, or iSpindel)?

**Comment by Bonners87** [comment]
Yes this is the correct page.

I am using the ispindel, and noticed it using chrome with android and also with ubuntu

**Comment by thorrak** [comment]
After fixing the HTML issue on that page I connected my iSpindel, and everything appears to be updating as expected for me. Try updating from GitHub and see if it now works.

**Comment by Bonners87** [comment]
Looks good on the home dashboard and sensor dashboard.

Thanks
