### ISSUE TITLE
Constance Error 

### ISSUE THREAD

**Issue by lggrizendi** [thorrak/fermentrack#244]
In testing the new fermentrack to see the changes when i click in config  on constance in  Django administration panel receive this error:

Request Method: | GET
-- | --
http://192.168.15.5/admin/constance/config/
1.11.11
AttributeError
'str' object has no attribute 'utcoffset'
/home/fermentrack/venv/lib/python3.5/site-packages/django/utils/timezone.py in is_aware, line 261
/home/fermentrack/venv/bin/python3
3.5.3
['/home/fermentrack/venv/lib/python3.5/site-packages/git/ext/gitdb',  '/home/fermentrack/venv/bin',  '/home/fermentrack/fermentrack',  '/home/fermentrack/venv/lib/python3.5/site-packages',  '/usr/lib/python35.zip',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-arm-linux-gnueabihf',  '/usr/lib/python3.5/lib-dynload',  '/usr/local/lib/python3.5/dist-packages',  '/usr/lib/python3/dist-packages',  '.',  '/home/fermentrack/venv/lib/python3.5/site-packages/gitdb/ext/smmap']
Wed, 21 Mar 2018 22:41:26 +0000

Error during template rendering

In template /home/fermentrack/venv/lib/python3.5/site-packages/constance/templates/admin/constance/includes/results_list.html, error at line 22

'str' object has no attribute 'utcoffset'

12 | <tr class="{% cycle 'row1' 'row2' %}">
-- | --
<th>
{{ item.name }} <div class="help">{{ item.help_text\|linebreaksbr }}</div>
</th>
<td>
{{ item.default\|linebreaks }}
</td>
<td>
{{ item.form_field.errors }}
{% if item.is_file %}{% trans "Current file" %}: <a href="{% get_media_prefix as MEDIA_URL %}{{ MEDIA_URL }}{{ item.value }}" target="_blank">{{ item.value }}</a>{% endif %}
{{ item.form_field }}
<br>
<a href="#" class="reset-link"
data-field-id="{{ item.form_field.auto_id }}"
data-field-type="{% spaceless %}
{% if item.is_checkbox %}checkbox
{% elif item.is_datetime %}datetime
{% endif %}
{% endspaceless %}"
data-default="{% spaceless %}
{% if item.is_checkbox %}{% if item.raw_default %} true {% else %} false {% endif %}

12 | <tr class="{% cycle 'row1' 'row2' %}">
-- | --
<th>
{{ item.name }} <div class="help">{{ item.help_text\|linebreaksbr }}</div>
</th>
<td>
{{ item.default\|linebreaks }}
</td>
<td>
{{ item.form_field.errors }}
{% if item.is_file %}{% trans "Current file" %}: <a href="{% get_media_prefix as MEDIA_URL %}{{ MEDIA_URL }}{{ item.value }}" target="_blank">{{ item.value }}</a>{% endif %}
{{ item.form_field }}
<br>
<a href="#" class="reset-link"
data-field-id="{{ item.form_field.auto_id }}"
data-field-type="{% spaceless %}
{% if item.is_checkbox %}checkbox
{% elif item.is_datetime %}datetime
{% endif %}
{% endspaceless %}"
data-default="{% spaceless %}
{% if item.is_checkbox %}{% if item.raw_default %} true {% else %} false {% endif %}

**Comment by thorrak** [comment]
I'm guessing that you used the Python 2 --> Python 3 upgrade script. You need to access the "Firmware Flash" page once to get that error fixed - it's caused by an incompatibility in the way that the "firmware list last refreshed" option is stored in Constance.

**Comment by lggrizendi** [comment]
i run sudo curl -L install.fermentrack.com | sudo bash and correct the problem. Thanks
