### ISSUE TITLE
iSpindel not communicating to Fermentrack

### ISSUE THREAD

**Issue by Mikmonken** [thorrak/fermentrack#246]
Added iSpindel to fermentrack but it appears not to want to communcate into Fermentrack logs after install.

Attached are stderr logs following restart of logging.

[ Fermentrack (Web Application) log-fermentrack-stderr.log.txt](https://github.com/thorrak/fermentrack/files/1839217/Fermentrack.Web.Application.log-fermentrack-stderr.log.txt)
[log-dev-old larry-stderr.log.txt](https://github.com/thorrak/fermentrack/files/1839222/log-dev-old.larry-stderr.log.txt)

**Comment by thorrak** [comment]
Thank you sir! The bug was in that stderr log. Makes pushing out a fix muuuuch easier.

This should be fixed now. Update from github & let me know if it works. If it doesn't, I'll dig in further.

**Comment by Mikmonken** [comment]
Update now means it’s logging to the iSpindel graph, but not to the assigned device. Also not displaying most recent reading for temp gravity, battery etc.

**Comment by Mikmonken** [comment]
attached is the stderr and some screenshots too, it's sending through to Fermentrack but not to the assigned device or most recent readings (other than what's graphed.)

![screen shot 2018-03-23 at 07 57 14](https://user-images.githubusercontent.com/19469569/37817922-639e68a8-2e70-11e8-9016-21e7e392a413.png)
![screen shot 2018-03-23 at 07 57 43](https://user-images.githubusercontent.com/19469569/37817923-63b932b4-2e70-11e8-8d90-11bdb8527a1d.png)
[Fermentrack (Web Application) .txt](https://github.com/thorrak/fermentrack/files/1840619/Fermentrack.Web.Application.txt)

**Comment by thorrak** [comment]
Just pushed a commit that should fix this in the most asinine way possible. Going to leave this open so I remember to come back and actually fix this later.

**Comment by riisefrutti** [comment]
I have a similar issue. Fermentrack does not receive any angle data from the spindel, only temperature

**Comment by Mikmonken** [comment]
Bingo, that works, thank you.

Now off to add something to the wish list ;-)
