### ISSUE TITLE
Attribute error encountered when reassigning temperature probes

### ISSUE THREAD

**Issue by jangevaare** [thorrak/fermentrack#258]
The reassignment was successful still, but this error was provided. 
```
Exception Type: AttributeError
Exception Value: 'NoneType' object has no attribute 'device_function'
Exception Location: /home/fermentrack/fermentrack/app/views.py in sensor_config, line 263
```

**Comment by thorrak** [comment]
When you say "reassigning temperature probes" - What specifically are you doing?

Is this happening when you click "Unassign" or when you attempt to assign the probe to its new function?

**Comment by jangevaare** [comment]
This was when assigning to new function. I did have a beer in progress while I did this, and thought an error may occur as a result of that. Unsure if that is why this came up. Cheers.

On Apr 1, 2018, at 2:33 PM, John <notifications@github.com<mailto:notifications@github.com>> wrote:
When you say "reassigning temperature probes" - What specifically are you doing?

Is this happening when you click "Unassign" or when you attempt to assign the probe to its new function?

**Comment by thorrak** [comment]
After staring at the code for awhile - I'm lost. The only thing that I can think is happening is that the cache of devices is changing between when you load the "add sensors/pins" page and when you click the "Assign Device" button. Unless you have two windows open and are trying to assign the same device in both, this shouldn't happen.

...that said: I went ahead and just refactored most of the code to cause the cache to get completely invalidated after each of the "script" events above. 

This change isn't live in the "master" branch as it involved quite a bit of code changes that I don't have the ability to test at the moment. I'm hoping to push this live in about ~3-4 hours and will report back here once that's complete.

**Comment by thorrak** [comment]
The potential fix for this was uploaded about a week ago. If you have a chance to test it, please do so and let me know if it works now. If not, that's fine too. I'll leave this issue open for a bit in case someone else has a similar issue for them to come back & report in

**Comment by jangevaare** [comment]
I have a couple more ESPs on the way - will try to break things when those arrive - hopefully soon!

On Apr 9, 2018, at 10:53 PM, John <notifications@github.com<mailto:notifications@github.com>> wrote:


The potential fix for this was uploaded about a week ago. If you have a chance to test it, please do so and let me know if it works now. If not, that's fine too. I'll leave this issue open for a bit in case someone else has a similar issue for them to come back & report in

**Comment by thorrak** [comment]
I haven't heard anything, so I'm hoping that the push I did a few months back fixed it. Closing out the issue.
