### ISSUE TITLE
iSpindel stopped communicating angle to fermentrack

### ISSUE THREAD

**Issue by Mikmonken** [thorrak/fermentrack#262]
Started logging a beer, and it seems that the temp is updating but gravity been communicated as 0 degree angle.

[stderr-webapp.txt](https://github.com/thorrak/fermentrack/files/1869329/stderr-webapp.txt)
[stderr.txt](https://github.com/thorrak/fermentrack/files/1869330/stderr.txt)

[Gravity Device 4 - L6 - Summer Blonde_full 2.xlsx](https://github.com/thorrak/fermentrack/files/1869319/Gravity.Device.4.-.L6.-.Summer.Blonde_full.2.xlsx)

**Comment by Mikmonken** [comment]
It maybe that I updated cofficients shortly after starting the logging?

**Comment by thorrak** [comment]
As discussed offline, this should be resolved, but if it pops up again (or if anyone else experiences this!) please upload the contents of the "iSpindel Raw Output" log (found by clicking the "question mark" in the upper right hand corner of any Fermentrack page & scrolling to the bottom of the help page). It should look similar to this:

```
'{"name":"iSpindel123","ID":3003098,"token":"fermentrack","angle":75.59959,"temperature":25.1875,"battery":3.889468,"gravity":26.28323}'
```
