### ISSUE TITLE
Connection debugging fails on port other than 23

### ISSUE THREAD

**Issue by NamelessCoder** [thorrak/fermentrack#279]
When attempting to "Debug connection" on a BrewPi connected over WiFi, the telnet test command always tries to connect on port 23 which causes an exception to be thrown if the device is only reachable on another port.

For example, it appears the BrewPi (at least with firmware 0.5.5) uses port `6666` but even when this is configured and saved, the test connection still attempts port `23`.

I tried tracing the problem through the python source code and found one lack that may be easy enough to fix: when creating the telnet connection instance in `app/connection_debug.py` the `port` function argument is never passed.

However, even when adding this argument and forcing it to a value of `6666` for testing purposes, `/usr/lib/python3.5/telnetlib.py` does not seem to use the port that's set in `self.port` when calling `self.open()`. I also attempted to refactor `connection_debug.py` to avoid the constructor calling the `open()` function and explicitly configuring the port, with the same result - port number is seen as `None` and the default one gets used instead.

I wish I could help more, but even if I managed to refactor `fermentrack`'s source code, it sure seems like the could be a problem in the telnet library itself concerning respect for the `port` argument... hopefully the above tells you exactly what's wrong.

**Comment by thorrak** [comment]
I've created a new branch (called "modern") to handle feature changes associated with getting the OEM BrewPi working. To test this branch, you will need to enable "git branch switching" in Fermentrack. To do this:

1. Log into Fermentrack & click the "gear" in the upper right
2. Choose `Django Admin Panel`
3. Select `Config` (under the "Constance") heading
4. Tick the checkbox next to `ALLOW_GIT_BRANCH_SWITCHING` (currently the first option) & click "Save" at the bottom of the pane
5. Make sure the box remains checked after the page reloads - if not, repeat step 4.
6. Return to Fermentrack & click the "gear" once again
7. Click `Update from GitHub`
8. At the bottom of the page select the `modern` branch and click `Switch Branch`

This branch incorporates changes associated with this issue as well as issues #278, #280, and #282.
