### ISSUE TITLE
Fermentrack dead after latest update

### ISSUE THREAD

**Issue by snoop6060** [thorrak/fermentrack#284]
Latest update killed my instance. 

ImportError: No module named backports.configparser

Is that the bottom of all the stderr logs.

**Comment by thorrak** [comment]
Are you running under Python 3? How long ago was the previous upgrade (did you have the message to upgrade for a long time before clicking it, or did you just see it for the update I pushed two days ago?)

Nothing in the latest update should have triggered that aside from the upgrade of the environment that happens on every upgrade. It’s possible one of the dependencies introduced a bug - but that’s a strange bug to introduce.

**Comment by thorrak** [comment]
I haven't heard anything more on this, so I'm going to go ahead and close the issue for now. If you are still having this problem please feel free to reopen!
