### ISSUE TITLE
Gravity range is in [X, 0.0] but should be [X, 1.0]

### ISSUE THREAD

**Issue by user400479** [thorrak/fermentrack#290]
My Fermentrack page currently display gravity in the range 1.1 to 0.0 .
Although I suppose the upper bound depends on your beer profile/current set of readings the lower bound should be 1.000...
(I've uploaded an image at https://imgur.com/a/eypG9q5, check the left most y axis)

Shouldn't the lower bound be always 1.000... or how can I change this? Due to large range the gravity series looks almost constant (!)

**Comment by thorrak** [comment]
What type of gravity sensor are you using? That graph would indicate that for some reason your sensor was reporting a temperature, but wasn’t reporting gravity during that time period - which shouldn’t happen. 

The way Fermentrack handles data points doesn’t include any “reasonableness” filter - the data that is received is the data that is logged.

For the data set you show, you should be able to click and drag on the graph to zoom in to data points in that range, and the axes will adjust as needed

**Comment by jangevaare** [comment]
Worth noting @user400479 that SG can be < 1.000 - especially with ciders and meads - unless this is a technical limitation of ispindel/tilts.

**Comment by thorrak** [comment]
That makes sense. 

In this case, the 0.0 points are information, as it indicates that there’s an issue with the calibration. If the points were discarded, it would be difficult to tell if there was a connectivity issue (so no data was being received by Fermentrack) versus a situation like you described.

As @jangevaare noted, a SG less than 1 can occur (and would be valid) depending on the situation. I’d rather err on the side of logging a potentially invalid point than drop the data, just in case it’s valid. 

That said, the idea of removing erroneous data points from an existing log file is what @jangevaare and I were discussing in #289 and if implemented would probably resolve the issue you described - where erroneous data points skew your graph.

**Comment by user400479** [comment]
There are a few corner cases where gravity can be < 1.000 (for those ciders/meads where this holds, FG is typically close to 1.000, e.g. 0.99 - 0.95). So just for completeness the lower bound could be a parameter that default to 1.000
