### ISSUE TITLE
Display gravity graph and device graph at same time

### ISSUE THREAD

**Issue by goose-ws** [thorrak/fermentrack#302]
Is there a way when viewing my device's temperature graph that it can also inlay the gravity readings from the gravity sensor? Sorry to open an issue for this, I couldn't find a better way/place to ask.

**Comment by thorrak** [comment]
No worries at all - issues are as good a place to ask as any!

I’m assuming you mean you want to combine the data from your gravity sensor into the readings from a BrewPi temperature controller. If so, then yes - just attach the gravity sensor to the controller and it should work automatically. 

There should be a link to do so either from the dashboard for the gravity sensor or from its device setup page.

If that isn’t what you were looking to do (or you have issues!) let me know and I can see if there’s a better way.

**Comment by goose-ws** [comment]
Thanks for her response. You're correct, I want to combine the data on one graph.

I have attached some screenshots, I believe I have linked my Tilt to my Audrino, but the data is still separate.

![screenshot_20180820-133559](https://user-images.githubusercontent.com/874014/44356767-4c6f5780-a47e-11e8-864b-ad73e243f2d4.png)
![screenshot_20180820-133539](https://user-images.githubusercontent.com/874014/44356768-4c6f5780-a47e-11e8-8116-714b606dda4d.png)
![screenshot_20180820-133630](https://user-images.githubusercontent.com/874014/44356769-4c6f5780-a47e-11e8-8df8-bb9e75527f5c.png)

**Comment by thorrak** [comment]
If you recently linked the sensor, you will need to stop logging the existing beer & start logging a new one to get the data to appear.

**Comment by goose-ws** [comment]
Ah, got it. It should be fine for my next brew then.

Thanks for the helpful responses, and the fantastic software!

**Comment by thorrak** [comment]
Sounds good. Yell if you have any more issues!
