### ISSUE TITLE
Tilt setup as Celcius but showing temp as (F)*C

### ISSUE THREAD

**Issue by Dubzie** [thorrak/fermentrack#303]
As above,

Showing the Fahrenheit with the *C after it, fermtrack setting set the Celsius, and the Tilt was configured as Celsius,

**Comment by peteprez** [comment]
I'm having exactly the same issue on a brand new build from today.

**Comment by thegraylan** [comment]
Yeah I'm in the same boat also,

**Comment by thorrak** [comment]
Found the bug and the fix is on my laptop. Going to push it live to dev once I have WiFi available.

**Comment by thorrak** [comment]
Just pushed the fix to a new branch called "tilt-celsius-fix". I haven't had a chance to test it to make sure nothing else has broken as a result, but once I can give it a quick once-over in a live environment I'll merge to dev.

**Comment by thorrak** [comment]
One small bug with the fix - just pushed a fix for it to tilt-celsius-fix.

**Comment by peteprez** [comment]
this is working great for me now :)

**Comment by thorrak** [comment]
This appears to be working for people now - closing out the issue report
