### ISSUE TITLE
Tilt not communicating with fermentrack

### ISSUE THREAD

**Issue by Kollensperger** [thorrak/fermentrack#304]
I've done a clean install of fermentrack on raspian stretch. 
Enabled gravity measurments and installed a black Tilt.
However the tilt does not manage to communicate with fermentrack.

I've checked with `sudo hcitool lescan` and the tilt shows up there.
I've tried to connect with the sibowler's `TiltHydrometerTest.py` and that owrked fine too (on another install).
After reinstalling twice now I'm a bit stumped as to why I can't get it to work.
Any ideas?
I am using an OEM Brewpi Spark photon v2

Here are the logs:
stderr:
`NFO:processmgr:Settings: Start delay: 2s, Sleep Interval: 15s, 
INFO:processmgr:Settings: Start delay: 2s, Sleep Interval: 15s, 
INFO:processmgr:New BrewPi device found: dev-brewpi
INFO:processmgr:New Tilt device found: tilt-
INFO:processmgr:Settings: Start delay: 2s, Sleep Interval: 15s, 
INFO:processmgr:New BrewPi device found: dev-brewpi
INFO:processmgr:New Tilt device found: tilt-`

/log/tilt-black-stdout.log:
`Error opening /home/fermentrack/fermentrack/log/tilt-black-stdout.log logfile: [Errno 2] No such file or directory: '/home/fermentrack/fermentrack/log/tilt-black-stdout.log'`

/log/tilt-black-stderr.log:
`Error opening /home/fermentrack/fermentrack/log/tilt-black-stderr.log logfile: [Errno 2] No such file or directory: '/home/fermentrack/fermentrack/log/tilt-black-stderr.log'`

`Sep 11 2018 00:07:16   BrewPi version received was 0.5.10 which this script supports in 'develop' branch mode.
 Sep 11 2018 00:07:16   Warning: version number of local copy of logMessages.h does not match log version number received from controller.controller version = 4, local copy version = 3. This is generally a non-issue, as thus far log messages have only been added - not changed.
 Sep 11 2018 00:07:16   Bound to TCP socket on port 2150, interface localhost 
 Sep 11 2018 00:07:16   Installed devices received: [{"f": 9, "j": -0.004, "d": 0, "v": 21.059, "i": 0, "h": 2, "p": 0, "t": 1, "a": "28C095C0070000A7", "b": 1, "c": 1}, {"f": 5, "j": -0.004, "d": 0, "v": 18.684, "i": 1, "h": 2, "p": 0, "t": 1, "a": "28A57CC0070000A6", "b": 0, "c": 1}, {"f": 3, "x": 0, "d": 10, "v": 0, "i": 2, "h": 1, "p": 10, "t": 3, "b": 0, "c": 1}, {"f": 2, "x": 0, "d": 0, "v": 0, "i": 3, "h": 1, "p": 11, "t": 3, "b": 0, "c": 1}]
 Sep 11 2018 00:07:16   Available devices received: [{"f": 0, "x": 0, "d": 0, "i": -1, "h": 1, "p": 17, "t": 0, "b": 0, "c": 1}, {"f": 0, "x": 0, "d": 0, "i": -1, "h": 1, "p": 16, "t": 0, "b": 0, "c": 1}]
 Sep 11 2018 00:14:17   Stopped data logging, as requested in web interface. BrewPi will continue to control temperatures, but will not log any data.
 Sep 11 2018 00:15:08   Setting controller to beer profile mode using database-configured profile
 Sep 11 2018 00:51:18   Setting controller to beer profile mode using database-configured profile
 Sep 11 2018 00:51:45   Notification: Restarted logging for beer 'Hop-Cleanup IPA'.
 Sep 11 2018 01:09:25   Connection type Serial selected. Opening serial port.
 Sep 11 2018 01:09:25   Connected via serial to port /dev/ttyACM0
 Sep 11 2018 01:09:25   Notification: Script started for beer 'Hop-Cleanup IPA'
 Sep 11 2018 01:09:44   Checking software version on controller... 
 Sep 11 2018 01:09:44   Found BrewPi v0.5.10 build 0.5.10-0-gac67918, running on a Particle Photon with a V2 shield on port /dev/ttyACM0

 Sep 11 2018 01:09:44   BrewPi version received was 0.5.10 which this script supports in 'develop' branch mode.
 Sep 11 2018 01:09:44   Warning: version number of local copy of logMessages.h does not match log version number received from controller.controller version = 4, local copy version = 3. This is generally a non-issue, as thus far log messages have only been added - not changed.
 Sep 11 2018 01:09:44   Bound to TCP socket on port 2150, interface localhost 
 Sep 11 2018 01:09:44   Installed devices received: [{"b": 1, "v": 20.496, "j": -0.004, "c": 1, "t": 1, "h": 2, "f": 9, "a": "28C095C0070000A7", "d": 0, "p": 0, "i": 0}, {"b": 0, "v": 15.871, "j": -0.004, "c": 1, "t": 1, "h": 2, "f": 5, "a": "28A57CC0070000A6", "d": 0, "p": 0, "i": 1}, {"b": 0, "x": 0, "v": 0, "c": 1, "t": 3, "h": 1, "f": 3, "d": 10, "p": 10, "i": 2}, {"b": 0, "x": 0, "v": 0, "c": 1, "t": 3, "h": 1, "f": 2, "d": 0, "p": 11, "i": 3}]
 Sep 11 2018 01:09:44   Available devices received: [{"b": 0, "x": 0, "c": 1, "t": 0, "h": 1, "f": 0, "d": 0, "p": 17, "i": -1}, {"b": 0, "x": 0, "c": 1, "t": 0, "h": 1, "f": 0, "d": 0, "p": 16, "i": -1}]`

**Comment by thorrak** [comment]
Does your temperature control work as expected, or is it also having issues alongside the Tilt?

**Comment by Kollensperger** [comment]
Temperature control works perfectly. 
I can see that .../gravity/tilt/monitor.py runs as a process, but for some reason nothing shows up on the dashboard

**Comment by thorrak** [comment]
Interesting. What color is your Tilt, and do you happen to know if it is the old or new model?

Sent from my iPhone

On Sep 11, 2018, at 5:04 AM, Peter <notifications@github.com<mailto:notifications@github.com>> wrote:


Temperature control works perfectly.
I can see that .../gravity/tilt/monitor.py runs as a process, but for some reason nothing shows up on the dashboard

**Comment by Kollensperger** [comment]
It’s a black v2. Not the completely new tubing. I have a v1 as well but it just eats batteries. This one lasts longer but has the same overall design. Not sure that helps?

**Comment by thorrak** [comment]
It does - I have a different Tilt-related project that works with the old Tilts but not the new ones for some reason.

Let me try to debug a bit when I get home.

Sent from my iPhone

On Sep 11, 2018, at 7:43 AM, Peter <notifications@github.com<mailto:notifications@github.com>> wrote:


It’s a black v2. Not the completely new tubing. I have a v1 as well but it just eats batteries. This one lasts longer but has the same overall design. Not sure that helps?

**Comment by thorrak** [comment]
I think uSlackr on HBT was having a similar issue, and posted being able to run a bletools command to clear filters and restore functionality:

https://raspberrypi.stackexchange.com/questions/89414/why-cant-one-of-my-rpis-talk-to-bluetooth-device

That said, from reading the discussions he linked to, I think that the problem may be one of the underlying dependencies of `beacontools`. It sounds like the maintainers of the `bluez` library made it so the library implements some kind of beacon filtering for beacons that are sent frequently to reduce strain on low-powered systems like the RPi. Great for some projects, I’m sure, but in our case I think these filters are screening out the Tilt packets. 

There is a library mentioned - https://github.com/frawau/aioblescan - which sounds like it might not suffer from the same limitation. Assuming I can’t find a way to remove filters using `beacontools` I’m going to see if it would be possible to switch to use that library instead to scan.

**Comment by thorrak** [comment]
I just went and did (another) rip & rewrite of the tilt monitor code - the new version uses the [frawau/aioblescan](https://github.com/frawau/aioblescan) project rather than beacontools. If you're interested in testing the new code, it's in the `aio_ble` branch. 

I've got this running on my local install of Fermentrack - if everything seems to be running well after a few days, I'll merge to `dev`.

**Comment by Kollensperger** [comment]
Thanks for your effort! Once it’s merged to dev, how do I change my installation to that track?

**Comment by thorrak** [comment]
It’s already in “dev” - if you’re on Master, just wait a few more days. Going to push live to master along with some bug fixes this weekend.

Sent from my iPhone

On Oct 24, 2018, at 2:05 PM, Peter <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for your effort! Once it’s merged to dev, how do I change my installation to that track?

**Comment by thorrak** [comment]
I thiiiink this is fixed now that everything has been released. Going to close this issue for now - if you're still having problems, let me know and we can reopen it!

**Comment by Kollensperger** [comment]
I’ve just startes a new brew yesterday and updated first to master, now to dev, but i still can’t get contact to the tilt via fermentrack. 

I see the tilt on the raspberry (I think) if I call Bluetoothctl:

Discovery started
[CHG] Controller 5C:F3:70:78:21:97 Discovering: yes
[NEW] Device 6F:2D:F2:97:D1:75 6F-2D-F2-97-D1-75
[NEW] Device 78:4B:08:03:F0:FE Mo0111
[NEW] Device 4D:3E:5E:96:70:31 4D-3E-5E-96-70-31
[CHG] Device 4D:3E:5E:96:70:31 ManufacturerData Key: 0x004c
[CHG] Device 4D:3E:5E:96:70:31 ManufacturerData Value: 0x10
[CHG] Device 4D:3E:5E:96:70:31 ManufacturerData Value: 0x05
[CHG] Device 4D:3E:5E:96:70:31 ManufacturerData Value: 0x07
[CHG] Device 4D:3E:5E:96:70:31 ManufacturerData Value: 0x1c
[CHG] Device 4D:3E:5E:96:70:31 ManufacturerData Value: 0xb3
[CHG] Device 4D:3E:5E:96:70:31 ManufacturerData Value: 0x28
[CHG] Device 4D:3E:5E:96:70:31 ManufacturerData Value: 0x12
[bluetooth]# 

I’ve tried to see the tilt via aioblescan but I get the following error message:
pi@raspberrypi:~ $ python3 -m aioblescan
Fatal write error on socket transport
protocol: <aioblescan.aioblescan.BLEScanRequester object at 0x76428270>
transport: <_SelectorSocketTransport fd=6 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 761, in write
    n = self._sock.send(data)
PermissionError: [Errno 1] Operation not permitted  

Any ideas?

**Comment by uSlackr** [comment]
@Kollensperger  Take a look at this thread: https://www.homebrewtalk.com/forum/threads/fermentrack-fermentation-monitoring-brewpi-www-replacement-for-raspberry-pi.649303/page-4#post-8403107

**Comment by thorrak** [comment]
Try running the command in sudo

It sounds like a permissions error (which is odd, as the permissions should have been set at install-time)

**Comment by Kollensperger** [comment]
Strange, I get 
‘pi@raspberrypi:~ $ sudo python3 -m aioblescan
/usr/bin/python3: No module named aioblescan
pi@raspberrypi:~ $’

I also tried 
‘python3 -m pip install aioblescan’
And ran the command as sudo again but same result.

**Comment by Kollensperger** [comment]
Ok I also ran the install as sudo and now aioblescan works and I can see the tilt. 
However after 5 min on a 2 min log cycle, fermentrack is still not showing the data...
