### ISSUE TITLE
Dashboard display problem after updating to August 6 version

### ISSUE THREAD

**Issue by user400479** [thorrak/fermentrack#305]
I used the upgrade tool (accessed through Fermentrack's settings page -> "Configuration Tools" -> "Update from GitHub") to update my Fermentrack copy to the latest version, Aug. 6, 2018, 12:42 a.m.

But as I went back to the temp controller dashboard I noticed that the log was scrambled and the new temp readings wasn't updated, as per:
![brewpi](https://user-images.githubusercontent.com/41307349/46173318-2ec7b600-c2a6-11e8-97d9-7fd10bbbd509.png)

From checking the logs and "Configure Sensors/Pins" page I can see that temperature controller readings are correct, they just seem to be displayed incorrectly on the dashboard (!).

Any idea why this is happening?

**Comment by thorrak** [comment]
The only thing I can think is that there was some kind of disk corruption of some of the javascript which led to this. Is your installation still working/are you still having issues?

**Comment by user400479** [comment]
Yes it is still not working unfortunately,
Could this disk corruption be due to the update script? I have so far not experienced any disk related issues on the system where fermentrack is installed.

Also, how can I fix this issue? do I need to reinstall fermentrack and if so is there a script that provide this functionality? or a script that completely removes fermentrack?

**Comment by zacharybussey** [comment]
If it is a JS issue, you should be able to see some kind of error message in the browser console.  If you navigate to the dashboard page, and then hit F12, it will open the dev tools.  Then, you should see a tab called Console.  Refresh the page and see if any messages appear.

**Comment by user400479** [comment]
@zacharybussey Thanks for pointing this out, I do actually get a JS error where you mentioned it would be:

Error: request failed with status 404
URL: http://192.168.1.117/static/vendor/bootstrap/css/bootstrap.min.css
Source-URL: bootstrap.min.css.map

(Where 192.168.1.117 is the IP of the machine that runs fermentrack)

Any idea what could be the cause and how to fix it?

**Comment by user400479** [comment]
@zacharybussey @thorrak any idea how to fix this bug?

**Comment by thorrak** [comment]
This bug has since been fixed. Closing the issue.
