### ISSUE TITLE
Error when setting a Temprature Calibration value.

### ISSUE THREAD

**Issue by zacharybussey** [thorrak/fermentrack#308]
I get the following error dump whenever I assign a pin with a calibration value set.

```

Request Method: | POST
-- | --
http://192.168.1.221/devices/1/sensors/config/
1.11.15
TypeError
Decimal('2.0') is not JSON serializable
/usr/lib/python3.5/json/encoder.py in default, line 179
/home/fermentrack/venv/bin/python3
3.5.3
['/home/fermentrack/venv/lib/python3.5/site-packages/git/ext/gitdb',  '/home/fermentrack/venv/bin',  '/home/fermentrack/fermentrack',  '/home/fermentrack/venv/lib/python3.5/site-packages',  '/usr/lib/python35.zip',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-arm-linux-gnueabihf',  '/usr/lib/python3.5/lib-dynload',  '.',  '/home/fermentrack/venv/lib/python3.5/site-packages/gitdb/ext/smmap']

```

Clearing the input allows the temp sensor to save.

I poked around a little bit, but I don't know Python well enough to narrow in on what is going wrong.  Thanks for putting this project together.

**Comment by thorrak** [comment]
I have what I think is a fix on my laptop for this. Going to push later today to the aio_ble branch and test tonight.

**Comment by zacharybussey** [comment]
So, saving the value is fixed now.  Thank you.

But, the saved value is a little bit different.  I saved a value of `2.088`, but, that temp probe now reports `Temp Calibration Offset: 2.023`.  Which is close enough, but, I thought it was a bit odd.  Going to close this issue though.
