### ISSUE TITLE
favicon displays for Django admin but not Fermentrack pages

### ISSUE THREAD

**Issue by meirion** [thorrak/fermentrack#313]
<img width="591" alt="screen shot 2018-10-12 at 09 31 46" src="https://user-images.githubusercontent.com/324459/46857807-b3b3e300-ce01-11e8-9a0e-ab8b7165ace0.png">

I've noticed the Django admin site displays a fermentrack Favicon in the browser, but the main Dashboard does not. It's a cool icon, let's see it!

Also, be nice to see the logo on the dashboard in the header.

**Comment by goose-ws** [comment]
Does your browser console show it as missing? The browser should be checking for /favicon.ico without it having to be proactively sent/served by the webserver.

**Comment by thorrak** [comment]
I think I found the issue -- The main template for Fermentrack doesn't have a properly-formed link to the favicon in the header. I've pushed a fix to the "pushout" branch which I *think* will be the next branch to be completed/merged to dev - if I end up working on something else instead, I'll add the fix then.
