### ISSUE TITLE
Temp from Tilt not showing in beer temp

### ISSUE THREAD

**Issue by k0zTheory** [thorrak/fermentrack#326]
The temp from Tilt is not showing in the LCD view for the fermenter (in fermentrack site).
Unsure if the temp controller then uses the actual beer temp.

Setup:
Temp probe in chamber
Tilt for beer temp

Mode   Beer Profile 
**Beer   --.-  10.0 °C**
Fridge  3.4   1.0 °C
Idling for     43m12

The Tilt is assigned to the temp controller.
Couldn't find this as an issue, but will close if duplicate.
Can add logs or other information as needed.

**Comment by thorrak** [comment]
This is intentional/expected. The BrewPi controller firmware currently does not have provisions for accepting temperatures that are fed in via any mechanism other than a wired DS18b20, and the “LCD” view is intended as a view into what the firmware knows/is displaying. The “beer” temp is therefore the reading from the beer sensor connected to the controller - which it sounds like is currently disabled/nonexistent. 


As an aside, the reason you probably don’t want to use the Tilt as a beer temp sensor is that the resolution of the sensor isn’t fine enough. The Tilt reads in whole degrees, while the controller is attempting to control to a far tighter range.

**Comment by k0zTheory** [comment]
Thank you for the clarification. I will add an additional temp probe in a thermowell for the beer temp. Was thinking that the temp in Tilt would be adequate, but realize this is not true for the level of precision required.

Hoped that Tilt would cover both temp and gravity for beer in my setup since the ideal is something like what is outlined in issue #287

**Comment by k0zTheory** [comment]
Have had some issues (all explained somewhere) installing fermentrack and the additional parts . Would like to help in updating documentation and suggestions ++(noobs version), ideally with corrections from you. Don't want to directly publish without corrections.
Love what your aiming at with the project.
PM me if you would like this.

**Comment by thorrak** [comment]
Any help - especially with documentation - is greatly appreciated. There isn’t a way (that I know of at least) to PM on GitHub - feel free to reach out on reddit (/u/lordfili) or homebrewtalk (Thorrak) if you like!

Sent from my iPhone

On Nov 13, 2018, at 5:56 PM, k0zTheory <notifications@github.com<mailto:notifications@github.com>> wrote:


Have had some issues (all explained somewhere) installing fermentrack and the additional parts . Would like to help in updating documentation and suggestions ++(noobs version), ideally with corrections from you. Don't want to directly publish without corrections.
Love what your aiming at with the project.
PM me if you would like this.

**Comment by uSlackr** [comment]
Is it for the docs in GitHub?  If so, you can clone. edit and submit a request.  The GitHub UI allows you to do that all in the browser.

**Comment by andrewrjones** [comment]
I had the same expectation as @k0zTheory so was surprised the beer temp wasn't being set until I found this issue.

Is this something BrewPi just can't/doesn't support? Or would it be possible to either:

1. Optionally use the gravity sensor temperature as the beer temp (maybe with a warning on accuracy)
2. Have a control mode of _Gravity Sensor Temp Constant_ or similar, alongside fridge and beer constant

Even with the accuracy issues, I think it would be better to use that than nothing for those of us without a thermowell.

I may be able to work on the implementation of one of these options if any are feasible, though may need some pointers to get started :) Thanks!

**Comment by uSlackr** [comment]
Fermenttrack and brewpi are designed to control temps to .1 of a degree. Using it with a tilt breaks that capability. It can be done using fuscue (I think that’s right) but you are giving up a lot.
You’d be better taping your probe to the outside with a piece of insulation covering it.
Also, thermowells are pretty easy. If you use a bucket you can find one that inserts down through the bucket lid.

\\\\ Greg
________________________________
