### ISSUE TITLE
Script starting up

### ISSUE THREAD

**Issue by Option113** [thorrak/fermentrack#327]
In Dashboard for my BrewPi temperature Controller i get the constant message"Script Starting Up".
It doesen't show the intended values.

Can someone please help?

**Comment by thorrak** [comment]
Are you still having this issue? 

Unfortunately, this is a pretty generic problem - when you see the "script starting up" message it can indicate a number of problems with your setup. How are you connecting to your BrewPi controllers? (Serial? WiFi?) What kind of controllers are they? (ESP8266-based? Arduino based? OEM?)

**Comment by thorrak** [comment]
I haven't heard anything, so closing this issue. If you're still having this problem let me know and we can reopen/address!
