### ISSUE TITLE
Control constantants

### ISSUE THREAD

**Issue by scouseboy999** [thorrak/fermentrack#329]
Hi There,

I am just getting to grips with the supeperb software and web front end.  I would like to know were some information relating to control constants can be found.  Such as which factors after cooling and heating delay and which variable affects the compressor delay,

Cheers

**Comment by thorrak** [comment]
The control constants should be documented on the control constants page, as well as in the code [here](https://github.com/thorrak/fermentrack/blob/cb332f8be73baf3ef2b46fae300b89298e1ad550/app/models.py#L1887). In truth, you really shouldn't have to edit these manually -- the defaults are normally OK for most setups aside from Glycol.
