### ISSUE TITLE
"Load Past Log" button on Dashboard not working

### ISSUE THREAD

**Issue by x2harry** [thorrak/fermentrack#350]
After update, March 18, 2019, 3:29 a.m.
The "Load Past Log" button on the Dashboard is not working.
When clicked it brings up Set Temp Control window instead.

**Comment by thorrak** [comment]
Apparently that line of code has been broken for the past two years... 😱 

Thanks for reporting that - it should be fixed when I merge the branch its on (hopefully later today)

**Comment by thorrak** [comment]
This should be on the dev branch now. Update your copy of Fermentrack and this should be fixed!
