### ISSUE TITLE
Cannot add calibration point

### ISSUE THREAD

**Issue by uSlackr** [thorrak/fermentrack#367]
I'm trying to add a calibration point to my Tilt.  On the Manage Sensor page for the Tilt, I click the Add Calibration point button and nothing happens.  I clicked the Guided Calibration button and it seems to work.

I'm running dev branch and checked that it was current. 
If it helps, access.log is logging nothing when I click.  Error.log is empty.

**Comment by bjornsol** [comment]
Having the same issue with the button not doing anything when pressed. Haven't checked if it's an error in the web page coding, but it seems that it has no action when pressed except changing color.

**Comment by vanosg** [comment]
This issue can be closed
