### ISSUE TITLE
Automatic or semi automatic install not pinging github

### ISSUE THREAD

**Issue by btozz** [thorrak/fermentrack#368]
Hope this is the right way to let you know!
When using Automatic or semiautomatic install, the install.sh script stops (maybe just for me and not elsewhere?) after failing the check for internet (internet is available). For some reason ping gets no returns from github.com within the script -or manually from the r-pi or a PC on the same wifi, did try firewall checks etc. in the end I just modified the script to ping google.com instead to check- all went fine after that. Thanks!

**Comment by uSlackr** [comment]
FWIW, `ping github.com` works fine on my pi.

**Comment by btozz** [comment]
Agreed. The test (ping)is fine, but something between github.com and my network is not- dns or firewall issue? Will test again tonight to see if it is persistent. Wierd as the downloads from github went fine, just no ping returns.

**Comment by kurtjcu** [comment]
github does not ping from everywhere, would be better to use a list of possible alternatives? I used my own server but would not google.com be a better alternative?

**Comment by vanosg** [comment]
This issue can probably be closed now?

**Comment by thorrak** [comment]
Agreed with @vanosg - Item was solved in a release earlier this year
