### ISSUE TITLE
Brewfather push support

### ISSUE THREAD

**Issue by daveconde** [thorrak/fermentrack#370]
It would be awesome to be able to push data to brewfather.app

**Comment by bjornsol** [comment]
I agree, and it's been suggested for some time (see #277 )

**Comment by thorrak** [comment]
It’s coming, I’ve just been busy and not coding much the past month or so

Sent from my iPhone

On Jun 19, 2019, at 9:28 AM, Bjørn Winther Solemslie <notifications@github.com<mailto:notifications@github.com>> wrote:


I agree, and it's been suggested for some time (see #277<https://github.com/thorrak/fermentrack/issues/277> )

**Comment by edtacey** [comment]
I am keen to make this work as well 
Is there anything I can do to assist
from my review of formats there is some transformation reuquired from Fermenttrack post to brewfather custom json but all the data is there.
I was going to stick some middle where like node-red etc to do this but naturally would be better to do this direct out of ferment track.
