### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by zrgravity** [thorrak/fermentrack#372]
I've created a docker image of fermentrack. The install script has to be modified a bit for the install, due to some things not working right in a docker build command.

https://github.com/zrgravity/fermentrack-docker

https://hub.docker.com/r/zrgravity/fermentrack

**Comment by vanosg** [comment]
This and #412 can probably be closed now?

**Comment by thorrak** [comment]
Yep, definitely @vanosg . Working on a feature update at the moment and am trying to go through and clean up some issues -- closing this one out as a result.
