### ISSUE TITLE
Add support for OLED I2c displays

### ISSUE THREAD

**Issue by guiwood** [thorrak/fermentrack#374]
As a suggestion, include support for OLED displays. They have been already implemented in the Brewpiless, so supporting BPL firmware may be a solution as well.

Thanks for this great software!

**Comment by thorrak** [comment]
I think that you raised this for the wrong project - support for a specific display type would need to be in the firmware, as opposed to in Fermentrack.

I've added an issue to that project that can be tracked here: https://github.com/thorrak/brewpi-esp8266/issues/33
