### ISSUE TITLE
"Please correct the error below", Tiltbridge field "requires entry" when changing Tilt configuration.

### ISSUE THREAD

**Issue by TigNewton** [thorrak/fermentrack#379]
I have two Tilt hydrometers connected to my Fermentrack setup(Commit Date: | April 28, 2019, 8:06 a.m.). Both installed without issue and are  functioning as expected. 

I tried to change the polling frequency. I enter the Django admin page, select tilt configurations. I see both Tilts listed. In the "sensor" column I select the tilt I want to change and the "Change Tilt Configuration" page displays.

I change the value in the "Polling Frequency" field and save the changes.

I then receive an error "Please correct the error below", Tiltbridge field "requires entry" (it has the default "--------" entry). The "Connection type" is Bluetooth but it insists that I need to add Tiltbridge device name.

I discovered that If I add a "dummy" Tiltbridge device and use that name to fill in the "Tiltbridge" field I can then save the configuration with a connection type set to bluetooth.

**Comment by thorrak** [comment]
This is happening in the Django admin, or in the settings page from the actual Fermentrack app?

**Comment by TigNewton** [comment]
Please excuse my ignorance, I am not yet very well versed with Fermentrack but I believe it is in the Dejango admin.

I get there using the following procedure:

From within Fermentrack (home page) I click on the "Site Settings" gear icon. The "App Settings" page opens.

I then click on "Dejango Admin Panel" and enter my password. The "Dejango Administration" page opens.

I scroll down to the "GRAVITY" section and click on "Tilt configurations". A page opens with "Select tilt configuration to change".

In the "sensor" column I select the tilt I want to change and the "Change Tilt Configuration" page displays.

It is from this page I make my changes and ultimately receive the error message after clicking on "Save"

User "RedwoodMonkey" has also duplicated the error and offers a solution in post #837 of this link:
https://www.homebrewtalk.com/forum/threads/fermentrack-fermentation-monitoring-brewpi-www-replacement-for-raspberry-pi.649303/page-21#post-8689272
