### ISSUE TITLE
Fermentrack captures Tilt diagnostic code

### ISSUE THREAD

**Issue by vanosg** [thorrak/fermentrack#386]
The Tilt will display the firmware version for 5 seconds upon wakeup. The temperature will show a value of 999 (a flag indicating version number, not actually temperature) and SG will show as 1.004 (this is the latest tilt firmware version number, not actually the SG). If Fermentrack is logging, it captures these values as valid values and can skew the graph.

Steps to reproduce:
* Set Tilt to sleep mode
* Start logging (no values will appear)
* Wake Tilt up
* Look at current temperature values shown and graph

Fermentrack will capture the high value (999) as a valid temp reading, and interpolate that with the other temperature readings.

Logs below show additional detail

[Gravity Device 3 - L8 - error2_graph.txt](https://github.com/thorrak/fermentrack/files/3757736/Gravity.Device.3.-.L8.-.error2_graph.txt)
[Gravity Device 3 - L8 - error2_full.txt](https://github.com/thorrak/fermentrack/files/3757737/Gravity.Device.3.-.L8.-.error2_full.txt)

**Comment by uSlackr** [comment]
is there a way to query the device directly for the version so it can be reported on the status page?  I rarely have Fermentrack logging when I first activate the Tilt
