### ISSUE TITLE
Temperature offset calibration

### ISSUE THREAD

**Issue by brendongough** [thorrak/fermentrack#393]
Feature rather than issue. It would be great to be able to perform temperature calibration of iSpindels and/or ESP brew controller probes. Whilst most manufacturers have a +/-0.5c calibration on the temp probes, it would be good to be able to place an offset against the temperature reported. It would be a good feature for people with lab calibrated sensors with a much tighter tolerance, attempting to get a more true reading.

**Comment by lbussy** [comment]
While I agree in general any reading should be subject to a calibration, keep in mind that the temperature sensor there is not in a good environment.  It’s within a tube, floating half in and half out of the wort, and there is the potential for some heating from the controller.

Testing shows these to be fairly close, but I would not put it in the realm of lab quality calibration capability.

**Comment by thorrak** [comment]
This feature already exists I think - at least for the BrewPi Controller linked sensors. I don’t remember where the field to update the calibration offset is, however.  Let me check when I get home.

**Comment by lbussy** [comment]
You’re right - I have a link somewhere.  Like you said it’s for the direct attached probes.  It’s controller-based so not able to directly be applied to the gravity sensor devices.

**Comment by lbussy** [comment]
As usual, day_trippr did a how-to:

https://www.homebrewtalk.com/forum/threads/howto-make-a-brewpi-fermentation-controller-for-cheap.466106/page-140#post-7574340

**Comment by thorrak** [comment]
I just checked, and the temperature calibration offset is available for the temp sensor sattached to BrewPi controllers in Fermentrack. You will need to un-assign and re-assign in order to set the calibration offset:

<img width="1216" alt="Screen Shot 2019-11-29 at 10 59 43 AM" src="https://user-images.githubusercontent.com/2457900/69880463-f51e8080-1297-11ea-8f78-ad85cb73a95b.png">
