### ISSUE TITLE
Official docker?

### ISSUE THREAD

**Issue by tethyso** [thorrak/fermentrack#412]
As per title, any plan for an official up-to-date docker?

**Comment by thorrak** [comment]
As of two weeks ago, yes. :)

Originally I wasn’t planning on it, but after getting a device that is better suited as a docker host than VM host, I’m now looking into it. Part of the conversion will require some broader configuration changes though - I’m still figuring that bit out.

**Comment by tethyso** [comment]
That's very good news!
Let me know if you need help in beta testing, I'll use this on my Unraid machine!

**Comment by danielatkins** [comment]
I'm also interested in beta testing docker containers for Dermentrack. I do
have it running in docker currently, but I'm certain it can be done better.

**Comment by snixon** [comment]
I'm interested in helping out here if I can as well.

@thorrak are you going to base off of https://github.com/thorrak/fermentrack/issues/372 this work?  Or do you have something else cooking?

**Comment by ouranos** [comment]
@thorrak any progress on this?

I'd be happy to look into it and work on a PR :)

**Comment by thorrak** [comment]
I will take all the help I can get with this - I remember running into _some_ issue back in January and switching gears, though of course I don't have any notes to recall what that issue was. 

I anticipate issues with the bluetooth/serial integration from Docker-hosted versions, but I'm OK with that given that [TiltBridge](https://github.com/thorrak/tiltbridge) can handle what we need Bluetooth for and everything else can come through WiFi for those who choose to use Docker.

**Comment by goose-ws** [comment]
Curious to know if there's any updates on an official Docker image?

I've found these two:
https://github.com/zrgravity/fermentrack-docker
https://github.com/travisbaker/fermentrack-docker-pi

But both appear to be abandoned in terms of commits.

**Comment by thorrak** [comment]
**The short answer is:** It's coming, but probably not for awhile

**The long answer:**

I'm currently working on another brewing-related project for which I decided at the outset to distribute primarily via Docker containers. This is the first Docker-distributed project I've worked on, and so I'm using it to learn how to properly create & maintain containers. 

There are actually quite a few things that I'm doing in that project which Fermentrack could benefit from - in addition to containerization, I'm targeting 90%+ test coverage, converting to use class-based views, adding localization support, etc. My goal - once I finish with that project - is to come back and apply a lot of the lessons learned to Fermentrack. When that happens, one of the first things I'm going to do is get Fermentrack installable via container.

If nothing else, had I used Docker from the beginning we could have avoided all the problems that came with the Django 3.0 upgrade (See: #463 and all the fun that came with it) as simply replacing the container would have upgraded Python. Again: Lessons learned.

**Comment by thorrak** [comment]
> I will take all the help I can get with this - I remember running into _some_ issue back in January and switching gears, though of course I don't have any notes to recall what that issue was.
> 
> I anticipate issues with the bluetooth/serial integration from Docker-hosted versions, but I'm OK with that given that [TiltBridge](https://github.com/thorrak/tiltbridge) can handle what we need Bluetooth for and everything else can come through WiFi for those who choose to use Docker.

One benefit to my latest project is that I've managed to solve the issues of Serial integration. Potentially Bluetooth as well, but I haven't tested it yet as it's not (yet) required for that project.

**Comment by mp-se** [comment]
I've created a docker image of fermentrack that anyone is welcome to test (feedback is appreciated). I will start to use it myself on my Synology NAS. So far I have done limited testing (have not tired bluetooth and firmware flashing) but iSpindel and BrewPI seams to work. the project can be found here; https://github.com/mp-se/fermentrack-docker.

**Comment by mp-se** [comment]
Ive also published built images on docker hub under mpse2/fermentrack-docker.

**Comment by thorrak** [comment]
An official Fermentrack docker image is nearing completion, designed to be part of a docker-compose stack. I'll post more information as things get nearer. Still, there are docker branches of this repo and [fermentrack-tools](https://github.com/thorrak/fermentrack-tools/tree/docker) which contain the current version of both the install scripts and the info needed to build the images. Here's the docker-compose [configuration file](https://github.com/thorrak/fermentrack/blob/docker/production.yml) detailing what all goes into the docker-compose stack.

There's still quite a bit left to do. By my count, I need to check the following (all of which potentially could have issues):

- [ ] Test serial connections to BrewPi controllers
- [ ] Test wifi connections to BrewPi controllers
- [ ] Test mDNS resolution of unconfigured wifi BrewPi controllers
- [ ] Test Bluetooth connections to Tilt hydrometers
- [ ] Test firmware flashing
- [ ] Test GitHub update process
- [ ] Test serial connections to BrewPi controllers
- [ ] Test TiltBridge auto-set-up procedure

If anyone can think of anything else likely to break that I should test, please drop it in this issue!

**Comment by thorrak** [comment]
I'm starting to get some of these features tested, but I've run into problems thus far with two of them - mDNS and Bluetooth support. Here's where I'm at:

## **mDNS**

I have made the changes necessary to my dockerfile to get `avahi-browse` to work from within the container -- but thus far I haven't had success getting `python-zeroconf` to work. I know that `avahi-browse` relies on d-bus (which I have [linked to the host's `avahi-daemon`](https://stackoverflow.com/questions/30646943/how-to-avahi-browse-from-a-docker-container), hence why it works in the container) and `python-zeroconf` relies on multicast DNS directly from the host - but I think the way the network configuration currently works the multicast messages don't make it to the host network.

I saw someone mention a [mdns-repeater](https://github.com/kennylevinsen/mdns-repeater) which sounds like a potential option to bridge the gap between the docker network and the host network, but I haven't had a chance to test it yet. 

Alternatively, I could set everything up to use host networking but I _really_ don't want to go down that path as it causes the docker-compose stack to no longer be self-contained.


## **Bluetooth**

Bluetooth I'm a bit stuck on. As currently designed I keep getting `ERROR:tilt:Unable to create socket - [Errno 97] Address family not supported by protocol` errors from the tilt monitor which is strange. To see the bug directly, you can use the following script:

```
import socket
sock = socket.socket(family=socket.AF_BLUETOOTH, type=socket.SOCK_RAW,proto=socket.BTPROTO_HCI)
```

The best answer I've found is that this is once again a case of the network-mode not being "host", but that seems _very_ odd if that's the case given the error. I need to create an example container to test with that has the network mode set to host but haven't yet had a chance.

**Comment by thorrak** [comment]
> ## **Bluetooth**
> ...
> The best answer I've found is that this is once again a case of the network-mode not being "host", but that seems _very_ odd if that's the case given the error. I need to create an example container to test with that has the network mode set to host but haven't yet had a chance.

I created this test container tonight, and sure enough - it seems to work just fine so long as I have docker-compose configuration set to use `network_mode: "host"`. Unfortunately, this is undesirable for a number of reasons. 

**Plan B for Bluetooth:** Migrate the tilt monitor to its own container, and have it send reports to Fermentrack via HTTP rather than through redis.

**Comment by vanosg** [comment]
For experimentation purposes, in the entrypoint script, try running ```/etc/init.d/dbus start```   and    ```/usr/libexec/bluetooth/bluetoothd --debug &```

You'd want to make sure bluez isn't running on the host machine first. I also think this would require the container to be run in privileged mode if it wasn't already

**Comment by thorrak** [comment]
> For experimentation purposes, in the entrypoint script, try running `/etc/init.d/dbus start` and `/usr/libexec/bluetooth/bluetoothd --debug &`
> 
> You'd want to make sure bluez isn't running on the host machine first. I also think this would require the container to be run in privileged mode if it wasn't already

Wouldn't that prevent the host from using Bluetooth though? (ie - no Bluetooth mice/keyboards?)

**Comment by mp-se** [comment]
A tip could be to have a look at home assistant (https://www.home-assistant.io/integrations/bluetooth_le_tracker/) since they have bluetooth LE support in their docker distro. 

There might be some tips that can be used. I will see if I can get something to work in a fresh docker image.

**Comment by thorrak** [comment]
Everything I've read makes it sound like there are only two options for Bluetooth support:

- Use the host network (and lose network isolation for the container)
- Kill the Bluetooth support on the host and only run it in the container

I'm not a huge fan of either option, but I'm leaning towards supporting the former - at least as a stopgap until I can figure out another solution. If I throw every container into `net=host` mode, we're no worse off than if each of the services was installed on bare metal. Ideal? Absolutely not - but _strictly speaking_ it would work...

**Comment by goose-ws** [comment]
On my Plex server, I was able to allow my container to utilize my PCI video capture card by exposing `/dev/dvb` from the host to the container. Perhaps the bluetooth device could be exposed in a similar manner? I have a USB bluetooth dongle, don't have it built into the board of my r.pi2b, and I can't seem to locate anything in `/dev/` that looks like a bluetooth adapter, but perhaps it's exposed elsewhere?

**Comment by thorrak** [comment]
> On my Plex server, I was able to allow my container to utilize my PCI video capture card by exposing `/dev/dvb` from the host to the container. Perhaps the bluetooth device could be exposed in a similar manner? I have a USB bluetooth dongle, don't have it built into the board of my r.pi2b, and I can't seem to locate anything in `/dev/` that looks like a bluetooth adapter, but perhaps it's exposed elsewhere?

Heh - that's actually [how I set things up](https://github.com/thorrak/fermentrack/blob/335ddfcd683f9cf9f6d7e69d23e9c6f0dfdd72e2/production.yml#L19) to allow for the firmware flashing/serial controller connectivity to work. I ended up binding all of `/dev` though rather than individual devices, as it's hard to know which/how many devices people might use in advance.

Unfortunately for Bluetooth support, though, I've had this linked from before I started testing things, so I think you're correct in thinking there isn't a way that Bluetooth support can be similarly linked (at least not through /dev). Doing some research, it sounds like Bluetooth access has to do with [restrictions in the kernel](https://github.com/moby/moby/issues/16208#issuecomment-349676784) and the fact that Bluetooth connections are accessed through the host's networking namespace. It might be possible to create a separate binary to run the Tilt monitor that could be set to enter the host's namespace using `nsenter` but as that still sounds like it would require a rewrite of the way that the Tilt monitor communicates to the rest of Fermentrack, I'm leaving that route unexplored for now.

**Comment by thorrak** [comment]
Bluetooth and mDNS both works as long as I set `network_mode: host` for all the images. Again - this is _not_ how I would like things to work long term - but it's good enough for now as it's no worse than how it currently works (i.e., for non-docker installs).

**Comment by thorrak** [comment]
Alrighty. All the base functionality is now in and tested under Docker. Next up is to ensure that non-docker installs still work with the Docker-compatible code. 

Consider this "unsupported alpha code", but if anyone wants to play with the docker image as-is, you can install it using (for now):

`curl -L https://raw.githubusercontent.com/thorrak/fermentrack-tools/docker/automated_install/auto-docker-install.sh | sudo bash`

**Note** - this script WILL fail at the very end if you have something on port 80 (like an existing Fermentrack install)

**Comment by zeister** [comment]
Howdy everyone, I'm trying to get this up and working  on my Synolology NAS.  @mp-se ,  when i try to run your image I  am getting an error that  says "Volume  for  data and / or database is NOT mounted. Aborting startup ..." Any help would be greatly appreciated!

**Comment by thorrak** [comment]
Official docker support has since been released. Closing this issue.
