### ISSUE TITLE
Tilt SG spikes?

### ISSUE THREAD

**Issue by KnoAll** [thorrak/fermentrack#413]
I have just setup a new install of Fermentrack for my new Tilt that I got for the holidays. I have been running some tests over the last few days and am seeing periodic spikes in SG. It shows expected SG for the bulk of the time but it will spike wildly high for a couple of minutes (depending on logging interval) and then return to the expected values.
For example it will show 1.002 for hours and then spike to 1.843 for a minute before returning.  I've tried several logging intervals from 15s to 3m with similar results.
 I have gotten in touch with Tilt support and they have not seen this before. I have tried logging with the Tilt app to a google sheet, but did not see the same results. I suspect this is due to the Tilt logging interval of only as small as every 15m.
Has anyone else seen this behavior?

**Comment by uSlackr** [comment]
I see this regularly.  I commented on issue #325. I edit the graph data file to remove the spikes.

**Comment by lbussy** [comment]
Have you seen it outside of Fermentrack?  Because I have not seen it myself.

**Comment by KnoAll** [comment]
I have not seen it outside of Fermentrack, but as I said the only other thing I have tried is the native Tilt app w/ google sheets push and it only logs every 15m.

I checked the version of the Tilt and it is a v3 board.

**Comment by uSlackr** [comment]
When I see it, there are usually 5-6 lines in the graph data file that are out of whack then it drops back to normal.  I wonder whay the smoothing function isn’t handling them.

\\Greg

**Comment by KnoAll** [comment]
Same for me. It is only spiked for 1-2m. I'm still seeing it at slower intervals. I'm currently testing 5m logging on the Tilt and I get a single entry spike at that interval but am seeing it. At 15s logging I would see between 3-6 intervals at the spiked temp.

**Comment by lbussy** [comment]
I'd think there's a bug here somewhere based on that.  The Tilt does not spike like that.

**Comment by KnoAll** [comment]
Yes, there may be a bug. I've been running Tilt's TiltPi RaspberryPi image and am on 12s logging. It's been running for over 3 hours and I have not seen any spikes. There has only been a .001 variance in SG.
I'm going to leave it run overnight and we'll see.

**Comment by KnoAll** [comment]
OK, So the TiltPi logging ran overnight recording a reading every 12s. DId not see a single spike. Still only .001 variance in SG over the entire sample. Not sure where to go from here.

**Comment by thorrak** [comment]
Weird. I was thinking that it was one of the tilt diagnostic codes that was being captured, but as long as you're on the latest version of Fermentrack (the one that was released ~1 month ago) then this shouldn't be the case. Let me think about how I could add some diagnostics to better capture it and I'll come back to you.

**Comment by KnoAll** [comment]
Yes, I've been on the current version. Thanks so much, I love this project and am happy to help however I can. I am not a developer but am an IT Infrastructure guy so I am technical.

**Comment by KnoAll** [comment]
I thought for context i would show the logs that I have gotten. One is from TiltPi and the other from Fermentrack so you can see how little the SG changes in TiltPi vs Ft
[log-1.txt](https://github.com/thorrak/fermentrack/files/4036066/log-1.txt)
[Gravity Device 2 - L7 - TiltTest8_full.txt](https://github.com/thorrak/fermentrack/files/4036067/Gravity.Device.2.-.L7.-.TiltTest8_full.txt)

**Comment by KnoAll** [comment]
Not sure if the updates were meant to address this, but I'm still seeing it. Started a new brew yesterday and spikes are still happening.

**Comment by daveconde** [comment]
Are you using a pi3 by any chance? I was seeing spikes and would have to restart the pi due to the Bluetooth connection hanging. I applied the changes at https://github.com/balena-os/balena-raspberrypi/issues/476 and it seems to have helped 🤞

**Comment by daveconde** [comment]
@thorrak i have fermented a beer since making the baud rate changes above, all spikes and readings getting stuck and requiring a restart seem to be solved

**Comment by lbussy** [comment]
Same as #424 I believe.

**Comment by daveconde** [comment]
Yep looks like the same issue 😁

**Comment by thorrak** [comment]
Yeah - I need to get the fix @lbussy proposed integrated into both the install script for new installations and into its own shell script that existing installs can use to fix their builds. This is one of those weird Fermentrack bugs that isn't exactly a bug with Fermentrack and thus has more hoops to jump through to fix. 😆 

Project for the long weekend, since it doesn't look like I'm going to be able to get out much!

**Comment by daveconde** [comment]
Oh the plus side, not being able to go out at weekends has meant a bit more time to brew 💪

**Comment by lbussy** [comment]
John needs three weekends to brew: One to talk about it, one to get ingredients, one to brew.

**Comment by thorrak** [comment]
> John needs three weekends to brew: One to talk about it, one to get ingredients, one to brew.

Preferably split across several months. :)

**Comment by lbussy** [comment]
Well, yeah, I didn't say "successive." 😄

**Comment by thorrak** [comment]
Closing this as I believe it has since been resolved. There’s a a new Tilt stack coming with https://github.com/thorrak/fermentrack/pull/724 as well, so if this reoccurs after that goes live I want to separate the issue.
