### ISSUE TITLE
Tilt on Buster bluetooth issues?

### ISSUE THREAD

**Issue by KnoAll** [thorrak/fermentrack#414]
I have been doing a lot of experimenting with Fermentrack and my new Tilt, and after a bit of head scratching, I believe I am running into bluetooth issues on Raspbian Buster. I am running the Dec 29th Fermentrack on two different rPi of the same hardware version 3B+. One has Stretch, and the other Buster. With the same setup/config (only one powered at a time) I see good connectivity in Stretch, and in Buster the Tilt stops logging after 5-15m. It appears to not be the hardware, I have switched the OS between the two different rPi and the issue sticks with the Buster OS version.

**Comment by lbussy** [comment]
@thorrak what I did here is lower the UART baud rate based on a convo with Noah.

```
do_aioblescan() {
    # Install aioblescan
    local blerepo device fast safe file
    echo -e "\nInstalling BLEacon support via aioblescan."
    blerepo="https://github.com/brewpi-remix/aioblescan.git"
    file="/usr/bin/btuart"
    fast="\$HCIATTACH \/dev\/serial1 bcm43xx 921600 noflow - \$BDADDR"
    safe="\$HCIATTACH \/dev\/serial1 bcm43xx 460800 noflow - \$BDADDR"
    rm -fr "$HOMEPATH/aioblescan"
    git clone "$blerepo" "$HOMEPATH/aioblescan"
    (cd "$HOMEPATH/aioblescan" || exit; python3 setup.py install)
    rm -fr "$HOMEPATH/aioblescan"
    # Slow down uart speeds on < Pi4
    if [ -f "$file" ]; then
        sed -i "s/$fast/$safe/g" "$file"
    fi
    device=$(hciconfig | grep "hci" | grep "UART" | tr -s ' ' | cut -d":" -f1)
    if [ -n "$device" ]; then
        if grep -vq "Pi 4" /proc/device-tree/model; then
            stty -F /dev/serial1 460800
        fi
    fi
}
```

**Comment by KnoAll** [comment]
Saw this on Stretch overnight. Rebooted and it re-connected to the Tilt.
![image](https://user-images.githubusercontent.com/7632685/79266249-22855880-7e4c-11ea-9464-4c67432f8c51.png)

**Comment by lbussy** [comment]
Sort of hard to see what you mean there.  Do you mean the Tilt stopped responding?  If so, some questions for you since I am seeing something similar in BPR:

1. How far away from the fermenter is your Pi?
2. Are you using a SS fermenter?
3. Can you post the contents of your `/usr/bin/btuart`?
4. What version of Pi?
5. What version of Raspbian?

I believe this is in the Aioblescan, just not sure why yet.  It does not happen often enough on my test system to really be able to catch it.

**Comment by KnoAll** [comment]
Yes sorry, Fermentrack stopped recording Tilt readings. 
1. The fermenter is a stainless conical inside an upright freezer. Originally the BrewPi/Fermentrack was directly on top of the freezer but was not getting any readings from the Tilt. I dangled the Pi/Fermentrack inside the door of the freezer and then started getting signal from the Tilt. So I would say 6" from the top of the conical roughly.
2. Yes!
3. fermentrack@raspberrypi:~ $ ls -al /usr/bin/btuart
-rwxr-xr-x 1 root root 738 Oct 29  2018 /usr/bin/btuart
fermentrack@raspberrypi:~ $
4. 3b+
5. Stretch..
fermentrack@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
fermentrack@raspberrypi:~ $

**Comment by thorrak** [comment]
Hmm. Are you running the latest version of Fermentrack?

**Comment by lbussy** [comment]
Would you `cat /usr/bun/btuart` please?

**Comment by KnoAll** [comment]
fermentrack@raspberrypi:~ $ cat /usr/bin/btuart
#!/bin/sh

HCIATTACH=/usr/bin/hciattach
SERIAL=`cat /proc/device-tree/serial-number | cut -c9-`
B1=`echo $SERIAL | cut -c3-4`
B2=`echo $SERIAL | cut -c5-6`
B3=`echo $SERIAL | cut -c7-8`
BDADDR=`printf b8:27:eb:%02x:%02x:%02x $((0x$B1 ^ 0xaa)) $((0x$B2 ^ 0xaa)) $((0x    $B3 ^ 0xaa))`

uart0="`cat /proc/device-tree/aliases/uart0`"
serial1="`cat /proc/device-tree/aliases/serial1`"

if [ "$uart0" = "$serial1" ] ; then
        uart0_pins="`wc -c /proc/device-tree/soc/gpio@7e200000/uart0_pins/brcm\,    pins | cut -f 1 -d ' '`"
        if [ "$uart0_pins" = "16" ] ; then
                $HCIATTACH /dev/serial1 bcm43xx 3000000 flow - $BDADDR
        else
                $HCIATTACH /dev/serial1 bcm43xx 921600 noflow - $BDADDR
        fi
else
        $HCIATTACH /dev/serial1 bcm43xx 460800 noflow - $BDADDR
fi
fermentrack@raspberrypi:~ $

**Comment by KnoAll** [comment]
and yes, running the latest version of fermentrack from Master

**Comment by lbussy** [comment]
If this happens often enough that you would notice a difference, edit the `usr/bin/btuart` file to change the baud rates all to 115200.  That would be the end of the file:

```
if [ "$uart0" = "$serial1" ] ; then
        uart0_pins="`wc -c /proc/device-tree/soc/gpio@7e200000/uart0_pins/brcm\,pins | cut -f 1 -d ' '`"
        if [ "$uart0_pins" = "16" ] ; then
                $HCIATTACH /dev/serial1 bcm43xx 115200 flow - $BDADDR
        else
                $HCIATTACH /dev/serial1 bcm43xx 115200 noflow - $BDADDR
        fi
else
        $HCIATTACH /dev/serial1 bcm43xx 115200 noflow - $BDADDR
fi
```

Then reboot since I've not bothered to figure out which systend process it is.  See if that helps.

**Comment by KnoAll** [comment]
ok, made the changes and rebooted. waiting to see....

**Comment by KnoAll** [comment]
OK, receiving data, fingers crossed that it is stable!

**Comment by lbussy** [comment]
I've seen it flake out anywhere between a couple of hours and > a day.  Here's a graph showing that:

![Image Alt](https://www.brewpiremix.com/wp-content/uploads/2020/04/Capture.png)

I'd love to find a better way to detect it, but the library is semi-silent on it.  It's one of my most annoying issues right now. :)

**Comment by KnoAll** [comment]
So I have not had a Tilt disconnect since changing the settings. Interestingly, I have also not had a spike in SG either.
![image](https://user-images.githubusercontent.com/7632685/79359436-7731dd80-7ef7-11ea-8a82-96d3a5e8bdcb.png)

**Comment by lbussy** [comment]
That's great news!  It also gives me a place to go to maybe help generate some additional "bad data" to dind an upstream fix overall,

**Comment by KnoAll** [comment]
First of all, thanks to both of you for all your effort and work on Fermentrack. LOVING it!
Secondly, what do you typically use/see for logging interval. I think it is set on 30s logging which seems like quite a bit but I'm used to the original BrewPi which was only every 2m.

I'll keep you updated if anything changes.

**Comment by lbussy** [comment]
I don't maintain Fermentrack - I just happen to be using the same libraries in BrewPi Remix so having a larger sample of people is beneficial to both "sides."

The logging interval impacts space and performance.  If you are not having issues with either then don't sweat it.

**Comment by uSlackr** [comment]
Thanks.
I had this issue so bad I restarted every night.  So I rebuilt the Pi. Can you explain what’s going on and how this helps?


\\Greg

**Comment by lbussy** [comment]
1. I'll script a stand-along fix for folks who don't like to or are not comfortable with editing system files.
2. I'll work with @thorrak to see if he wants to incorporate what will be an upstream fix to him when I get it solved.
3. This is related to the speed at which the Pi communicates with the BLE devices (or vice-versa in this case.)  In a side conversation with the Tilt devs and my own testing, it seems this happens more frequently with Buster (where the speed was increased) and older Pi's (like my Pi 2).  It also shows up more when there's more than one Tilt supposedly.

**Comment by lbussy** [comment]
For 2 above:  @thorrak you can use this if you like:

```
INPUT="/usr/bin/btuart"
SEARCHSTRING="\$HCIATTACH /dev/serial1 bcm43xx"

update() {
    while IFS= read -r line
    do
        if [[ "$line" == *"$SEARCHSTRING"* ]]
        then
            baud=$(echo "$line" | tr -s ' ' | cut -d ' ' -f 4)
            eval sed -i 's/$baud/115200/g' "$INPUT"
        fi
    done < "$INPUT"
    echo "$INPUT updated."
}
```

It will update ALL baud rates in that file (only one would be applicable) to 115200.

For 1 above (a script a few of you can test) you can try this:

```
curl -L uartspeed.brewpiremix.com | sudo bash
```

This runs as root (and will reload and run as root if you skip the sudo) because it needs to restart the Bluetooth daemon.

It might take an hour or so for DNS to update so if you get a `curl: (6) Could not resolve host: uartspeed.brewpiremix.com` error, give it a try after dinner.

**Comment by KnoAll** [comment]
Still not a single disconnect or spike in SG!

**Comment by uSlackr** [comment]
I have  3b and a 3b+.  The 3B had this issue.  I just changed btuart and the Tilt connected on restart.

Thanks

\\Greg

**Comment by thorrak** [comment]
Closing this as I believe it has since been resolved. There’s a a new Tilt stack coming with #724 as well, so if this reoccurs after that goes live I want to separate the issue.
