### ISSUE TITLE
OpperationalError "Database is locked"

### ISSUE THREAD

**Issue by fanoway** [thorrak/fermentrack#415]
This has come up multiple times when trying to delete or mange logs. Some other actions have caused this too. It seems somewhat intermittent

Traceback can be found here:

http://dpaste.com/2ESSF5Q

**Comment by thorrak** [comment]
This is (unfortunately) an environment issue relating to the fact that sqlite databases aren't really designed to have multiple things accessing them at once. 

It would be good to support other databases, but that's going to be a fairly intensive change I fear.
