### ISSUE TITLE
Error setting ports

### ISSUE THREAD

**Issue by Kooza25** [thorrak/fermentrack#418]
I get this error when trying to set ports and sensors for a wifi 8266:

Failed to write the configuration to the controller. If this continues, try resetting the EEPROM on the controller.

i already tried to reset and power cycle

**Comment by thorrak** [comment]
Were you able to get this working?

**Comment by Kooza25** [comment]
Ya I did, I just reset it again and it worked
Il 27 gen 2020, 13:06 +0100, John <notifications@github.com>, ha scritto:
