### ISSUE TITLE
Tilt not displaying

### ISSUE THREAD

**Issue by devJayden** [thorrak/fermentrack#421]
I rebuilt a PI since I thought it was my built but can't get the tilt to display.  HCItools scan shows the tilt address but doesn't have a name (unknown).  In windows using beacon interactor I can see the tilt and it shows the correct UUID for black.  It also works fine in the iOS app. 

Logs show 
INFO:processmgr:Settings: Start delay: 2s, Sleep Interval: 15s, 
INFO:processmgr:New Tilt device found: tilt-

I am running the latest pi OS with the latest fermentrack. 

Seems like the same issue as https://github.com/thorrak/fermentrack/issues/304 but it still exists.

**Comment by devJayden** [comment]
Turns out this was the same as 304.  Dev build fixes this.  It mentioned in 304 it would be merged to master but I don't think it has been.

**Comment by thorrak** [comment]
Correct - I try to delay merges to master until I’m sure there are no residual bugs. I’ll probably end up accelerating a merge given the issues.

**Comment by lbussy** [comment]
>> Correct - I try to delay merges to master until I’m sure there are no residual bugs. I’ll probably end up accelerating a merge given the issues.

Oh that's GOOD!  I'm going to use that the next time I go out for cocktails and forget something. :)

**Comment by devJayden** [comment]
Ahh great!   I almost also playing with the beta Grainfather integration!  

As a side note it looks like the bug with old tilt data still showing when the tilt is off still exists.  

Love the project guys. Let me know if you need any testing etc. 

Jayden
