### ISSUE TITLE
Fermentrack not displaying tilt readings

### ISSUE THREAD

**Issue by fun4stuff** [thorrak/fermentrack#424]
I have fermentrack installed on a pi3b. 

I added my tilt, but i get no readings from it.

**Comment by thorrak** [comment]
Are you up to date with the latest dev/master? Can you post a screenshot of the configuration options for your Tilt?

**Comment by fun4stuff** [comment]
I ended up setting up a tiltbridge on my esp32 and have fermentrack getting tilt readings from that. So I’ll close this now. Thanks for your response.
