### ISSUE TITLE
Lock the version of PyBluez

### ISSUE THREAD

**Issue by thorrak** [thorrak/fermentrack#428]
There have been a number of bugs reported related to Tilt support, where it appeared to break for a subset of users. Best that I can tell, the root cause is recent changes to the PyBluez library (and to the bluez subsystem it sits atop). 

To (hopefully) prevent this in the future, it would be good to lock the version so that upgrades only happen when we want them to. 

This is a reminder to get this done in the next bug fix release.

**Comment by uSlackr** [comment]
Mine indeed is dead. Do I need to downgrade?

\\\\ Greg

________________________________
