### ISSUE TITLE
No Data Logged.

### ISSUE THREAD

**Issue by yakam-doolday** [thorrak/fermentrack#437]
Hi all,
I'm new to this so please forgive me for being ignorant of so many things.
I have been running fermentrack for over a year, with 5 ispindles and 1 ardiuno ESP8266.  Today,  after a year I finalized and ended my beer as web page was taking an age to load due to the shear volume of data. So I thought I would like to save the years data as a CSV.  I go to manage logs, and in there it lists my year long log and the new one i've just started running.  However, on both it says no data logged instead of view full CSV.  The data must still be there because if i load the year long log it shows me the graph, please help I would like to keep the data as a CSV file.  Can someone tell me what i am doing wrong.  Thanks in advance.

**Comment by thorrak** [comment]
This is a bug! Sorry about that - thanks for reporting it.

 I've got a fix pending - should be in dev shortly.
