### ISSUE TITLE
Raspberry Pi Reboot Required to detect Tilt

### ISSUE THREAD

**Issue by matthawley** [thorrak/fermentrack#439]
When I complete a brew, I usually don't shutdown my Raspberry Pi. However, what I've noticed when I do this, is that the next brew doesn't automatically reconnect to my Tilt. I have to restart my Raspberry Pi for it to reconnect and start logging again. This has happened to me twice so far.

**Comment by thorrak** [comment]
Although I can't be certain, I'm guessing this relates to #414 . Going to close this, and track the tweak I'm going to attempt to implement on that issue.
