### ISSUE TITLE
Color in legend for Gravity line isn't dynamic

### ISSUE THREAD

**Issue by thorrak** [thorrak/fermentrack#443]
Per https://www.homebrewtalk.com/forum/threads/tilt-not-communicating-with-fermentrack.677019/#post-8827585 the color of the icon in the legend for "gravity" isn't updated to properly match the color as set in the Django admin

**Comment by Garzlok** [comment]
I don't know if there's more to the Bug, or not.

device_dashboard.html currently reads (line:232):
                                    <i class="fa fa-line-chart" style="color: {{ config.GRAPH_FRIDGE_SET_COLOR }}" id="gravity_legend" onClick="toggle_graph_visibility(this)"></i>

(should change to:)
                                    <i class="fa fa-line-chart" style="color: {{ config.GRAPH_GRAVITY_COLOR }}" id="gravity_legend" onClick="toggle_graph_visibility(this)"></i>

**Comment by Garzlok** [comment]
son of a bish!

`                                     <i class="fa fa-line-chart" style="color: {{ config.GRAPH_FRIDGE_SET_COLOR }}" id="gravity_legend" onClick="toggle_graph_visibility(this)"></i>

                                    <i class="fa fa-line-chart" style="color: {{ config.GRAPH_GRAVITY_COLOR }}" id="gravity_legend" onClick="toggle_graph_visibility(this)"></i>`

**Comment by thorrak** [comment]
Nope, that's all there is to it!
