### ISSUE TITLE
Question: Can you edit a fermentation profile and apply to in progress brew?

### ISSUE THREAD

**Issue by KnoAll** [thorrak/fermentrack#448]
On my first fermentrack brew. I had a guess for my fermentation profile, but my yeast is beating my estimate and I want to begin ramping up temp earlier than thought. I tried to find a way to edit a profile, but cannot see one. Do I have to create a new profile and apply it to the brew instead? 

What is the recommended method? create a profile including just where I am not forward? Or try and get a complete profile and have it start Xtime into it?

**Comment by thorrak** [comment]
You should be able to edit the profile by loading it, but the recommended method would be to just cancel the current profile and restart it part of the way through (using the start X time into profile feature).

**Comment by KnoAll** [comment]
I will do the cancel and re-start for now.
I do see the ability to add a setpoint, but not to edit existing setpoints?

**Comment by KnoAll** [comment]
It seems that the previous points cannot be removed unless the profile is unassigned. then points can be added and deleted. then the profile can be re-applied

**Comment by thorrak** [comment]
Yep, exactly. That's intentional behavior to prevent people from accidentally adding/deleting points from a live profile, and then wondering why their already-fermenting beer starts doing something funky. This is also part of why the "start midway through" function was added.
