### ISSUE TITLE
Upgrades to some pip packages aren't actually upgrading those packages

### ISSUE THREAD

**Issue by thorrak** [thorrak/fermentrack#457]
For some reason, I keep seeing weird issues like the below come through Sentry that would imply that pip didn't actually upgrade Django. This is incredibly troublesome, given that Django returns the appropriate version codes for a fully-upgraded Django, so there isn't a way to easily test for this. 

ImportError: cannot import name 'RemovedInDjango20Warning' from 'django.utils.deprecation' (/home/fermentrack/...

```
ImportError: cannot import name 'RemovedInDjango20Warning' from 'django.utils.deprecation' (/home/fermentrack/venv/lib/python3.7/site-packages/django/utils/deprecation.py)
(1 additional frame(s) were not displayed)
...
  File "django/core/handlers/base.py", line 115, in _get_response
  File "django/core/handlers/base.py", line 113, in _get_response
    view = transaction.atomic(using=db.alias)(view)
  File "django/contrib/auth/decorators.py", line 21, in _wrapped_view
    def _wrapped_view(request, *args, **kwargs):
  File "app/decorators.py", line 37, in _wrapped_view
    path = request.get_full_path()
  File "django/contrib/auth/views.py", line 21, in <module>
    from django.utils.deprecation import (
```

**Comment by uSlackr** [comment]
Let me know if I can test or collect info for this.

**Comment by thorrak** [comment]
Will do - Thank you! The immediate fix for this problem is to run this command:
https://github.com/thorrak/fermentrack-tools/blob/5a9b0730c82dd9de195af68ec199f73e14b69a8b/fix-environment.sh#L148

The thing is that I need to figure out how to detect when/if this needs to be run, and I don't know if that's possible. The file that most frequently seems to be missing is [this one](https://github.com/django/django/blob/master/django/views/templates/technical_500.html) so I can at least test for that, I guess - it's just not ideal. 

My plan for closing this issue is to refactor out [all of these actions](https://github.com/thorrak/fermentrack-tools/blob/5a9b0730c82dd9de195af68ec199f73e14b69a8b/fix-environment.sh#L130-L163) from that tactical script I posted last night to a utility that sits within Fermentrack, and then (hopefully) figure out a plan for triggering that from within Fermentrack

**Comment by thorrak** [comment]
FileNotFoundError/
error[Errno 2] No such file or directory: 

'/home/fermentrack/venv/lib/python3.7/site-packages/django/views/templates/technical_500.html'

**Comment by thorrak** [comment]
I've done about all I can do with this, as it seems to be an environmental thing. Going to close this issue - the `fix-environment.sh` script does everything it can do, but beyond that the only solution is either Docker or a clean reinstall.
