### ISSUE TITLE
Django 3.0 upgrade cannot be completed automatically on Raspbian Stretch

### ISSUE THREAD

**Issue by thorrak** [thorrak/fermentrack#463]
## About the upcoming pull request

In an upcoming PR (#462) I upgrade Fermentrack to Django 3.0 which requires Python 3.7 or later. Unfortunately, on Raspbian Stretch the Python packages that are available end at Python 3.6. To resolve this, users will need to manually install Python 3.7.

## Installing Python 3.7 Semi-Automatically

To assist with installing Fermentrack on Stretch, I've created a script that installs Python 3.7 and rebuilds the venv to use it. This script can be run either in advance of the release of the new version of Fermentrack (in which case the upgrade will work out of the box) or can be run after upgrading. To run the script, SSH into your Raspberry Pi as the `pi` user and run the following command:

`curl -L "https://raw.githubusercontent.com/thorrak/fermentrack-tools/master/non_docker_install/fix-environment.sh" | sudo bash`

This command will (amongst other things) update your environment, install Python 3.7, and upgrade to the latest commit in your selected branch from GitHub. Be aware - If you have customized code in Fermentrack, this command may revert that code, and as such you may need to execute the various pieces separately. 

## Installing Python 3.7 (and otherwise fixing your environment) Manually

If you prefer to fix your environment manually (or are otherwise trained not to pipe things from curl directly to bash - which is smart!) then you will need to replicate the actions that the [fix-environment.sh](https://github.com/thorrak/fermentrack-tools/blob/master/fix-environment.sh) script performs. The best way to do this is to read through the script and follow along manually, but as an overview, the script is doing the following:

1. Install any missing packages that need to be installed with `apt`
2. Check if Python 3.7 is installed and - if it isn't - installing it
3. Delete the virtual environment at `/home/fermentrack/venv`
4. Recreate the virtual environment - and replace the symlinks therein to python/python3 with symlinks to python 3.7
5. Install pyzmq into the venv using the `--no-binary` option (we **do not** want a wheel)
6. Install numpy into the venv using the `--no-binary` option (again - we **do not** want a wheel)
7. Double check that the `fermentrack` user owns everything at `/home/fermentrack`
8. Use `setcap` to allow the venv's python interpreter to properly query bluetooth without being root
9. Switch to the Fermentrack user and activate the virtualenv
10. Upgrade pip within the virtualenv
11. Update everything from GitHub
12. Reinstall all the requirements using `pip`
13. Run the `manage.py` commands `migrate`, `fix_sqlite_for_django_2`, and `collectstatic` (Note - fix_sqlite_for_django_2 will not work/have no impact for installs that have not been upgraded to Django 3)
14. Restart circus & relaunch fermentrack

When the above steps are complete, you should have Python 3.7 installed & available in a venv, with pyzmq & numpy installed from source into that same venv, all under the fermentrack user.

**Comment by thorrak** [comment]
Note - I'm planning on merging the PR on **Friday, June 5th**.  

After this date, any installation of Fermentrack that does not have access to a Python 3.7 interpreter will cease to function.

**Comment by Vetton1521** [comment]
Hi! After using your script to update, I'm not able anymore to enter on Fermentrack (I get a 502 Bad Gateway - nginx 1.10.3).  When using the script I see some fail messages. Any ideas on how to fix it? Thanks!

_**::: Creating virtualenv directory...
rm: cannot remove '/root/venv/': Permission denied
sudo: python3.7: command not found
bash: /home/fermentrack/venv/bin/pip: /home/fermentrack/venv/bin/python3: bad interpreter: No such file or directory
bash: /home/fermentrack/venv/bin/python3: No such file or directory
bash: /home/fermentrack/venv/bin/python3: No such file or directory

::: Making sure everything is owned by fermentrack

::: Enabling python to query bluetooth without being root
Failed to set capabilities on file `' (No such file or directory)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
::: Switching to the Fermentrack user and doing all the other bits...
Stopping Circus
bash: /home/fermentrack/venv/bin/circusctl: /home/fermentrack/venv/bin/python3: bad interpreter: No such file or directory
Upgrading pip
bash: /home/fermentrack/venv/bin/pip3: /home/fermentrack/venv/bin/python3: bad interpreter: No such file or directory
Fetching, resetting, and pulling from git...
Fetching origin
HEAD is now at b8fd21a Add warning about upcoming Python 3.7 requirement
Already up-to-date.
Re-installing Python packages from requirements.txt via pip3
bash: /home/fermentrack/venv/bin/pip3: /home/fermentrack/venv/bin/python3: bad interpreter: No such file or directory
Running manage.py migrate/fix_sqlite_for_django_2/collectstatic...
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    import django
ImportError: No module named 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 17, in <module>
    "Couldn't import Django. Are you sure it's installed and "
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    import django
ImportError: No module named 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 17, in <module>
    "Couldn't import Django. Are you sure it's installed and "
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    import django
ImportError: No module named 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 17, in <module>
    "Couldn't import Django. Are you sure it's installed and "
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Quitting Circus
bash: /home/fermentrack/venv/bin/circusctl: /home/fermentrack/venv/bin/python3: bad interpreter: No such file or directory
Calling updateCronCircus to restart Circus...
Starting Fermentrack supervisor: circusd: utils/updateCronCircus.sh: /home/fermentrack/venv/bin/circusd: /home/fermentrack/venv/bin/python3: bad interpreter: No such file or directory
failed, please see logfile.**_

**Comment by thorrak** [comment]
It appears that Python 3.7 failed to install, and as a result your virtualenv didn't get created. Unfortunately, that doesn't look like a full log, so it's difficult to say what exactly happened. Is your Fermentrack installation on the `fermentrack` user? If so, my first recommendation would be to re-attempt the `fix-environment.sh` script.

What version of Raspbian are you running?

**Comment by Vetton1521** [comment]
Hi! Indeed, I guess it was that. I manually installed just Python 3.7, then I run your script and now everything's fine. 

Thanks for the amazing work!
