### ISSUE TITLE
Fermentrack ESP8266 Temp Setting Push

### ISSUE THREAD

**Issue by jnr-nat** [thorrak/fermentrack#464]
I know that there now a Data Push setup that enables the data logged into Fermentrack from an iSpindel to be sent to Brewfather.

But is there a way that the Temp reading from a ESP8266 BrewLessPi controlled by Fermentrack gets sent to Brewfather also?

Cheers

**Comment by rthopper** [comment]
Piggy backing on this one after posting a similar question on homebrewtalk.  I have several ESP8266's (setup via fermentrack) that control my various fermentation chambers.  It would be great to push this temp data (Beer temp, beer setting, fridge temp, fridge setting, room temp) into brewfather for the correspond batch.  Thanks much!

**Comment by mp-se** [comment]
The API for brewfather supports 3 temp values; gravity, beer, room values. Currently it's only the temp for the gravity is used. If the gravity sensor is attached it should be possible to extract the beer/room values from the esp8266 as well. But I guess that you want the option to send temp values without having a gravity sensor?

**Comment by jnr-nat** [comment]
> The API for brewfather supports 3 temp values; gravity, beer, room values. Currently it's only the temp for the gravity is used. If the gravity sensor is attached it should be possible to extract the beer/room values from the esp8266 as well. But I guess that you want the option to send temp values without having a gravity sensor?

Yeah basically I'm just looking at sending the Temp Data standalone from Fermentrack to Brewfather. I have my iSpindel going direct to Brewfather. But getting all other temp controllers (Keezer and the like) would be handy while away

**Comment by mp-se** [comment]
Then I understand, I will have a look at it. I have basically the same setup at home. Fermentation chamber, keezer and iSpindels. I just switched to brewfather so I have the same need.

**Comment by rthopper** [comment]
Yes same for me.

I just want to store the temperature chart of the beer along with all of
the other vitals captured in brewfather.  No ispindles or gravity sensors
for me, just the ESP8266.

Thanks a bunch.

Tim

**Comment by mp-se** [comment]
@thorrak can you assign this to me and I will start to work on it.

**Comment by thorrak** [comment]
Sure thing! Thinking about this, I think this would be pretty simple to adapt from the implementation of `GenericPushTarget`. The only real "catch" that I see is that you would need to check each of the gravity sensors that were selected to make sure that if a gravity sensor that was attached to a BrewPi was selected to push AND the BrewPi was selected to push, you wouldn't end up pushing the data twice.

**Comment by mp-se** [comment]
I have been looking at the code and the default behaviour is to push the gravity sensor data + brewpi sensors if one is attached. 

So I only need an option for the user to push brewi data that has no gravity sensor attached. My approach is to add an option where the user can choose between brewpi or gravity as the source device. It's an quite easy extension of the current code.

**Comment by x2harry** [comment]
This would be great, I have just started with Brewfather.
I brew under pressure, will there be a pressure sensor added to Fermentrack like in brewpiless?
Cheers and thanks for all your good work.

**Comment by mp-se** [comment]
@thorrak  I think I found an error in the brewpi script. I was having a problem to get any temp values over to brewfather. The push code uses "getDashInfo" to get the current temp values but the prevTempJson variable is not updated, if beer logging is not active.... Im wondering if I would break any logic if I update the brewpi script to update the prevTempJson variable even tough logging is off... I guess this is affecting all the external push options.....

**Comment by mp-se** [comment]
> This would be great, I have just started with Brewfather.
> I brew under pressure, will there be a pressure sensor added to Fermentrack like in brewpiless?
> Cheers and thanks for all your good work.

Since this is not really related to this change, it would be best to post this as a new feature request so it won't be missed.

**Comment by blazem** [comment]
Is the generic push target option compatible with influxdb? I would like to log the sensors into a influxdb database and have that then graphed into grafana as a way to see the ferment activity in home assistant.

**Comment by uSlackr** [comment]
It could work with any db but would need a web-based interface to sit in-between to accept the data and write it to the db. Alternately, the data is logged locally in csv and could be imported to your db.  Check out the   /data folder

\\Greg

**Comment by thorrak** [comment]
This change is currently sitting in a the `newfeatures` branch of Fermentrack. I'm debating with myself as to whether or not to try to get this into `dev` prior to the release of the Django 3.0 updates to master. At the moment, I'm leaning towards not doing so, which means that this will get released to `dev` in slightly under two weeks. (I'm merging the Django 3.0 changes on Friday, June 5th)

**Comment by thorrak** [comment]
This is now sitting in `dev`

**Comment by jnr-nat** [comment]
I don't run the rev version, so I'll just wait till it is released in the Master.

Thanks for the effort guys making these changes

**Comment by thorrak** [comment]
This is now in Master. Closing this issue.
