### ISSUE TITLE
Impossible to conect devices (DS18B20) with ARDUINO UNO and RPI 3B

### ISSUE THREAD

**Issue by pakopiwi** [thorrak/fermentrack#469]
Hi everyone! And sorry for my english.
I have a great problem with my Fermentation Chamber`s proyect and I don't know the next step to fix it...
My equipment:
   - Raspberry Pi Model 3B
   - Arduino UNO compatible

I have assembled everything according to the plans (4,7 KOhms resistance, relays, etc, etc) and I am unable to get Fermentrack to detect the temperature probes (brewpi either). This temperature probes does work with the OneWire example in arduino separately... I have tried diferents flashes of arduino, reinstalled several times Fermentrack, Brewpi Remix, etc etc...

` May 13 2020 16:49:01   Connection type Serial selected. Opening serial port.
 May 13 2020 16:49:01   Connected via serial to port /dev/ttyACM0
 May 13 2020 16:49:01   Notification: Script started, with no active beer being logged
 May 13 2020 16:49:11   Checking software version on controller... 
 May 13 2020 16:49:11   Found BrewPi v0.2.12 build 8d36524, running on an Arduino Uno with a revC shield on port /dev/ttyACM0

Controller Logs: 
May 13 2020 16:49:11   BrewPi version received was 0.2.12 which this script supports in 'legacy' branch mode.
 May 13 2020 16:49:11   Bound to TCP socket on port 2549, interface localhost 
 May 13 2020 16:49:12   Installed devices received: []
 May 13 2020 16:49:12   Available devices received: [{"i": -1, "t": 0, "c": 1, "b": 0, "f": 0, "h": 1, "d": 0, "p": 2, "x": 1}, {"i": -1, "t": 0, "c": 1, "b": 0, "f": 0, "h": 1, "d": 0, "p": 5, "x": 1}, {"i": -1, "t": 0, "c": 1, "b": 0, "f": 0, "h": 1, "d": 0, "p": 6, "x": 1}, {"i": -1, "t": 0, "c": 1, "b": 0, "f": 0, "h": 1, "d": 0, "p": 19, "x": 1}]
 May 13 2020 16:50:31   Installed devices received: []
 May 13 2020 16:50:31   Available devices received: [{"i": -1, "t": 0, "c": 1, "b": 0, "f": 0, "h": 1, "d": 0, "p": 2, "x": 1}, {"i": -1, "t": 0, "c": 1, "b": 0, "f": 0, "h": 1, "d": 0, "p": 5, "x": 1}, {"i": -1, "t": 0, "c": 1, "b": 0, "f": 0, "h": 1, "d": 0, "p": 6, "x": 1}, {"i": -1, "t": 0, "c": 1, "b": 0, "f": 0, "h": 1, "d": 0, "p": 19, "x": 1}]
 May 13 2020 16:56:29   Installed devices received: []
 May 13 2020 16:56:29   Available devices received: [{"i": -1, "t": 0, "c": 1, "b": 0, "f": 0, "h": 1, "d": 0, "p": 2, "x": 1}, {"i": -1, "t": 0, "c": 1, "b": 0, "f": 0, "h": 1, "d": 0, "p": 5, "x": 1}, {"i": -1, "t": 0, "c": 1, "b": 0, "f": 0, "h": 1, "d": 0, "p": 6, "x": 1}, {"i": -1, "t": 0, "c": 1, "b": 0, "f": 0, "h": 1, "d": 0, "p": 19, "x": 1}]
 May 13 2020 17:03:51   Installed devices received: []
 May 13 2020 17:03:51   Available devices received: [{"i": -1, "t": 0, "c": 1, "b": 0, "f": 0, "h": 1, "d": 0, "p": 2, "x": 1}, {"i": -1, "t": 0, "c": 1, "b": 0, "f": 0, "h": 1, "d": 0, "p": 5, "x": 1}, {"i": -1, "t": 0, "c": 1, "b": 0, "f": 0, "h": 1, "d": 0, "p": 6, "x": 1}, {"i": -1, "t": 0, "c": 1, "b": 0, "f": 0, "h": 1, "d": 0, "p": 19, "x": 1}]
 May 13 2020 17:23:42   Installed devices received: []
 May 13 2020 17:23:42   Available devices received: [{"i": -1, "t": 0, "c": 1, "b": 0, "f": 0, "h": 1, "d": 0, "p": 2, "x": 1}, {"i": -1, "t": 0, "c": 1, "b": 0, "f": 0, "h": 1, "d": 0, "p": 5, "x": 1}, {"i": -1, "t": 0, "c": 1, "b": 0, "f": 0, "h": 1, "d": 0, "p": 6, "x": 1}, {"i": -1, "t": 0, "c": 1, "b": 0, "f": 0, "h": 1, "d": 0, "p": 19, "x": 1}]`

/log/fermentrack-stderr.log:
`2020-05-10 11:28:11 [521] [INFO] Application is <django.core.handlers.wsgi.WSGIHandler object at 0x74a742f0>
INFO:chaussette:Application is <django.core.handlers.wsgi.WSGIHandler object at 0x74a742f0>
2020-05-10 11:28:11 [521] [INFO] Serving on fd://10
INFO:chaussette:Serving on fd://10
2020-05-10 11:28:11 [521] [INFO] Using <class 'chaussette.backend._wsgiref.ChaussetteServer'> as a backend
INFO:chaussette:Using <class 'chaussette.backend._wsgiref.ChaussetteServer'> as a backend
2020-05-10 11:28:11 [522] [INFO] Serving on fd://10
INFO:chaussette:Serving on fd://10
2020-05-10 11:28:11 [522] [INFO] Using <class 'chaussette.backend._wsgiref.ChaussetteServer'> as a backend
INFO:chaussette:Using <class 'chaussette.backend._wsgiref.ChaussetteServer'> as a backend
2020-05-10 12:17:16 [514] [INFO] Application is <django.core.handlers.wsgi.WSGIHandler object at 0x74a08310>
INFO:chaussette:Application is <django.core.handlers.wsgi.WSGIHandler object at 0x74a08310>
2020-05-10 12:17:16 [513] [INFO] Application is <django.core.handlers.wsgi.WSGIHandler object at 0x74a4d2f0>
INFO:chaussette:Application is <django.core.handlers.wsgi.WSGIHandler object at 0x74a4d2f0>
2020-05-10 12:17:16 [513] [INFO] Serving on fd://10
INFO:chaussette:Serving on fd://10
2020-05-10 12:17:16 [513] [INFO] Using <class 'chaussette.backend._wsgiref.ChaussetteServer'> as a backend
INFO:chaussette:Using <class 'chaussette.backend._wsgiref.ChaussetteServer'> as a backend
2020-05-10 12:17:16 [514] [INFO] Serving on fd://10
INFO:chaussette:Serving on fd://10
2020-05-10 12:17:16 [514] [INFO] Using <class 'chaussette.backend._wsgiref.ChaussetteServer'> as a backend
INFO:chaussette:Using <class 'chaussette.backend._wsgiref.ChaussetteServer'> as a backend
2020-05-10 12:38:10 [566] [INFO] Application is <django.core.handlers.wsgi.WSGIHandler object at 0x74a93310>
INFO:chaussette:Application is <django.core.handlers.wsgi.WSGIHandler object at 0x74a93310>
2020-05-10 12:38:10 [567] [INFO] Application is <django.core.handlers.wsgi.WSGIHandler object at 0x74a03310>
INFO:chaussette:Application is <django.core.handlers.wsgi.WSGIHandler object at 0x74a03310>
2020-05-10 12:38:10 [567] [INFO] Serving on fd://10
2020-05-10 12:38:10 [566] [INFO] Serving on fd://10
INFO:chaussette:Serving on fd://10
2020-05-10 12:38:10 [566] [INFO] Using <class 'chaussette.backend._wsgiref.ChaussetteServer'> as a backend
INFO:chaussette:Using <class 'chaussette.backend._wsgiref.ChaussetteServer'> as a backend
INFO:chaussette:Serving on fd://10
2020-05-10 12:38:10 [567] [INFO] Using <class 'chaussette.backend._wsgiref.ChaussetteServer'> as a backend
INFO:chaussette:Using <class 'chaussette.backend._wsgiref.ChaussetteServer'> as a backend
2020-05-13 16:23:10 [509] [INFO] Application is <django.core.handlers.wsgi.WSGIHandler object at 0x74a5f2f0>
INFO:chaussette:Application is <django.core.handlers.wsgi.WSGIHandler object at 0x74a5f2f0>
2020-05-13 16:23:10 [509] [INFO] Serving on fd://10
INFO:chaussette:Serving on fd://10
2020-05-13 16:23:10 [509] [INFO] Using <class 'chaussette.backend._wsgiref.ChaussetteServer'> as a backend
INFO:chaussette:Using <class 'chaussette.backend._wsgiref.ChaussetteServer'> as a backend
2020-05-13 16:23:10 [513] [INFO] Application is <django.core.handlers.wsgi.WSGIHandler object at 0x74ac22d0>
INFO:chaussette:Application is <django.core.handlers.wsgi.WSGIHandler object at 0x74ac22d0>
2020-05-13 16:23:10 [513] [INFO] Serving on fd://10
INFO:chaussette:Serving on fd://10
2020-05-13 16:23:10 [513] [INFO] Using <class 'chaussette.backend._wsgiref.ChaussetteServer'> as a backend
INFO:chaussette:Using <class 'chaussette.backend._wsgiref.ChaussetteServer'> as a backend
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
2020-05-13 16:35:20 [1405] [INFO] Application is <django.core.handlers.wsgi.WSGIHandler object at 0x74a3f310>
INFO:chaussette:Application is <django.core.handlers.wsgi.WSGIHandler object at 0x74a3f310>
2020-05-13 16:35:20 [1405] [INFO] Serving on fd://10
INFO:chaussette:Serving on fd://10
2020-05-13 16:35:20 [1405] [INFO] Using <class 'chaussette.backend._wsgiref.ChaussetteServer'> as a backend
INFO:chaussette:Using <class 'chaussette.backend._wsgiref.ChaussetteServer'> as a backend
2020-05-13 16:35:20 [1404] [INFO] Application is <django.core.handlers.wsgi.WSGIHandler object at 0x74a1d2f0>
INFO:chaussette:Application is <django.core.handlers.wsgi.WSGIHandler object at 0x74a1d2f0>
2020-05-13 16:35:20 [1404] [INFO] Serving on fd://10
INFO:chaussette:Serving on fd://10
2020-05-13 16:35:20 [1404] [INFO] Using <class 'chaussette.backend._wsgiref.ChaussetteServer'> as a backend
INFO:chaussette:Using <class 'chaussette.backend._wsgiref.ChaussetteServer'> as a backend
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
2020-05-13 16:35:54 [1475] [INFO] Application is <django.core.handlers.wsgi.WSGIHandler object at 0x74a99310>
INFO:chaussette:Application is <django.core.handlers.wsgi.WSGIHandler object at 0x74a99310>
2020-05-13 16:35:54 [1475] [INFO] Serving on fd://10
INFO:chaussette:Serving on fd://10
2020-05-13 16:35:54 [1475] [INFO] Using <class 'chaussette.backend._wsgiref.ChaussetteServer'> as a backend
INFO:chaussette:Using <class 'chaussette.backend._wsgiref.ChaussetteServer'> as a backend
2020-05-13 16:35:54 [1474] [INFO] Application is <django.core.handlers.wsgi.WSGIHandler object at 0x74a682d0>
INFO:chaussette:Application is <django.core.handlers.wsgi.WSGIHandler object at 0x74a682d0>
2020-05-13 16:35:54 [1474] [INFO] Serving on fd://10
INFO:chaussette:Serving on fd://10
2020-05-13 16:35:54 [1474] [INFO] Using <class 'chaussette.backend._wsgiref.ChaussetteServer'> as a backend
INFO:chaussette:Using <class 'chaussette.backend._wsgiref.ChaussetteServer'> as a backend
0.0.0.0 - - [13/May/2020 16:39:31] "GET /api/log/text/upgrade/stderr/ HTTP/1.0" 200 9414
0.0.0.0 - - [13/May/2020 16:40:28] "POST /devices/guided/ HTTP/1.0" 302 0
0.0.0.0 - - [13/May/2020 16:40:38] "GET /devices/guided/serial/autodetect/Arduino/ HTTP/1.0" 200 5590
0.0.0.0 - - [13/May/2020 16:48:26] "POST /devices/guided/serial/autodetect/Arduino/ HTTP/1.0" 200 6027
0.0.0.0 - - [13/May/2020 16:48:34] "POST /devices/guided/serial/autodetect/Arduino/ HTTP/1.0" 200 5924
0.0.0.0 - - [13/May/2020 16:48:39] "POST /devices/guided/serial/autodetect/Arduino/ HTTP/1.0" 200 11416
0.0.0.0 - - [13/May/2020 16:48:50] "POST /devices/guided/serial/autodetect/Arduino/ HTTP/1.0" 302 0
0.0.0.0 - - [13/May/2020 16:48:52] "GET /api/lcd/ HTTP/1.0" 200 629
0.0.0.0 - - [13/May/2020 16:48:57] "GET /api/lcd/ HTTP/1.0" 200 629
0.0.0.0 - - [13/May/2020 16:49:02] "GET /api/lcd/ HTTP/1.0" 200 629
0.0.0.0 - - [13/May/2020 16:49:07] "GET /api/lcd/ HTTP/1.0" 200 629
0.0.0.0 - - [13/May/2020 16:49:12] "GET /api/lcd/ HTTP/1.0" 200 622
0.0.0.0 - - [13/May/2020 16:49:21] "GET /devices/8/dashboard/ HTTP/1.0" 200 21733
0.0.0.0 - - [13/May/2020 16:49:22] "GET /api/panel/8/ HTTP/1.0" 200 187
0.0.0.0 - - [13/May/2020 16:50:29] "GET /devices/8/sensors/refresh/ HTTP/1.0" 302 0
0.0.0.0 - - [13/May/2020 16:50:32] "GET /devices/8/sensors/ HTTP/1.0" 200 23411
0.0.0.0 - - [13/May/2020 16:50:43] "GET /api/lcd/8/ HTTP/1.0" 200 377
0.0.0.0 - - [13/May/2020 16:50:48] "GET /devices/8/manage/ HTTP/1.0" 200 19071
0.0.0.0 - - [13/May/2020 16:52:47] "GET /site/help/ HTTP/1.0" 200 6900
0.0.0.0 - - [13/May/2020 16:54:51] "GET /api/log/text/fermentrack/stderr/ HTTP/1.0" 200 7679
Internal Server Error: /api/log/text/ispindel/stderr/
ERROR:django.request:Internal Server Error: /api/log/text/ispindel/stderr/`

/log/fermentrack-processmgr.log:
`INFO:processmgr:Settings: Start delay: 2s, Sleep Interval: 15s, 
INFO:processmgr:New BrewPi device found: dev-temp1
INFO:processmgr:Settings: Start delay: 2s, Sleep Interval: 15s, 
INFO:processmgr:New BrewPi device found: dev-temp1
INFO:processmgr:Settings: Start delay: 2s, Sleep Interval: 15s, 
INFO:processmgr:New BrewPi device found: dev-1
INFO:processmgr:Settings: Start delay: 2s, Sleep Interval: 15s, 
INFO:processmgr:New BrewPi device found: dev-1
INFO:processmgr:Device: dev-1 should be stopped and removed, stopped
INFO:processmgr:New BrewPi device found: dev-1
INFO:processmgr:Device: dev-1 should be stopped and removed, stopped
INFO:processmgr:New BrewPi device found: dev-2
INFO:processmgr:Settings: Start delay: 2s, Sleep Interval: 15s, 
INFO:processmgr:New BrewPi device found: dev-2
INFO:processmgr:Device: dev-2 should be stopped and removed, stopped
INFO:processmgr:New BrewPi device found: dev-3
INFO:processmgr:Settings: Start delay: 2s, Sleep Interval: 15s, 
INFO:processmgr:New BrewPi device found: dev-3
INFO:processmgr:Settings: Start delay: 2s, Sleep Interval: 15s, 
INFO:processmgr:New BrewPi device found: dev-3
INFO:processmgr:Device: dev-3 should be stopped and removed, stopped
INFO:processmgr:New BrewPi device found: dev-4
INFO:processmgr:Device: dev-4 should be stopped and removed, stopped
INFO:processmgr:New BrewPi device found: dev-4
INFO:processmgr:Device: dev-4 should be stopped and removed, stopped
INFO:processmgr:New BrewPi device found: dev-5
INFO:processmgr:Settings: Start delay: 2s, Sleep Interval: 15s, 
INFO:processmgr:New BrewPi device found: dev-5
INFO:processmgr:Device: dev-5 should be stopped and removed, stopped
INFO:processmgr:New BrewPi device found: dev-6
INFO:processmgr:Device: dev-6 should be stopped and removed, stopped
INFO:processmgr:New BrewPi device found: dev-6
INFO:processmgr:New BrewPi device found: dev-7
INFO:processmgr:Settings: Start delay: 2s, Sleep Interval: 15s, 
INFO:processmgr:New BrewPi device found: dev-6
INFO:processmgr:New BrewPi device found: dev-7
INFO:processmgr:Settings: Start delay: 2s, Sleep Interval: 15s, 
INFO:processmgr:New BrewPi device found: dev-6
INFO:processmgr:New BrewPi device found: dev-7
ERROR:processmgr:Could not spawn process: dev-7
INFO:processmgr:New BrewPi device found: dev-7
INFO:processmgr:Settings: Start delay: 2s, Sleep Interval: 15s, 
INFO:processmgr:New BrewPi device found: dev-6
INFO:processmgr:New BrewPi device found: dev-7
ERROR:processmgr:Could not spawn process: dev-7
INFO:processmgr:New BrewPi device found: dev-7
INFO:processmgr:Device: dev-6 should be stopped and removed, stopped
INFO:processmgr:Device: dev-7 should be stopped and removed, stopped
INFO:processmgr:Settings: Start delay: 2s, Sleep Interval: 15s, 
INFO:processmgr:Settings: Start delay: 2s, Sleep Interval: 15s, 
INFO:processmgr:New BrewPi device found: dev-8`

/log/ispindel_raw_output.log:
`Error opening /home/fermentrack/fermentrack/log/ispindel_raw_output.log logfile: [Errno 2] No such file or directory: '/home/fermentrack/fermentrack/log/ispindel_raw_output.log'`

/log/upgrade.log:
`::: Re-installing Python packages from requirements.txt
::: Waiting 1 second for Fermentrack to send updates if triggered from the web...
::: Stopping circus...
::: Updating pip3...
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already up-to-date: pip in /home/fermentrack/venv/lib/python3.7/site-packages (20.1)
Could not build wheels for pip, since package 'wheel' is not installed.
::: Updating requirements via pip3...
::: Running manage.py migrate...
::: Running manage.py collectstatic...
::: Relaunching circus...
::: Complete!
ngo<3.1,>=3.0.5 in /home/fermentrack/venv/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (3.0.6)
Requirement already up-to-date: configobj in /home/fermentrack/venv/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (5.0.6)
Requirement already up-to-date: pytz in /home/fermentrack/venv/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (2020.1)
Requirement already up-to-date: sentry-sdk in /home/fermentrack/venv/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (0.14.3)
Requirement already up-to-date: django-constance[database] in /home/fermentrack/venv/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (2.6.0)
Requirement already up-to-date: GitPython in /home/fermentrack/venv/lib/python3.7/site-packages (from -r requirements.txt (line 7)) (3.1.2)
Requirement already up-to-date: zeroconf in /home/fermentrack/venv/lib/python3.7/site-packages (from -r requirements.txt (line 8)) (0.26.1)
Requirement already up-to-date: circus<0.17.0,>=0.16.0 in /home/fermentrack/venv/lib/python3.7/site-packages (from -r requirements.txt (line 9)) (0.16.1)
Requirement already up-to-date: chaussette in /home/fermentrack/venv/lib/python3.7/site-packages (from -r requirements.txt (line 11)) (1.3.0)
Requirement already up-to-date: huey>=2.0 in /home/fermentrack/venv/lib/python3.7/site-packages (from -r requirements.txt (line 12)) (2.2.0)
Requirement already up-to-date: pid in /home/fermentrack/venv/lib/python3.7/site-packages (from -r requirements.txt (line 13)) (3.0.3)
Requirement already up-to-date: pyserial in /home/fermentrack/venv/lib/python3.7/site-packages (from -r requirements.txt (line 14)) (3.4)
Requirement already up-to-date: pyudev in /home/fermentrack/venv/lib/python3.7/site-packages (from -r requirements.txt (line 16)) (0.22.0)
Requirement already up-to-date: requests in /home/fermentrack/venv/lib/python3.7/site-packages (from -r requirements.txt (line 17)) (2.23.0)
Requirement already up-to-date: esptool in /home/fermentrack/venv/lib/python3.7/site-packages (from -r requirements.txt (line 19)) (2.8)
Requirement already up-to-date: packaging~=17.1 in /home/fermentrack/venv/lib/python3.7/site-packages (from -r requirements.txt (line 20)) (17.1)
Requirement already up-to-date: redis==3.4.1 in /home/fermentrack/venv/lib/python3.7/site-packages (from -r requirements.txt (line 23)) (3.4.1)
Requirement already up-to-date: PyBluez==0.23 in /home/fermentrack/venv/lib/python3.7/site-packages (from -r requirements.txt (line 24)) (0.23)
Requirement already up-to-date: aioblescan==0.2.6 in /home/fermentrack/venv/lib/python3.7/site-packages (from -r requirements.txt (line 25)) (0.2.6)
Requirement already satisfied, skipping upgrade: sqlparse>=0.2.2 in /home/fermentrack/venv/lib/python3.7/site-packages (from Django<3.1,>=3.0.5->-r requirements.txt (line 1)) (0.3.1)
Requirement already satisfied, skipping upgrade: asgiref~=3.2 in /home/fermentrack/venv/lib/python3.7/site-packages (from Django<3.1,>=3.0.5->-r requirements.txt (line 1)) (3.2.7)
Requirement already satisfied, skipping upgrade: six in /home/fermentrack/venv/lib/python3.7/site-packages (from configobj->-r requirements.txt (line 2)) (1.14.0)
Requirement already satisfied, skipping upgrade: urllib3>=1.10.0 in /home/fermentrack/venv/lib/python3.7/site-packages (from sentry-sdk->-r requirements.txt (line 5)) (1.25.9)
Requirement already satisfied, skipping upgrade: certifi in /home/fermentrack/venv/lib/python3.7/site-packages (from sentry-sdk->-r requirements.txt (line 5)) (2020.4.5.1)
Requirement already satisfied, skipping upgrade: django-picklefield; extra == "database" in /home/fermentrack/venv/lib/python3.7/site-packages (from django-constance[database]->-r requirements.txt (line 6)) (2.1.1)
Requirement already satisfied, skipping upgrade: gitdb<5,>=4.0.1 in /home/fermentrack/venv/lib/python3.7/site-packages (from GitPython->-r requirements.txt (line 7)) (4.0.5)
Requirement already satisfied, skipping upgrade: ifaddr in /home/fermentrack/venv/lib/python3.7/site-packages (from zeroconf->-r requirements.txt (line 8)) (0.1.6)
Requirement already satisfied, skipping upgrade: psutil in /home/fermentrack/venv/lib/python3.7/site-packages (from circus<0.17.0,>=0.16.0->-r requirements.txt (line 9)) (5.7.0)
Requirement already satisfied, skipping upgrade: tornado<5.0,>=3.0 in /home/fermentrack/venv/lib/python3.7/site-packages (from circus<0.17.0,>=0.16.0->-r requirements.txt (line 9)) (4.5.3)
Requirement already satisfied, skipping upgrade: pyzmq>=17.0 in /home/fermentrack/venv/lib/python3.7/site-packages (from circus<0.17.0,>=0.16.0->-r requirements.txt (line 9)) (19.0.1)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in /home/fermentrack/venv/lib/python3.7/site-packages (from requests->-r requirements.txt (line 17)) (2.9)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in /home/fermentrack/venv/lib/python3.7/site-packages (from requests->-r requirements.txt (line 17)) (3.0.4)
Requirement already satisfied, skipping upgrade: pyaes in /home/fermentrack/venv/lib/python3.7/site-packages (from esptool->-r requirements.txt (line 19)) (1.6.1)
Requirement already satisfied, skipping upgrade: ecdsa in /home/fermentrack/venv/lib/python3.7/site-packages (from esptool->-r requirements.txt (line 19)) (0.15)
Requirement already satisfied, skipping upgrade: pyparsing>=2.0.2 in /home/fermentrack/venv/lib/python3.7/site-packages (from packaging~=17.1->-r requirements.txt (line 20)) (2.4.7)
Requirement already satisfied, skipping upgrade: smmap<4,>=3.0.1 in /home/fermentrack/venv/lib/python3.7/site-packages (from gitdb<5,>=4.0.1->GitPython->-r requirements.txt (line 7)) (3.0.4)
Could not build wheels for Django, since package 'wheel' is not installed.
Could not build wheels for configobj, since package 'wheel' is not installed.
Could not build wheels for pytz, since package 'wheel' is not installed.
Could not build wheels for sentry-sdk, since package 'wheel' is not installed.
Could not build wheels for django-constance, since package 'wheel' is not installed.
Could not build wheels for GitPython, since package 'wheel' is not installed.
Could not build wheels for zeroconf, since package 'wheel' is not installed.
Could not build wheels for circus, since package 'wheel' is not installed.
Could not build wheels for chaussette, since package 'wheel' is not installed.
Could not build wheels for huey, since package 'wheel' is not installed.
Could not build wheels for pid, since package 'wheel' is not installed.
Could not build wheels for pyserial, since package 'wheel' is not installed.
Could not build wheels for pyudev, since package 'wheel' is not installed.
Could not build wheels for requests, since package 'wheel' is not installed.
Could not build wheels for esptool, since package 'wheel' is not installed.
Could not build wheels for packaging, since package 'wheel' is not installed.
Could not build wheels for redis, since package 'wheel' is not installed.
Could not build wheels for PyBluez, since package 'wheel' is not installed.
Could not build wheels for aioblescan, since package 'wheel' is not installed.
Could not build wheels for sqlparse, since package 'wheel' is not installed.
Could not build wheels for asgiref, since package 'wheel' is not installed.
Could not build wheels for six, since package 'wheel' is not installed.
Could not build wheels for urllib3, since package 'wheel' is not installed.
Could not build wheels for certifi, since package 'wheel' is not installed.
Could not build wheels for django-picklefield, since package 'wheel' is not installed.
Could not build wheels for gitdb, since package 'wheel' is not installed.
Could not build wheels for ifaddr, since package 'wheel' is not installed.
Could not build wheels for psutil, since package 'wheel' is not installed.
Could not build wheels for tornado, since package 'wheel' is not installed.
Could not build wheels for pyzmq, since package 'wheel' is not installed.
Could not build wheels for idna, since package 'wheel' is not installed.
Could not build wheels for chardet, since package 'wheel' is not installed.
Could not build wheels for pyaes, since package 'wheel' is not installed.
Could not build wheels for ecdsa, since package 'wheel' is not installed.
Could not build wheels for pyparsing, since package 'wheel' is not installed.
Could not build wheels for smmap, since package 'wheel' is not installed.
Operations to perform:
  Apply all migrations: admin, app, auth, contenttypes, database, external_push, firmware_flash, gravity, sessions
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
ok
ok`

Sorry for so much information and thank you very much for attention.
![Captura](https://user-images.githubusercontent.com/65304246/81845132-699c6180-9550-11ea-8447-ccfba79e5a60.JPG)
![Captura2](https://user-images.githubusercontent.com/65304246/81845215-8fc20180-9550-11ea-9eaa-f8242616f7c8.JPG)

**Comment by thorrak** [comment]
The issue is with your controller, not with Fermentrack. For issues with the BrewPi remix firmware, you'll need to reach out to the author [here](https://github.com/brewpi-remix/brewpi-firmware-rmx).

That said, have you checked to see if your temperature sensors are running in parasitic mode? There should be a script that will help do that out there somewhere - unfortunately I don't have a link to it to provide, however.

**Comment by pakopiwi** [comment]
I am using Fermentrack. I have only talked about brewpi to add more data to people you know. My temperature probes are conected in normal mode, not parasitic... I dont know what to do...

**Comment by thorrak** [comment]
Apologies for any confusion on this one. From looking at your logs, your controller isn't seeing any OneWire temperature sensors:

```
May 13 2020 16:56:29 Installed devices received: []
May 13 2020 16:56:29 Available devices received: [{"i": -1, "t": 0, "c": 1, "b": 0, "f": 0, "h": 1, "d": 0, "p": 2, "x": 1}, {"i": -1, "t": 0, "c": 1, "b": 0, "f": 0, "h": 1, "d": 0, "p": 5, "x": 1}, {"i": -1, "t": 0, "c": 1, "b": 0, "f": 0, "h": 1, "d": 0, "p": 6, "x": 1}, {"i": -1, "t": 0, "c": 1, "b": 0, "f": 0, "h": 1, "d": 0, "p": 19, "x": 1}]
```

As a result, your controller can't report any OneWire sensors to Fermentrack. This indicates that your problem is somewhere upstream from Fermentrack. Either with your firmware (you're using the BrewPi Remix firmware), your temperature sensors (if they happen to be parasitic), or with your hardware. Since you mentioned using a test script and seeing the temperature sensors respond, it sounds like your hardware is fine, which would leave the firmware or your temperature sensors.

You mentioned that your temperature probes are connected in normal mode, not parasitic - have you run a test script to confirm this? The reason I ask is that there actually is a different temperature sensor (the part inside the stainless steel probe tip!) for parasitic mode sensors vs. regular ones. Many people buy the "three wire" sensors and use all three wires thinking that they're fine, when the manufacturer has actually used parasitic mode sensors. The only way to easily tell would be to use a test script that tells you whether or not your probes are parasitic mode.

Unfortunately, I don't have a test script for Arduinos as all my builds use the ESP8266 - but if you ask around I know that one exists.
