### ISSUE TITLE
+Add Gravity Sensor Option 

### ISSUE THREAD

**Issue by worgz01** [thorrak/fermentrack#484]
Fermentrack has been working great. I've just made my first iSpindel and low and behold I have not got the option to +Add Gravity Sensor. 

P.S. I am a novice at all this :-)

![image](https://user-images.githubusercontent.com/67539683/85944564-3ed46400-b96a-11ea-9016-31c4c96539bb.png)

**Comment by thorrak** [comment]
I'm guessing you disabled gravity sensor support when you set up Fermentrack. I believe you can update this by clicking the "gear" in the upper right hand corner of Fermentrack and editing Fermentrack's settings.

**Comment by worgz01** [comment]
Thanks. Set up the iSpindel successfully, very easy actually, but can not get communication. Tried re-configuring to different networks, but no success at all. I know the iSpindel is working as it will communicate with Ubidots (when configured to do so). I'm obviously missing something. I've attached some logs that may help :-) 
[brewpi.local.txt](https://github.com/thorrak/fermentrack/files/4874484/brewpi.local.txt)
[stderr.log.txt](https://github.com/thorrak/fermentrack/files/4874485/stderr.log.txt)

**Comment by mp-se** [comment]
Can you check the log for fermentrack, you should have an entry like this

0.0.0.0 - - [05/Jul/2020 05:38:41] "POST /ispindel HTTP/1.0" 200 57

if there is communication between the iSpindel and fermentrack. You can also check if the file /log/ispindel_raw_output.log contains any data.. 

If you cant see these the issue must be in the ispindel configuration or network. Post a screendump of the ispindel config in that case.

**Comment by worgz01** [comment]
Thanks
OK, check the fermentrack log. Nothings (as per above)
Checked the ispindel_raw_output (no data) It does say 
Error opening /home/fermentrack/fermentrack/log/ispindel_raw-output.log logfile: [Errno2] No such file or directory. /home/fermentrack/fermentrack/log/ispindel_raw_output.log'
![image](https://user-images.githubusercontent.com/67539683/86529312-5075b880-bee2-11ea-894b-3d05cc6f8904.png)

**Comment by mp-se** [comment]
It looks like the ispindel cannot find or connect to fermentrack. I would skip the DNS name and only use IP. Your network connections seams to be low so try to place it closer to the router (at least for testing this part)

Try to update the path with the IP adress instead of DNS, i.e. http://192.168.0.17/ispindel

**Comment by worgz01** [comment]
Tried IP address instead of DNS, no luck. 

Even changed networks, (100% strength) still no luck

**Comment by mp-se** [comment]
can you check if fermentrack is responding just to eliminate sources of error. 

If you type in the URL in the web browser http://192.168.0.17/ispindel you should get this error message;

{
    "status": "failed",
    "message": "No JSON data was posted (are you accessing this manually?)"
}

This means that fermentrack is responding as it should. If this is OK, I would try to connect the ispindel to a serial console on a computer an check the output from the console for error.

**Comment by worgz01** [comment]
OK, Fermentrack is responding as you suggested. I'm getting the exact msg.

Connected the ispindel to console and every thing seems to be working. 
![image](https://user-images.githubusercontent.com/67539683/86588386-314c5900-bfbe-11ea-9307-12b40e466f4d.png)

**Comment by mp-se** [comment]
It looks like the iSpindel cant connect to the network. It parses the config but never sends anything, perhaps you can get some support from that project? 

If it was sending ths data correctly, you should have the following in the log which does not appear i your screendump;

After waiting 1000ms, result 3
IP: 192.168.1.182

calling HTTP
{"name":"iSpindel001","ID":14421487,"token":"fermentrack","angle":78.43537,"temperature":29.75,"temp_units":"C","battery":4.004171,"gravity":27.72735,"interval":30,"RSSI":-65}
HTTP API: posting code: 200
{
    "status": "ok",
    "gravity": 0.0
}

Final-sleep: 30s; RT: 2511

**Comment by worgz01** [comment]
OK, now I'm  stuck. I increased the network strength, as a side thought &  "BINGO". One strike only. I got one reading and now only one,  temperature and gravity  reading are both set and do not move. I know when I set up to Ubidots there is no issue. Data was transmitted and received

**Comment by mp-se** [comment]
Have you tried posting your problem om the ispindle project? The issues seams to be there and not with fermentrack.
