### ISSUE TITLE
Specific gravity shows extreme high % ABV.

### ISSUE THREAD

**Issue by exoticatom** [thorrak/fermentrack#487]
My configuration is iSpindel with Fermentrack (I am using it only to follow fermentation) and recently I noticed that graphs shows extreme ABV. Specific gravity seems to be ok as plato.

what could be the issue? 
![image](https://user-images.githubusercontent.com/26557176/88154548-4d2f3c00-cc07-11ea-9d9d-a770b6da833b.png)

**Comment by mp-se** [comment]
Fermentrack is designed to work with SG for gravity measurements not Plato so it not strange that you get high ABV values. Change the setting in the iSpindel to send SG instead of Plato and you would be fine. There is an update coming that will allow you to show Plato on the graphs instead of SG.

**Comment by exoticatom** [comment]
oh dear. Thank you for that.

**Comment by exoticatom** [comment]
hm... there is no setting i iSpindel to send SG. 
iSpindel sends only angle. 


where should I change it then ?

**Comment by exoticatom** [comment]
![image](https://user-images.githubusercontent.com/26557176/88463734-3e6db100-ceb5-11ea-9f05-08264bb96917.png)

**Comment by exoticatom** [comment]
![image](https://user-images.githubusercontent.com/26557176/88463747-64935100-ceb5-11ea-9c05-0f2973a3e0f4.png)

**Comment by exoticatom** [comment]
![Untitled](https://user-images.githubusercontent.com/26557176/88463759-8391e300-ceb5-11ea-97c5-d3bf3470667e.png)

**Comment by exoticatom** [comment]
So where I have to change it.

I delted sensor, created it again and it's showing Plato ....

**Comment by exoticatom** [comment]
or do I have to change formula ?
I used https://github.com/universam1/iSpindel/blob/master/docs/Kalibrierung_en.xlsm

**Comment by mp-se** [comment]
If there is no way to convert in ispindel you need to calibrate it to send SG

**Comment by exoticatom** [comment]
thank you for helping.

I found a way to add calibration points from my excell file into fermentrack and then performed claibration from fementrack itself.
![image](https://user-images.githubusercontent.com/26557176/88465330-6e6f8100-cec2-11ea-9d1d-c0a86687a718.png)
