### ISSUE TITLE
Multiple iSpindels for a single temperature controller/chamber

### ISSUE THREAD

**Issue by pensphreak** [thorrak/fermentrack#498]
I have a chest freezer with room for 2 fermenters.  So I have 2 iSpindels to track the fermentation of those 2 fermenters.  Unfortunately it looks like I can only associate a single iSpindel to a temperature controller (chamber).  Is there a way to associate multiple devices so that I can see the log of the fermentation?

Without that feature, I can't see a graph of the second iSpindel unless I add a second 'log' for the same beer fermenting in the first fermenter

**Comment by thorrak** [comment]
Fermentrack will allow you to add both iSpindels, but as you noted, it will only allow one at a time to be associated with a temperature controller/fermenter.

I'm not sure if this is what you were referring to by "adding a second log", but you can log a fermentation on a gravity sensor in the same way you can log a temperature controller or controller+gravity sensor combination. In this way, you're able to log both sensors separately - but you won't see both on the same graph.
