### ISSUE TITLE
[Feature Request] Add Gravity to the shield screen

### ISSUE THREAD

**Issue by goose-ws** [thorrak/fermentrack#505]
Referring to this screen on the web interface:

![image](https://user-images.githubusercontent.com/874014/96328424-de4c5e00-1010-11eb-8896-335792ecf569.png)

Could it be possible to have it also rotate through its text display the current gravity, if reportable? Curious, as I'm working on adding a shield/screen to my fermenter.

**Comment by thorrak** [comment]
Unfortunately no. That text is read from the controller itself, which doesn't know anything about the gravity.

Gravity could theoretically be added as one of the dash panels, though (similar to the "control mode" and "log interval" panels that you show beneath the LCD in your screenshot)
