### ISSUE TITLE
Django rendering error when setting up pushing to Brewfather

### ISSUE THREAD

**Issue by Coctus** [thorrak/fermentrack#509]
I tried to setup the pushing to Brewfather but forgot to select the device I'm pushing. Django rendering failed and now I can't get to settings menu at all. How could I reset Fermentrack so I could try to setup it again?

`AttributeError at /site/settings/
'NoneType' object has no attribute 'device_name'
Request Method:	GET
Request URL:	http://192.168.0.16/site/settings/
Django Version:	3.0.10
Exception Type:	AttributeError
Exception Value:	
'NoneType' object has no attribute 'device_name'
Exception Location:	/home/fermentrack/fermentrack/external_push/models.py in __str__, line 422
Python Executable:	/home/fermentrack/venv/bin/python3.7
Python Version:	3.7.3
Python Path:	
['/home/fermentrack/venv/bin',
 '/home/fermentrack/venv/lib/python3.7/site-packages/git/ext/gitdb',
 '/home/fermentrack/fermentrack',
 '/home/fermentrack/venv/lib/python3.7/site-packages',
 '/usr/lib/python37.zip',
 '/usr/lib/python3.7',
 '/usr/lib/python3.7/lib-dynload',
 '.',
 '/home/fermentrack/venv/lib/python3.7/site-packages/gitdb/ext/smmap']
Server time:	Tue, 27 Oct 2020 08:26:24 +0000`

`Error during template rendering
In template /home/fermentrack/fermentrack/external_push/templates/external_push/push_target_list_embeddable.html, error at line 51`

'NoneType' object has no attribute 'device_name'
41	    {% endif %}
42	
43	    {#  Then list the Brewfather push targets #}
44	    {% if brewfather_push_targets.count > 0 %}
45	        <h4>Brewfather Push Targets</h4>
46	        <ul class="list-group list-group-flush">
47	        {% for push_target in brewfather_push_targets %}
48	            
49	            <li class="list-group-item">
50	                <div class="row">
51	                    <div class="col-sm-12 col-md-6"><a href="{% url "external_push_brewfather_view" push_target.id %}">{{ push_target }}</a></div>
52	                    <div class="col-sm-2 col-md-2">{{ push_target.status }}</div> {#  TODO - Make this display an error if applicable #}
53	                </div>
54	            </li>
55	            
56	        {% endfor %}
57	    </ul>
58	    {% endif %}
59	
60	    {#  List the thingspeak push targets next #}
61	    {% if thingspeak_push_targets.count > 0 %}

**Comment by thorrak** [comment]
Linking to sentry issue 1969

**Comment by thorrak** [comment]
I've found the _immediate_ issue here and think I have a fix ready to go pending an upcoming PR. That said, I think there is a broader issue in that Fermentrack allowed a `brewfather_push_target` to be created without either a `gravity_sensor_to_push` or `brewpi_to_push` being set.  Going to track this as a separate issue as #521
