### ISSUE TITLE
Add option to adjust temperature reading from an iSpindel

### ISSUE THREAD

**Issue by mp-se** [thorrak/fermentrack#514]
Most of my iSpindels dont show the correct temperature (the ds18b20 arent always calibrated). I propose that we add an option to adjust/calibrate  the temperature reading when it's received to be correct. 

If this is a good feature to have I can create the PR.

**Comment by mp-se** [comment]
@thorrak if you are ok with this addon I can do the development for iSpindel.

**Comment by thorrak** [comment]
Definitely - let me know if I can help!

**Comment by mp-se** [comment]
Will do, I don't think this will be that complicated to handle.

**Comment by thorrak** [comment]
Thank you!
