### ISSUE TITLE
Thoughs on flashing from within the docker container

### ISSUE THREAD

**Issue by mp-se** [thorrak/fermentrack#525]
I started to explore the firmware flashing functionality when running in a docker container. i have tested on a ubuntu desktop installation and not windows yet. 

I've added this option to my docker-compose file to import the USB device into the container;

    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"

That all seams to work so far and the guide in Fermentrack detects the serial port. But since the guide first looks for existing devices and if you follow the guide and attach the chip to be flashed it will not detect a new serial port since it has already been mounted. 

My conclusion is that the guide for flashing needs to be updated if we are running Fermentrack in a docker container to allow us to do the flashing... I guess this could add some complexity for the users to figure out what device to import into the container or the installation scripts needs to update this part. Perhaps a future change when the basic stuff is working.

@thorrak do you have any ideas on how you want to handle this in a container setup?

I'd be happy to explore this further but dont want to move in the wrong direction...

**Comment by thorrak** [comment]
I actually have flashing working in my docker container. What isn’t working at the moment is mDNS and Bluetooth. 

Let me do a PR to your repo for the tweaks I used to get flashing to work.

**Comment by thorrak** [comment]
I sent across a PR for this to your repo - hopefully that works! The firmware flashing is something that I've tested and can confirm currently works. 

For the two other issues I mentioned - Bluetooth and mDNS - I've added [notes](https://github.com/thorrak/fermentrack/issues/412#issuecomment-723457400) to the "Docker support" issue detailing where things currently stand.

**Comment by mp-se** [comment]
Thanks, I will try that out and also see of I can get some success when it comes to bluetooth/mDNS. I bought an USB bluetooth dongle today so I now have something to play around with.
