### ISSUE TITLE
The "numpy" python package is not available which is required for calibration 

### ISSUE THREAD

**Issue by hefevice** [thorrak/fermentrack#540]
Trying to recalculate calibration curves with new points "Perform Calibration with Above Points".

Running on Ubuntu 20.04.1 LTS, numpy links in venv appear to be OK:

geoff@faraday:/home/fermentrack/venv/lib/python3.7/site-packages$ ls -las numpy*
0 lrwxrwxrwx 1 fermentrack fermentrack 36 Nov 23 16:52 numpy -> /usr/lib/python3/dist-packages/numpy
0 lrwxrwxrwx 1 fermentrack fermentrack 52 Nov 23 16:52 numpy-1.17.4.egg-info -> /usr/lib/python3/dist-packages/numpy-1.17.4.egg-info

**Comment by hefevice** [comment]
Worked it out in case anyone else runs into this issue. The numpy and scipy libraries in Ubuntu 20.04.1 are more recent (from 3.8) than the 3.7 expected by fermentrack and as a result were not importing (verified by running python3 in the venv and issuing the import command). Did an alternative installation of Python 3.7, installed numpy and scipy using pip3.7 and linked the resulting site-packages to the venv.

**Comment by thorrak** [comment]
Yikes - sorry about that, and thanks for catching that.

This image actually reminded me that I have yet to solve this problem for the upcoming Dockerized installation path. My current inclination is to just build my own armv7 wheels for Python 3.8 and then add numpy/scipy to requirements.txt which should allow it to work with the manylinux wheels for x86/x64 in cases like yours.
