### ISSUE TITLE
Add Icon for adding shortcut to phones

### ISSUE THREAD

**Issue by akang6** [thorrak/fermentrack#541]
Could we get code added so that we can add Fermentrack to our home screens on phones and have the icons show?

https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

https://web.dev/customize-install/

**Comment by akang6** [comment]
I just submitted my own pull request

**Comment by thorrak** [comment]
This has been merged into master
