### ISSUE TITLE
Chart plot color fields accept invalid entries that don’t work.

### ISSUE THREAD

**Issue by 100amps** [thorrak/fermentrack#553]
In the Django controls, under Constance, the rgb value fields accept invalid rgb values. An error alert or input validation would be helpful.

**Comment by thorrak** [comment]
I agree this is a bug, but unfortunately, there isn't a way to get Constance to validate that RGB inputs are valid. :( 

Sorry about that. If I ever decide to make this part of the standard UI then I'll make sure to get validation implemented.
