### ISSUE TITLE
Registering tiltbridge with names containing hyphen

### ISSUE THREAD

**Issue by kidmock** [thorrak/fermentrack#558]
According to RFC1035, the Hyphen "-" is a valid character in hostnames. However, it appears that adding a tiltbridge that has an mDNS name such as "tilt-garage" consistently fails.

If I rename my host to "tiltgarage", I have no issues. 

I think this maybe a form validation that is checking for alphanumeric, that may need to a "-" to the list. However, I am not yet able to find it in the code and I have a work around.

**Comment by thorrak** [comment]
The check is in the field validation in the model. I've tweaked the regex to `^[a-zA-Z0-9]+[a-zA-Z0-9-]+[a-zA-Z0-9]+$"` - Hopefully that should solve this.

**Comment by kidmock** [comment]
Looks like that fixed it. Thanks
