### ISSUE TITLE
Extra data to external push targets

### ISSUE THREAD

**Issue by gieljnssns** [thorrak/fermentrack#560]
Is it possible to add some extra data to external push targets?

Like,

- is the heating on?
- is the cooling on?
- is the door open?
- fridge setting?
- beer setting?
- ....

**Comment by thorrak** [comment]
Which push targets?

**Comment by gieljnssns** [comment]
At the generic push target please.

**Comment by thorrak** [comment]
Sure thing -- I'm adding Fridge Setting, Beer Setting, and Controller State to the payload for generic push targets. 

Controller state is a number as sent by the controller itself and will require some interpretation - here are the states in order:

```
enum states {
	IDLE,           //!< Neither heating, nor cooling
	STATE_OFF,      //!< Disabled
	DOOR_OPEN,			//!< Fridge door open. Used by the Display only
	HEATING,				//!< Calling for heat
	COOLING,				//!< Calling for cool
	WAITING_TO_COOL,	//!< Waiting to cool. (Compressor delay)
	WAITING_TO_HEAT,			//!< Waiting to heat. (Compressor delay)
	WAITING_FOR_PEAK_DETECT,	//!< Waiting for peak detection
	COOLING_MIN_TIME,			// 8
	HEATING_MIN_TIME,			// 9
	NUM_STATES
};
```

**Comment by gieljnssns** [comment]
🍻🍻🍻

**Comment by gieljnssns** [comment]
How can I update to the newest version to use this?

I've installed with `curl -L install.fermentrack.com | sudo bash`

**Comment by thorrak** [comment]
Click the gear in the upper right, make sure your update preference is set to “Upgrade whenever possible, including beta code”, and then go through the upgrade workflow.
