### ISSUE TITLE
Setup page in browser displays an OperationalError: no such table: gravity_gravitysensor

### ISSUE THREAD

**Issue by MattWeazel** [thorrak/fermentrack#570]
Hello,
I had a Fermentrack setup working great.  I had flashed a copy of a friends setup and adapted it to mine.  When I left it on but unused for 6 months, I couldn't get the graph to load so I re-installed Fermentrack with the command line "curl -L install.fermentrack.com | sudo bash" & everything appeared to complete successfully.  Then I got this error.
I ran the install command line a second time and still have the error.
I am interfacing with an ardrino and a tilt gravity sensor.  Both are connected (no change from when it was working 6 months ago) and the Tilt is displaying data on "Tiltpi".
Please help.
Matt

OperationalError at /setup/
no such table: gravity_gravitysensor
Request Method:	GET
Request URL:	http://192.168.50.84/setup/
Django Version:	3.0.11
Exception Type:	OperationalError
Exception Value:	
no such table: gravity_gravitysensor
Exception Location:	/home/fermentrack/venv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py in execute, line 396
Python Executable:	/home/fermentrack/venv/bin/python3.7
Python Version:	3.7.7
Python Path:	
['/home/fermentrack/venv/bin',
 '/home/fermentrack/venv/lib/python3.7/site-packages/git/ext/gitdb',
 '/home/fermentrack/fermentrack',
 '/home/fermentrack/venv/lib/python3.7/site-packages',
 '/usr/local/lib/python37.zip',
 '/usr/local/lib/python3.7',
 '/usr/local/lib/python3.7/lib-dynload',
 '.',
 '/home/fermentrack/venv/lib/python3.7/site-packages/gitdb/ext/smmap']
Server time:	Fri, 1 Jan 2021 23:58:48 +0000

In template /home/fermentrack/fermentrack/app/templates/sitewide/flat_ui_navbar_left.html, error at line 45
no such table: gravity_gravitysensor
35	{% endif %}
36	                  <span class="dropdown-arrow"></span>
37	                  <ul class="dropdown-menu">
38	
39	{% if config.TEMP_CONTROL_SUPPORT_ENABLED %}{% for this_device in all_devices %}
40	                    <li><a href="{% url 'device_dashboard' this_device.id %}">{{ this_device.device_name }}</a></li>
41	{% endfor %}{% endif %}
42	
43	{# The idea is that for assigned gravity sensors, there's not really much of a reason to go into the individual #}
44	{# sensor as everything should be on the controller dashboard. #}
45	{% if config.GRAVITY_SUPPORT_ENABLED %}{% for this_device in unassigned_gravity_sensors %}
46	                    <li><a href="{% url 'gravity_dashboard' this_device.id %}">{{ this_device.name }}</a></li>
47	{% endfor %}{% endif %}
48	
49	                  {% if config.TEMP_CONTROL_SUPPORT_ENABLED %}
50	                    <li class="divider"></li>
51	                    <li><a href="{% url 'device_guided_select_device' %}"><i class="fa fa-fw fa-plus"></i> Add New Temp Controller (Guided)</a></li>
52	                    <li><a href="{% url 'device_add' %}"><i class="fa fa-fw fa-plus"></i> Add Temp Controller (Advanced)</a></li>
53	                  {% endif %}
54	
55	                  {% if config.GRAVITY_SUPPORT_ENABLED %}

**Comment by MattWeazel** [comment]
Thanks for the quick reply.  
1. So I tried to delete db.sqlite3 file but I get a "permission denied" message.
2. I'm not sure how to do this one?  Are these separate lines I need to type into the command line?
Sorry for being so bad at this.  
Matt

**Comment by thorrak** [comment]
Try the following after ssh'ing in:

```
sudo su fermentrack
cd ~/fermentrack
rm ./db.sqlite3
source ../venv/bin/activate
python3 manage.py migrate
utils/upgrade3.sh -b dev
```

**Comment by MattWeazel** [comment]
That worked!  Thank you, thank you!
Just one issue left - my Tilt won’t connect now.  I can see the data from the Tilt on “TiltPi” but not in Fermentrack.  I ran the troubleshoot and came up with this screen:

I ran the script "sudo setcap cap_net_raw,cap_net_admin+eip /usr/local/bin/python3.7” and nothing happened.  Any suggestions?
Matt
