### ISSUE TITLE
Python is missing required capability flags!

### ISSUE THREAD

**Issue by MattWeazel** [thorrak/fermentrack#578]
I'm trying to connect my Tilt.  I ran the "troubleshoot connection" and received the "Python is missing required capability flags!" message.  I followed the directions and here's what I got:

pi@raspberrypi:~ $ sudo setcap cap_net_raw,cap_net_admin+eip/usr/local/bin/python3.7
usage: setcap [-q] [-v] (-r|-|<caps>) <filename> [ ... (-r|-|<capsN>) <filenameN> ]

 Note <filename> must be a regular (non-symlink) file.

Any suggestions?  BTW - the Tilt is working with "Tiltpi" on the same device so I know the bluetooth connection is working.

**Comment by mp-se** [comment]
There should be a space after iep and /usr in the command.

**Comment by MattWeazel** [comment]
I tried it again with the space after eip and all I get is the "pi@raspberrypi:~ $" prompt again.  Nothing happens.  I rebooted and I'm still getting the "Python is missing required capability flags!" message.

**Comment by mp-se** [comment]
Can you type this commands and post the result? It will show the linux version used.

I've had issues with setcap on older versions of linux. I'm running on v10 buster which works fine.

cat /etc/os-release

**Comment by mp-se** [comment]
On my installation of raspian the path to the python binary is as follows;

sudo setcap cap_net_raw,cap_net_admin+eip /usr/bin/python3.7

You can verify if its the binary file with the ls command like this;
pi@raspberrypi:~ $ ls -al /usr/bin/python3.7
-rwxr-xr-x 2 root root 4275580 jul 25 15:03 /usr/bin/python3.7

If the line starts with an like this it's a link and the setcap command will not work,
lrwxrwxrwx 1 root root       9 mar 26  2019 /usr/bin/python3 -> python3.7

**Comment by MattWeazel** [comment]
pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by MattWeazel** [comment]
pi@raspberrypi:~ $ ls -al /usr/bin/python3.7
ls: cannot access '/usr/bin/python3.7': No such file or directory

**Comment by mp-se** [comment]
I would recommend that you update to release 10 (buster) to see it that works. Here is a link to a guide, 

https://pimylifeup.com/upgrade-raspbian-stretch-to-raspbian-buster/

**Comment by mp-se** [comment]
Can you post the result of this command ?

ls -al /usr/local/bin/python*

**Comment by MattWeazel** [comment]
pi@raspberrypi:~ $ ls -al /usr/local/bin/python*
-rwxr-xr-x 2 root staff 10986216 Jan  1 13:44 /usr/local/bin/python3.7
-rwxr-xr-x 2 root staff 10986216 Jan  1 13:44 /usr/local/bin/python3.7m
-rwxr-xr-x 1 root staff     2908 Jan  1 13:47 /usr/local/bin/python3.7m-config

**Comment by mp-se** [comment]
From what i can see the command should work. Ive read that the capability flags depend on support in the filesystem and linux kernel. So my best bet would be to either run fermentrack as root or try a new version of raspian (buster) to see if that works.

**Comment by MattWeazel** [comment]
Ok.  Going through the upgrade process now.  Takes forever.  I'll let you know how it goes...

**Comment by MattWeazel** [comment]
So I've tried to do the update to release 10 (buster) twice following the directions carefully on the website you provided.  However, I'm still getting this:
pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Do I need to do something to switch to the release 10 that's not on the website directions?

Here's what I got on the second install attempt:

pi@raspberrypi:~ $ sudo apt update
Get:1 http://archive.raspberrypi.org/debian stretch InRelease [25.3 kB]
Get:2 http://raspbian.raspberrypi.org/raspbian stretch InRelease [15.0 kB]
Fetched 40.3 kB in 1s (23.3 kB/s)                                     
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
pi@raspberrypi:~ $ sudo apt dist-upgrade -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@raspberrypi:~ $ sudo rpi-update
 *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
 *** Performing self-update
 *** Relaunching after update
 *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
#############################################################
WARNING: This update bumps to rpi-5.10.y linux tree
See: https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=288234
'rpi-update' should only be used if there is a specific
reason to do so - for example, a request by a Raspberry Pi
engineer or if you want to help the testing effort
and are comfortable with restoring if there are regressions.

DO NOT use 'rpi-update' as part of a regular update process.

##############################################################
Would you like to proceed? (y/N)
 *** Downloading specific firmware revision (this will take a few minutes)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   168  100   168    0     0    293      0 --:--:-- --:--:-- --:--:--   293
100  119M  100  119M    0     0   362k      0  0:05:38  0:05:38 --:--:--  303k
 *** Updating firmware
 *** Updating kernel modules
 *** depmod 5.10.7-v7+
 *** depmod 5.10.7+
 *** Updating VideoCore libraries
 *** Using HardFP libraries
 *** Updating SDK
 *** Running ldconfig
 *** Storing current firmware revision
 *** Deleting downloaded files
 *** Syncing changes to disk
 *** If no errors appeared, your firmware was successfully updated to 246f5ead8d2d017fd2734d79e1f9a606fb65b72c
 *** A reboot is needed to activate the new firmware
pi@raspberrypi:~ $ sudo reboot
Connection to 192.168.50.84 closed by remote host.
Connection to 192.168.50.84 closed.
MattWesselsiMac:~ F15Weazel$ ssh pi@192.168.50.84
pi@192.168.50.84's password: 
Linux raspberrypi 5.10.7-v7+ #1395 SMP Mon Jan 18 16:14:16 GMT 2021 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Mon Jan 18 11:34:41 2021 from 192.168.50.213
pi@raspberrypi:~ $ sudo nano /etc/apt/sources.list
pi@raspberrypi:~ $ sudo nano /etc/apt/sources.list.d/raspi.list
pi@raspberrypi:~ $ sudo apt-get remove apt-listchanges
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'apt-listchanges' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@raspberrypi:~ $ sudo apt update
Get:1 http://archive.raspberrypi.org/debian stretch InRelease [25.3 kB]
Hit:2 http://raspbian.raspberrypi.org/raspbian stretch InRelease               
Fetched 25.3 kB in 1s (14.3 kB/s)                                              
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
pi@raspberrypi:~ $ sudo apt dist-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@raspberrypi:~ $ sudo apt purge timidity lxmusic gnome-disk-utility deluge-gtk evince wicd wicd-gtk clipit usermode gucharmap gnome-system-tools pavucontrol
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'clipit' is not installed, so not removed
Package 'deluge-gtk' is not installed, so not removed
Package 'evince' is not installed, so not removed
Package 'gnome-disk-utility' is not installed, so not removed
Package 'gnome-system-tools' is not installed, so not removed
Package 'gucharmap' is not installed, so not removed
Package 'lxmusic' is not installed, so not removed
Package 'pavucontrol' is not installed, so not removed
Package 'timidity' is not installed, so not removed
Package 'usermode' is not installed, so not removed
Package 'wicd' is not installed, so not removed
Package 'wicd-gtk' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@raspberrypi:~ $ sudo apt autoremove -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@raspberrypi:~ $ sudo apt autoclean
Reading package lists... Done
Building dependency tree       
Reading state information... Done
pi@raspberrypi:~ $ sudo reboot

**Comment by mp-se** [comment]
Have you edited the sources file to point to buster repositories?

sudo nano /etc/apt/sources.list

you should replace strech with buster in that file to make sure its using the right repos.

**Comment by MattWeazel** [comment]
So I got frustrated and decided to just start over.  I re-flashed my micro SD with a fresh, new version of linux and pi desktop software.  Then I re-installed Fermentrack.  The Tilt is connected and working!  But now my arduino is not showing the temperature probe temps on the little black screen with the yellow characters.  Do I need to re-flash that?

**Comment by mp-se** [comment]
Do you mean the brewpi? What type of display is it? 

It could be low power to the display or the audrino is not starting up, some displays have a potentiometer on the back to control contrast. If that isnt working try to reflash

**Comment by uSlackr** [comment]
And make sure you use the config to assign the probes


\\Greg

**Comment by MattWeazel** [comment]
It's an Arduino UNO.  The Fermentrack flash page gets to the "running" stage and never says "finished" - like the documentation says it should?

**Comment by MattWeazel** [comment]
![image](https://user-images.githubusercontent.com/76857002/105417778-f247c300-5bf0-11eb-95c5-33ed2d9b96cd.png)

The temps are all dashes in the upper right...

**Comment by mp-se** [comment]
Fermentrack is flashing in the background. Go to the flash page again and you should see the status.

It looks like the pins are not configured for the device. You need to tell it where the temp probes are connected

**Comment by MattWeazel** [comment]
How long does a flash take?  It's been going for over 2 hours...  Can I restart it?

**Comment by MattWeazel** [comment]
Ok - I got the temperature pins assigned and that all looks good.  I've been trying to get the heating and cooling relays figured out and I'm struggling.  Is there an easy way?  I had pin 5 assigned to cooling and it seemed to work correctly but then I assigned pin 6 to heating and both the heating and cooling came on at the same time.
<img width="788" alt="Screen Shot 2021-01-21 at 4 56 22 PM" src="https://user-images.githubusercontent.com/76857002/105431148-e9afb680-5c09-11eb-9b14-02f74465a473.png">

**Comment by thorrak** [comment]
> Ok - I got the temperature pins assigned and that all looks good. I've been trying to get the heating and cooling relays figured out and I'm struggling. Is there an easy way? I had pin 5 assigned to cooling and it seemed to work correctly but then I assigned pin 6 to heating and both the heating and cooling came on at the same time.

I can't help you with Arduino-based builds, unfortunately, but heating and cooling coming on at the same time sounds like a wiring issue. When you say they both come on at the same time, do you mean that the LEDs both come on, or the actual heating/cooling both come on? Is the same true when the cooling pin is engaged?

**Comment by MattWeazel** [comment]
I wired in lights on the front of my chamber - blue for cooling and red for heat. They are connected to the load side of my relays so I can tell when they are running. I haven’t changed any of the wires and it was working perfectly last year so I don’t think it’s wired wrong. 
i set the temp to 33 degrees an d the cooling came on - perfect. Then I changed the temp to 80 degrees and the heat came on but the cooling did not shut off. Could I be causing it by quickly changing from cold to hot?

**Comment by mp-se** [comment]
Its hard to say what could be wrong. It depends on your build and firmware. Did you flash the device? What was the version you had when it worked? I would check the bulild and see if the wiring is ok and try to test the different parts. Also check the pin configs so everything is correct. I have only used esp builds so i can help in more details.

**Comment by MattWeazel** [comment]
I went through all of the wiring and everything is correct.  I ordered a new Arduino UNO thinking that maybe I had fried it.  I decided this morning to try flashing the current Arduino again.  Here's the error I found poking around on my iPad.  Does this help?
![Uploading Screen Shot 2021-01-23 at 8.57.30 AM.png…]()

**Comment by MattWeazel** [comment]
<img width="1607" alt="Screen Shot 2021-01-23 at 8 57 30 AM" src="https://user-images.githubusercontent.com/76857002/105608713-774dec00-5d59-11eb-9df6-269c303d861f.png">

**Comment by thorrak** [comment]
What were you doing/trying to do when this error popped up?

**Comment by MattWeazel** [comment]
I was trying to flash the Arduino UNO.

**Comment by MattWeazel** [comment]
I bought a brand new Arduino UNO.  It's installed and I started over with a fresh download of Fermentrack.  When I go through the guided flash for a new device, the Firmware Flash Status never goes beyond "running."  I've left it running for over an hour.  I'm getting a little frustrated.  Is there a way to do it through terminal?  Or a way to see what's going on?  Maybe a way to flash the Arduino directly from my Mac with the Arduino app?

![IMG_8566](https://user-images.githubusercontent.com/76857002/105921448-b2684d80-5fed-11eb-8f54-0d8fcef1e6d1.JPG)
![IMG_8567](https://user-images.githubusercontent.com/76857002/105921499-beeca600-5fed-11eb-80f5-36abc025e8e2.JPG)

**Comment by thorrak** [comment]
I'm guessing this is actually issue #589.

I just pushed a fix to the dev branch - when you have a second, please update your copy of Fermentrack, and see if that resolves the issue.

**Comment by MattWeazel** [comment]
THANK YOU! THANK YOU!  THANK YOU!  That fixed it.  I'm up and running again.  Tilt is connected and Fermentrack is heating and cooling my chamber as required.  You guys are amazing...
