### ISSUE TITLE
Fermentrack 504 Gateway Time-out on Raspberry PI Desktop 

### ISSUE THREAD

**Issue by ericpare1** [thorrak/fermentrack#579]
Hi,

My knowledge in linux is none and it's been 3 days i'm trying to find a solution.

I managed to installed Fermentrack successfully on my old Raspberry PI (Gen 1 Model B). I can reach the website and setup everything. But it's slooowww.

I was planning to use a faster device (Beelink Mini-pc). I installed Raspberry PI Desktop and follow the same procedure but when trying to access the website, I got the 504 Gateway Time-out nginx/1.14.2. I have the same thing locally (http://localhost). I tried to increase the timeout value in nginx.conf but no luck.

Can anyone help me to troubleshoot this ?

Thanks!

**Comment by lbussy** [comment]
When you say you have the same thing locally, do you mean you get a gateway timeout when you try that from the local machine?

**Comment by ericpare1** [comment]
Correct. Locally on my mini-pc

**Comment by thorrak** [comment]
It’s going to be a long paste, but what do you see when you run the command `ps -xauf`

**Comment by ericpare1** [comment]
`USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         2  0.0  0.0      0     0 ?        S    05:11   0:00 [kthreadd]
root         3  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [rcu_gp]
root         4  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [rcu_par_gp]
root         5  0.0  0.0      0     0 ?        I    05:11   0:00  \_ [kworker/0:0-events]
root         6  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [kworker/0:0H-mmc_complete]
root         7  0.2  0.0      0     0 ?        I    05:11   0:00  \_ [kworker/u8:0-events_unbound]
root         8  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [mm_percpu_wq]
root         9  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [ksoftirqd/0]
root        10  0.2  0.0      0     0 ?        I    05:11   0:00  \_ [rcu_sched]
root        11  0.0  0.0      0     0 ?        I    05:11   0:00  \_ [rcu_bh]
root        12  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [migration/0]
root        13  0.1  0.0      0     0 ?        I    05:11   0:00  \_ [kworker/0:1-memcg_kmem_cache]
root        14  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [cpuhp/0]
root        15  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [cpuhp/1]
root        16  1.0  0.0      0     0 ?        S    05:11   0:00  \_ [migration/1]
root        17  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [ksoftirqd/1]
root        18  0.0  0.0      0     0 ?        I    05:11   0:00  \_ [kworker/1:0-cgroup_destroy]
root        19  0.3  0.0      0     0 ?        I<   05:11   0:00  \_ [kworker/1:0H-kblockd]
root        20  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [cpuhp/2]
root        21  1.0  0.0      0     0 ?        S    05:11   0:00  \_ [migration/2]
root        22  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [ksoftirqd/2]
root        23  0.0  0.0      0     0 ?        I    05:11   0:00  \_ [kworker/2:0-cgroup_destroy]
root        24  0.1  0.0      0     0 ?        I<   05:11   0:00  \_ [kworker/2:0H-kblockd]
root        25  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [cpuhp/3]
root        26  1.0  0.0      0     0 ?        S    05:11   0:00  \_ [migration/3]
root        27  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [ksoftirqd/3]
root        28  0.0  0.0      0     0 ?        I    05:11   0:00  \_ [kworker/3:0-memcg_kmem_cache]
root        29  0.4  0.0      0     0 ?        I<   05:11   0:00  \_ [kworker/3:0H-events_highpri]
root        30  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [kdevtmpfs]
root        31  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [netns]
root        32  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [kauditd]
root        33  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [khungtaskd]
root        34  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [oom_reaper]
root        35  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [writeback]
root        36  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [kcompactd0]
root        37  0.0  0.0      0     0 ?        SN   05:11   0:00  \_ [ksmd]
root        38  0.0  0.0      0     0 ?        SN   05:11   0:00  \_ [khugepaged]
root        39  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [crypto]
root        40  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [kintegrityd]
root        41  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [kblockd]
root        42  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [edac-poller]
root        43  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [devfreq_wq]
root        44  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [watchdogd]
root        45  0.0  0.0      0     0 ?        I    05:11   0:00  \_ [kworker/1:1-mm_percpu_wq]
root        46  0.3  0.0      0     0 ?        I    05:11   0:00  \_ [kworker/2:1-mm_percpu_wq]
root        47  0.6  0.0      0     0 ?        I    05:11   0:00  \_ [kworker/3:1-mm_percpu_wq]
root        48  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [kswapd0]
root        66  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [kthrotld]
root        67  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [ipv6_addrconf]
root        68  0.0  0.0      0     0 ?        I    05:11   0:00  \_ [kworker/u8:1-events_unbound]
root        77  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [kstrp]
root        80  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [irq/115-ACPI:Ev]
root       122  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [spi1]
root       126  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [spi2]
root       128  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [spi3]
root       131  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [irq/45-mmc0]
root       132  0.4  0.0      0     0 ?        I    05:11   0:00  \_ [kworker/3:2-events]
root       138  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [acpi_thermal_pm]
root       139  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [irq/46-mmc1]
root       145  0.0  0.0      0     0 ?        I    05:11   0:00  \_ [kworker/2:2-events]
root       156  0.1  0.0      0     0 ?        I    05:11   0:00  \_ [kworker/u8:2-events_unbound]
root       195  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [mmc_complete]
root       196  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [kworker/3:1H]
root       197  1.0  0.0      0     0 ?        I<   05:11   0:00  \_ [kworker/0:1H-mmc_complete]
root       198  0.0  0.0      0     0 ?        I    05:11   0:00  \_ [kworker/1:2-cgroup_destroy]
root       199  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [irq/47-mmc2]
root       200  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [irq/162-80860F1]
root       201  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [kworker/1:1H-kblockd]
root       202  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [kworker/2:1H]
root       203  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [kworker/0:2H-mmc_complete]
root       204  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [kworker/1:2H]
root       205  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [irq/119-axp288_]
root       206  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [kworker/1:3H]
root       207  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [kworker/u9:0-hci0]
root       208  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [i915/signal:0]
root       209  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [i915/signal:1]
root       210  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [i915/signal:2]
root       211  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [i915/signal:6]
root       220  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [md]
root       230  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [raid5wq]
root       277  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [kworker/2:2H-kblockd]
root       278  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [kworker/3:2H-kblockd]
root       284  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [jbd2/mmcblk0p2-]
root       285  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [ext4-rsv-conver]
root       338  0.2  0.0      0     0 ?        I<   05:11   0:00  \_ [kworker/2:3H-kblockd]
root       340  0.0  0.0      0     0 ?        I    05:11   0:00  \_ [kworker/u8:3-events_unbound]
root       342  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [rpciod]
root       343  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [xprtiod]
root       368  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [irq/165-ACPI:Ev]
root       388  0.0  0.0      0     0 ?        I    05:11   0:00  \_ [kworker/0:2-events]
root       402  0.0  0.0      0     0 ?        S    05:11   0:00  \_ [irq/166-proc_th]
root       403  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [sst_post_msg_wq]
root       404  0.1  0.0      0     0 ?        S    05:11   0:00  \_ [irq/29-intel_ss]
root       405  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [kworker/u9:1-hci0]
root       406  2.3  0.0      0     0 ?        I<   05:11   0:00  \_ [kworker/u9:2-hci0]
root       412  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [cfg80211]
root       415  0.0  0.0      0     0 ?        I<   05:11   0:00  \_ [kworker/3:3H-kblockd]
root       446  0.0  0.0      0     0 ?        I<   05:12   0:00  \_ [kworker/u9:3-hci0]
root       473  0.0  0.0      0     0 ?        I    05:12   0:00  \_ [kworker/2:3-cgroup_destroy]
root       585  0.0  0.0      0     0 ?        I    05:12   0:00  \_ [kworker/1:3]
root       603  0.0  0.0      0     0 ?        I    05:12   0:00  \_ [kworker/3:3-rcu_gp]
root       667  0.0  0.0      0     0 ?        I    05:12   0:00  \_ [kworker/0:3-events]
root       713  0.0  0.0      0     0 ?        I<   05:12   0:00  \_ [brcmf_wq/mmc1:0]
root       715  0.0  0.0      0     0 ?        S    05:12   0:00  \_ [brcmf_wdog/mmc1]
root      1234  0.0  0.0      0     0 ?        S<   05:12   0:00  \_ [krfcommd]
root         1  9.4  0.2  35428  8928 ?        Ss   05:11   0:04 /sbin/init splash
root       319  1.4  0.1  19796  7844 ?        Ss   05:11   0:00 /lib/systemd/systemd-journald
root       348  2.0  0.1  20756  4684 ?        Ss   05:11   0:00 /lib/systemd/systemd-udevd
root       506  1.7  0.1   8184  4708 ?        Ss   05:12   0:00 /usr/sbin/haveged --Foreground --verbose=1 -w 1024
root       509  0.1  0.1  12672  5464 ?        SNs  05:12   0:00 /usr/sbin/alsactl -E HOME=/run/alsa -s -n 19 -c rdaemon
root       511  0.0  0.0   6996   688 ?        Ss   05:12   0:00 /usr/sbin/anacron -d -q -s
message+   512  1.1  0.1   7104  4076 ?        Ss   05:12   0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork -
root       514  0.0  0.1  13444  4488 ?        Ss   05:12   0:00 /sbin/wpa_supplicant -u -s -O /run/wpa_supplicant
root       515  0.2  0.1  25916  5912 ?        Ssl  05:12   0:00 /usr/sbin/rsyslogd -n -iNONE
root       518  0.4  0.1  14632  6404 ?        Ss   05:12   0:00 /lib/systemd/systemd-logind
root       520  0.7  0.3  66552 13376 ?        Ssl  05:12   0:00 /usr/lib/udisks2/udisksd
nobody     521  0.0  0.0   4724  2508 ?        Ss   05:12   0:00 /usr/sbin/thd --triggers /etc/triggerhappy/triggers.d/ --so
root       523  0.2  0.1  11280  5552 ?        Ss   05:12   0:00 /usr/lib/bluetooth/bluetoothd
root       528  0.0  0.0   8228  2620 ?        Ss   05:12   0:00 /usr/sbin/cron -f
root       534  0.6  0.2  36488  8704 ?        Ss   05:12   0:00 /usr/sbin/cupsd -l
lp        1363  0.1  0.1  14996  5600 ?        S    05:12   0:00  \_ /usr/lib/cups/notifier/dbus dbus://
avahi      539  0.2  0.0   6016  2984 ?        Ss   05:12   0:00 avahi-daemon: running [raspberry.local]
avahi      557  0.0  0.0   5864   240 ?        S    05:12   0:00  \_ avahi-daemon: chroot helper
root       543  0.2  0.0  28160    80 ?        SLsl 05:12   0:00 /usr/sbin/rngd -r /dev/hwrng
root       565  2.0  0.2  42972 10624 ?        Ssl  05:12   0:00 /usr/sbin/cups-browsed
root       575  0.1  0.0   3364  2300 ?        Ss   05:12   0:00 /sbin/dhcpcd -q -b
root       601  0.5  0.2  43048 11256 ?        Ssl  05:12   0:00 /usr/lib/policykit-1/polkitd --no-debug
ntp        685  0.0  0.0   9552  3084 ?        Ssl  05:12   0:00 /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 104:110
root       687  0.1  0.1  11632  6104 ?        Ss   05:12   0:00 /usr/sbin/sshd -D
root      1375  1.5  0.1  12440  7216 ?        Ss   05:12   0:00  \_ sshd: pi [priv]
pi        1384  0.0  0.1  12440  4680 ?        S    05:12   0:00      \_ sshd: pi@pts/0
pi        1385  1.8  0.1   9360  4336 pts/0    Ss   05:12   0:00          \_ -bash
pi        1404  0.0  0.0  10268  3152 pts/0    R+   05:12   0:00              \_ ps -xauf
root       688  0.2  0.2  50692  8264 ?        Ssl  05:12   0:00 /usr/sbin/lightdm
root       754  4.1  0.8  89400 32084 tty7     Ssl+ 05:12   0:01  \_ /usr/lib/xorg/Xorg :0 -seat seat0 -auth /var/run/lightd
root      1050  0.2  0.2  33232 10500 ?        Sl   05:12   0:00  \_ lightdm --session-child 14 17
pi        1054  0.5  0.3  58988 14180 ?        Ssl  05:12   0:00      \_ /usr/bin/lxsession -s LXDE-pi -e LXDE
pi        1088  0.0  0.0   5716   296 ?        Ss   05:12   0:00          \_ /usr/bin/ssh-agent x-session-manager
pi        1106  0.6  0.4  67592 16932 ?        S    05:12   0:00          \_ openbox --config-file /home/pi/.config/openbox/
pi        1111  0.1  0.3  49416 12472 ?        Sl   05:12   0:00          \_ lxpolkit
pi        1114  3.5  0.8 426520 34444 ?        Sl   05:12   0:01          \_ lxpanel --profile LXDE-pi
pi        1116  2.7  0.6  86276 24308 ?        Sl   05:12   0:00          \_ pcmanfm --desktop --profile LXDE-pi
root       753  0.2  0.0   4764  3332 tty1     Ss   05:12   0:00 /bin/login -f
pi        1032  0.4  0.1   9364  4196 tty1     S+   05:12   0:00  \_ -bash
root       755  0.0  0.0  53088  1252 ?        Ss   05:12   0:00 nginx: master process /usr/sbin/nginx -g daemon on; master_
www-data   756  0.0  0.0  53244  2700 ?        S    05:12   0:00  \_ nginx: worker process
www-data   757  0.0  0.0  53244  2700 ?        S    05:12   0:00  \_ nginx: worker process
www-data   758  0.0  0.0  53244  2700 ?        S    05:12   0:00  \_ nginx: worker process
www-data   759  0.0  0.0  53244  2700 ?        S    05:12   0:00  \_ nginx: worker process
redis      762  0.4  0.1  40048  5820 ?        Ssl  05:12   0:00 /usr/bin/redis-server 127.0.0.1:6379
root       972  0.0  0.0  13656  2504 ?        Ss   05:12   0:00 wpa_supplicant -B -c/etc/wpa_supplicant/wpa_supplicant.conf
Debian-+  1005  0.0  0.0  16152  2604 ?        Ss   05:12   0:00 /usr/sbin/exim4 -bd -q30m
ferment+  1013  8.5  0.4  48120 16120 ?        Sl   05:12   0:02 /home/fermentrack/venv/bin/python3 /home/fermentrack/venv/b
ferment+  1209  7.3  0.5  47260 19980 ?        Ssl  05:12   0:02  \_ /home/fermentrack/venv/bin/python3 -c from circus impor
ferment+  1402  2.0  0.0      0     0 ?        Zs   05:12   0:00  \_ [python] <defunct>
ferment+  1403 21.5  0.0      0     0 ?        Zs   05:12   0:00  \_ [python] <defunct>
pi        1016  0.6  0.2  16348  8032 ?        Ss   05:12   0:00 /lib/systemd/systemd --user
pi        1018  0.0  0.0  17960  1812 ?        S    05:12   0:00  \_ (sd-pam)
pi        1062  0.3  0.0   6684  3812 ?        Ss   05:12   0:00  \_ /usr/bin/dbus-daemon --session --address=systemd: --nof
pi        1096  0.1  0.1  44660  6724 ?        Ssl  05:12   0:00  \_ /usr/lib/gvfs/gvfsd
pi        1222  0.2  0.2  57160  8840 ?        Sl   05:12   0:00  |   \_ /usr/lib/gvfs/gvfsd-trash --spawner :1.4 /org/gtk/g
pi        1101  0.1  0.2  58352  9424 ?        Sl   05:12   0:00  \_ /usr/lib/gvfs/gvfsd-fuse /run/user/1000/gvfs -f -o big_
pi        1148  1.9  0.3 378436 13432 ?        S<sl 05:12   0:00  \_ /usr/bin/pulseaudio --daemonize=no
pi        1172  0.2  0.3  82632 13172 ?        Ssl  05:12   0:00  \_ /usr/lib/gvfs/gvfs-udisks2-volume-monitor
pi        1183  0.0  0.1  40844  5096 ?        Ssl  05:12   0:00  \_ /usr/lib/gvfs/gvfs-mtp-volume-monitor
pi        1189  0.0  0.1  40964  6916 ?        Ssl  05:12   0:00  \_ /usr/lib/gvfs/gvfs-goa-volume-monitor
pi        1197  0.0  0.2  57272  7984 ?        Ssl  05:12   0:00  \_ /usr/lib/gvfs/gvfs-afc-volume-monitor
pi        1210  0.0  0.1  42796  5512 ?        Ssl  05:12   0:00  \_ /usr/lib/gvfs/gvfs-gphoto2-volume-monitor
pi        1127  0.0  0.0   5716   300 ?        Ss   05:12   0:00 /usr/bin/ssh-agent -s
pi        1132  0.0  0.0   2512   568 ?        S    05:12   0:00 sh /etc/xdg/lxsession/LXDE-pi/sshpwd.sh
pi        1141  2.3  1.1 206696 44172 ?        Sl   05:12   0:00  \_ zenity --warning --width=400 --text=SSH is enabled and
pi        1142  2.9  0.7  54224 30676 ?        S    05:12   0:00 /usr/bin/python3 /usr/share/system-config-printer/applet.py
rtkit     1162  0.0  0.0  23600  2712 ?        SNsl 05:12   0:00 /usr/lib/rtkit/rtkit-daemon
pi        1168  0.0  0.2  30276  8808 ?        Sl   05:12   0:00 /usr/lib/menu-cache/menu-cached /run/user/1000/menu-cached-
colord    1364  2.4  0.3  51204 12972 ?        Ssl  05:12   0:00 /usr/lib/colord/colord`

**Comment by ericpare1** [comment]
[ps.txt](https://github.com/thorrak/fermentrack/files/5789944/ps.txt)

**Comment by thorrak** [comment]
It looks like your fermentrack process is dying for some reason. Let's try to figure out why... 

When you have a second, run the following:

```
sudo tail -30 /home/fermentrack/fermentrack/log/fermentrack-stderr.log 
sudo tail -30 /home/fermentrack/fermentrack/log/huey-stderr.log
sudo tail -30 /home/fermentrack/fermentrack/log/upgrade.log
```

Again - you'll get 90 lines of output. That's fine!

**Comment by ericpare1** [comment]
The first command didn't output any data
[upgrade.log](https://github.com/thorrak/fermentrack/files/5789973/upgrade.log)
[huey-stderr.log](https://github.com/thorrak/fermentrack/files/5789974/huey-stderr.log)

**Comment by thorrak** [comment]
Well, there's your problem:
```
Traceback (most recent call last):
  File "/home/fermentrack/fermentrack/manage.py", line 4, in <module>
    from django.db import IntegrityError
ModuleNotFoundError: No module named 'django'
```
Something seems to be off about your environment, given that cryptography failed to install. To me, that would indicate that something strange is going on with your build environment.

Do you happen to know what processor the Beelink uses? Separately, what method did you use to install Fermentrack?

**Comment by ericpare1** [comment]
4 core Intel(R) Atom(TM) x5-Z8350  CPU @ 1.44GHz
[cpu.txt](https://github.com/thorrak/fermentrack/files/5790087/cpu.txt)

I did this command to install Fermentrack (same thing I did on the Gen1 Raspberry Pi) :`pi@raspberrypi:~ $ curl -L install.fermentrack.com | sudo bash`

**Comment by ericpare1** [comment]
FYI, It did work on the Ubuntu release but it wasn't able to install the wifi driver. Either I troubleshoot Fermentrack on Raspberry PI desktop or my Broadcom wifi drivers on Ubuntu. Linux is such a big deal for me... lol

**Comment by thorrak** [comment]
Try installing the Docker version under Raspbian.

The installation command is:
`curl -L https://raw.githubusercontent.com/thorrak/fermentrack-tools/docker/automated_install/auto-install.sh | bash` rather than the `curl -L install...` command you used before.

It should hopefully fix your issues - and has the added benefit of being what Fermentrack is moving towards in the future.

**Comment by ericpare1** [comment]
I reinstalled the O.S. and this command worked.

Thank you very much @thorrak

**Comment by dannyshaw** [comment]
I've just had this same issue@thorrak

It looks like `cryptography` now requires a Rust toolchain in order to build and fresh installations are failing. 
Pinning it to `cryptography==3.3.2` in `requirements.txt` (manually) and re-running `utils/upgrade3.sh` got me up and running again.
