### ISSUE TITLE
Further docker support

### ISSUE THREAD

**Issue by mcinnes01** [thorrak/fermentrack#585]
Hi 

I've been trying to create a home assistant [addon](https://www.home-assistant.io/addons/) for fermentrack, building on from the docker image @mp-se has created.

I'm close to getting it working, but one of the issues I have is around persistence. I've seen the PR that detects if fermentrack is running in docker and then suffixes the base path with /db, but I wonder if we could take this a step further still...

Basically with home assistant or more specifically hassio addons, they do a lot of plumbing for you and the convention is that you get a bind-mount in your addons container for you to persist data back to the docker host at "/data". Sadly this is a bind-mount and not a volume, I spent hours not realising this and trying to get a symbolic link to work between it and the various persistence folders for fermentrack:

/home/fermentrack/fermentrack/data
/home/fermentrack/fermentrack/db
/home/fermentrack/fermentrack/log

I'll start by saying python isn't my strongest point, but I wondered what effort would be involved and if it's even possible to have it so we can specify these folders as part of the installation? That way in a docker container or even on a server, it would be possible to decide where you want these folders creating.

Thanks in advance for your help, and I really enjoy using fermentrack :)

Andy

**Comment by thorrak** [comment]
Hey there!

What exactly does the addon do? Run Fermentrack, or interface with an external installation of Fermentrack?

**Comment by mcinnes01** [comment]
Hi 

An add-on is just what home assistant calls something that runs in a docker container, so consider add-on a container with some convenience around it's configuration and management. Basically home assistant manages the host server and also has a hypervisor to manage docker. This allows you to run other applications within docker and manage them through home assistant.

This gives various benefits such as a nice add-on store interface when you can install, update and remove add-ons. It also has a few conventions built in to cover things like providing a bind mount for your container to persist data, ways of providing configuration for your add-on through the home assistant UI and also what they call  ingress. 

Ingress does some routing to proxy from the home assistant UI to the UI running in your add-on. It creates a proxy and automatically following some convention maps the a port to the add-on allowing it to not only render the add-on UI within home assistant, but also to automatically provide a menu link to the add-on.

What I've managed to do so far is take the dockerfile @mp-se has running fermentrack all in one container. Then I've tweaked it a little to fit with some of the home assistant add-on requirements.

Currently I can install the add-on and fermentrack initializes correctly, but I have an issue persisting the data. HA add-ons get a bind mount of /data but I spent hours trying to get a symbolic link working to the directories like /home/fermentrack/fermentrack/db mapped to /data/fermentrack/db and so on, but sadly bind mounts don't support symbolic links.

I've forked the fermentrack Dev branch and I've started by updating the settings.py to try to read some environment variables for data and db directories so if you specify them it uses them.

However I'm not sure if that would be sufficient and also I started looking at the log directory but that seems to define the log path where it is used. I may be wrong I'm not particularly experienced with python other than the odd lambda function. 

I'm happy to put a PR in but I will definitely need your input around the issues above. 

Thanks again 

Andy

**Comment by thorrak** [comment]
Do you have any documentation on the "bind mounts" you're referring to in the context of hassio? 

Additionally, do you have your dockerfile available anywhere (GitHub or otherwise) I could see it?

**Comment by mcinnes01** [comment]
Absolutely...

So the HA documentation is a bit light on addon development but here is a [link](https://developers.home-assistant.io/docs/add-ons/configuration)

Bind mounts are configurable for various things such as config, backup, addons, ssl, etc there is a little in the above HA docs, but by default each addon gets a read write bind-mount of /data. [Here](https://docs.docker.com/storage/bind-mounts/) is a much better description, but the key thing is they aren't as flexible as volumes.

My attempt so far is [here](https://github.com/mcinnes01/addon-fermentrack)

Currently the only way I can access it by setting a port mapping to the exposed port of the my addon (which you can do in home assistant) and then I can use my home assistant host with that port to access it directly. I.e. 192.168.1.1:8080

This is to do with the way nginx is configured in the addons I've been told in the past, but not really had much elaboration how to get it working. There are loads of examples of things with working ingress allowing HA to render the addon ui in HA. [This](https://github.com/hassio-addons/addon-node-red/tree/master/node-red/rootfs/etc) is for running node-red as an addon in home assistant, but sadly I have very little experience with nginx (.net developer by day) and I don't really know where to begin.

That node-red example seems a very common structure for nginx in a lot of docker containers as well as home assistant addons, but sadly I really don't understand it much.

**Comment by thorrak** [comment]
You should be able to symlink everything to a directory in `/data` and have it work. What was (or wasn't) happening when you tried that?

**Comment by mcinnes01** [comment]
Basically as it is a bind-mount, it was creating the symlink on the host from the container as the container has full control over the directory. So within the container all looked well and I could see my files linking from the fermentrack directories to my data directories. 

However on the host, there is just 3 broken symlinks. This is because by creating the symlinks from the container, it essentially runs the same command on the host. So it was trying to link to 3 fermentrack directories on the host that don't exist as they only exist in the container.

**Comment by mcinnes01** [comment]
I started playing with this idea: https://github.com/mcinnes01/fermentrack/commit/34fc2b7736085e11eb87920f4679ba1c063785e2

**Comment by thorrak** [comment]
Unfortunately, I'm not keen on adding configuration options for any additional folders if possible.

The logs aren't important for persistence - and honestly, I'd consider wiping them on container creation to be advantageous. Prevents old issues from showing up on a fresh version of the code. ;)

I can't find any documentation where the "magic" folders such as /data are specified in the hassio documentation - and it looks like there may be a `hostconfig.json` file where [bind options can be specified](https://community.home-assistant.io/t/bind-new-volume-on-homeassistant-container-installed-via-hassio-install-sh/143618/2). 

Have you tried specifying binds that are more applicable to Fermentrack (or - alternatively - seeing if hostconfig.json will accept a `Volumes` option as I'm guessing that this configures portainer somehow?)

**Comment by mcinnes01** [comment]
That hostconfig.json is sadly someone just hacking around home assistants supervisor, these changes could be lost by an upgrade or restoring a backup etc or worse upset the supervisor. I came across a similar issue when trying to mount an external drive to a plex addon.

The binds you get for addons are all dictated by convention in the config.json and sadly they don't give you enough rope to hang yourself by specifying custom mounts.

Each addon essentially get's it's own sandboxed folder in /usr/share/hassio/addons/data/my-addon and there are others like the general config folder in home assistant you can grant access to and say with its read-only or read-write. But again all of these are bind-mounts.

Could you see any problem of having the fermentrack data and db folders specified somewhere outside of:
home/fermentrack/fermentrack? Also for maybe raspberry pi users would it not be useful to be able to specify a usb drive mount or network drive in case the sd card dies?

**Comment by thorrak** [comment]
Well, that's annoying. The folders should always be a subfolder of the main Fermentrack directory. It might work with a different configuration - but it's not one that I recommend/would support. 

I'm sure there's some reason not to do this, but you could always change the Fermentrack user's home directory to something like `/data/fermentrack`. You'll end up persisting almost everything (including the codebase) - but it should work, and it would keep the data in a subfolder of the main Fermentrack directory. 

To your question - if an RPi user installing onto bare metal wanted to specify a network drive/other device to save their data, I would tell them to mount the share/device at the ~fermentrack/data directory. ;)

(Or, honestly, I would tell them to set up automated backups to copy their data to their backup device. Installing Fermentrack on another device leads to _weird_ issues when the drive accidentally gets disconnected)

**Comment by mp-se** [comment]
The simple approach would probably be to install fermentrack into the /data dir to avoid changes to fermentrack, then you will have everything stored in one place and even git upgrades should work. You could probably modify my docker image and point the home directory towards /data instead of /home/fermentrack to make that work with minimal changes. 

But if you cannot control what is mapped to your container you will not be able to utilize the firmware flashing functions within fermentrack since that requires that the /dev file system is mounted into the container. Just to be aware of the limitations that this approach will have.

**Comment by mcinnes01** [comment]
Thanks, I had a similar thought about setting the root folder to data but also had that same feeling that it would mean the application code would get written to home assistant too.

I did see the details on configuring docker to allow the usb flashing to work by mounting dev. I think I have this taken care of, but it doesn't supply dev on it's own, you get: /dev/bus/usb

And then it also provides all the devices like so:
![image](https://user-images.githubusercontent.com/877512/104889613-5b67d600-5966-11eb-9214-7cb1dfd09a96.png)

This is working for other addons such as esp-home which I also use to flash devices.

**Comment by mp-se** [comment]
The fermentrack code/script work directly with /dev so you will need to change that part of the  code that work with devices for this to work. Would apply to both serial brewpi integration and firmware flashing.

**Comment by mcinnes01** [comment]
Ok cool can you point me in the right direction of that? 

I'm just trying a few things in regards to moving the data and db directories out of the fermentrack route on my fork, just for curiosities sake. This might seem a silly question, but if I update the settings.py file do I need to run some build or packaging or will that suffice?

And in my docker file I do a git clone to get fermentrack I've update this to my fork, but the commit output by fermentrack when it initializes is your last dev branch commit not mine. Is there something else I need to do to get it to pick that up?

Many thanks

Andy

**Comment by mcinnes01** [comment]
One thing db wise I've not looked at yet but is possible, is to run the postgres addon and make it a dependency of the fermentrack addon. I've not seen how to do that yet, but there are other relying on other database addons already. Like I use nginx proxy manager and that uses the influxdb addon. That would only leave the data directory as an issue.

This would be a kind of hybrid between your docker implementation and the all in one approach. I.e. keep fermentrack, redis and nginx in the fermentrack container and then use a separate db container. Still have that issue of the data folder though :(

**Comment by mp-se** [comment]
> Ok cool can you point me in the right direction of that?

Make a search for /dev in the code, you should find a starting point. I havent been digging in that area yet. 

> I'm just trying a few things in regards to moving the data and db directories out of the fermentrack route on my fork, just for curiosities sake. This might seem a silly question, but if I update the settings.py file do I need to run some build or packaging or will that suffice?

A restart of the application (django) should be sufficient. Either restart the image or just restart it via circusctl
 
> And in my docker file I do a git clone to get fermentrack I've update this to my fork, but the commit output by fermentrack when it initializes is your last dev branch commit not mine. Is there something else I need to do to get it to pick that up?

The entrypoint.sh script just run a few git command to show that information. Source and last commit. If you are cloning from your own fork it should display that information. Try to connect to the docker image and see if you can figure out what is happening. If you are running docker you should be able to connect with "docker exec -it fermentrack /bin/bash" and get a bash shell.

**Comment by mp-se** [comment]
> One thing db wise I've not looked at yet but is possible, is to run the postgres addon and make it a dependency of the fermentrack addon. I've not seen how to do that yet, but there are other addons relying on other database addons already. Like I use nginx proxy manager and that uses the influxdb addon. That would only leave the data directory as an issue.
> 
> This would be a kind of hybrid between your docker implementation and the all in one approach. I.e. keep fermentrack, redis and nginx in the fermentrack container and then use a separate db container. Still have that issue of the data folder though :(

If you want to go this route you should look into the offical docker release (it's currently in the fermentrack dev branch), that uses a separate image for postgres. it's working from what I have tested so far.

**Comment by mcinnes01** [comment]
Great I'm just picking this back up now, going to have one last play messing with the data and db folders outside of the fermentrack root the I will try relying on postrgres for the db source. That still doesn't fix my the fermentrack/data folder issue though. 

Just to help with my lack of knowledge around the fermentrack implementation, what is stored in the /home/fermentrack/fermentrack/data folder and is the contents of this important if for example you want to restart the docker container? And how frequently or maybe just when are files added/update/used in this folder?

One potential idea I have with this folder is to perhaps see if I can set something up that copys files from the /data folder to /home/fermentrack/fermentrack/data at start up and either on a cron whilst running or if there is some way of triggering a script when the container is shutting down.

**Comment by thorrak** [comment]
`/home/fermentrack/fermentrack/data` contains all of the logs of your ferments (the data used to generate the graphs) so you'd likely want to retain it between container recreations. 

Again, you could just do this: https://github.com/thorrak/addon-fermentrack/commit/d1f67a65287ae9e18502162b099e973f9d64f997 😉  
Just sayin'.

If you can go the Postgres route I would _highly_ recommend it - even if everything else lives in a single container. Postgres > SQLite in every way _except_ ease of installation. I'd tackle that as a separate issue though as @mp-se 's implementation works out of the box with SQLite.

**Comment by mcinnes01** [comment]
Yep so just to confirm it hates having the data and db folders moved like I'd tried with the environment variables:

> Traceback (most recent call last):
>   File "manage.py", line 25, in <module>
>     execute_from_command_line(sys.argv)
>   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
>     utility.execute()
>   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 231, in fetch_command
>     settings.INSTALLED_APPS
>   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 76, in __getattr__
>     self._setup(name)
>   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 63, in _setup
>     self._wrapped = Settings(settings_module)
>   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 142, in __init__
>     mod = importlib.import_module(self.SETTINGS_MODULE)
>   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/home/fermentrack/fermentrack/fermentrack_django/settings.py", line 131, in <module>
>     DB_DIR = env("MOUNT_DB_DIR")
>   File "/home/fermentrack/venv/lib/python3.7/site-packages/environ/environ.py", line 123, in __call__
>     return self.get_value(var, cast=cast, default=default, parse_default=parse_default)
>   File "/home/fermentrack/venv/lib/python3.7/site-packages/environ/environ.py", line 277, in get_value
>     raise ImproperlyConfigured(error_msg)
> django.core.exceptions.ImproperlyConfigured: Set the MOUNT_DB_DIR environment variable
> Applying database migration
> Traceback (most recent call last):
>   File "/home/fermentrack/venv/lib/python3.7/site-packages/environ/environ.py", line 273, in get_value
>     value = self.ENVIRON[var]
>   File "/usr/lib/python3.7/os.py", line 678, in __getitem__
>     raise KeyError(key) from None
> KeyError: 'MOUNT_DB_DIR'
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "manage.py", line 25, in <module>
>     execute_from_command_line(sys.argv)
>   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
>     utility.execute()
>   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/core/management/base.py", line 366, in execute
>     self.check()
>   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/core/management/base.py", line 395, in check
>     include_deployment_checks=include_deployment_checks,
>   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 63, in _run_checks
>     issues = run_checks(tags=[Tags.database])
>   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
>     new_errors = check(app_configs=app_configs)
>   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/core/checks/database.py", line 9, in check_database_backends
>     for conn in connections.all():
>   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/db/utils.py", line 222, in all
>     return [self[alias] for alias in self]
>   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/db/utils.py", line 219, in __iter__
>     return iter(self.databases)
>   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
>     res = instance.__dict__[self.name] = self.func(instance)
>   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/db/utils.py", line 153, in databases
>     self._databases = settings.DATABASES
>   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 76, in __getattr__
>     self._setup(name)
>   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 63, in _setup
>     self._wrapped = Settings(settings_module)
>   File "/home/fermentrack/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 142, in __init__
>     mod = importlib.import_module(self.SETTINGS_MODULE)
>   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/home/fermentrack/fermentrack/fermentrack_django/settings.py", line 131, in <module>
>     DB_DIR = env("MOUNT_DB_DIR")
>   File "/home/fermentrack/venv/lib/python3.7/site-packages/environ/environ.py", line 123, in __call__
>     return self.get_value(var, cast=cast, default=default, parse_default=parse_default)
>   File "/home/fermentrack/venv/lib/python3.7/site-packages/environ/environ.py", line 277, in get_value
>     raise ImproperlyConfigured(error_msg)
> django.core.exceptions.ImproperlyConfigured: Set the MOUNT_DB_DIR environment variable
> Version/Source of fermentrack installed in image:
> ****************************************************************
> origin	https://github.com/mcinnes01/fermentrack.git (fetch)
> origin	https://github.com/mcinnes01/fermentrack.git (push)
> commit 34fc2b7736085e11eb87920f4679ba1c063785e2
> Author: iamandymcinnes <andy.mcinnes@kalibrate.com>
>     Added ability to configure data and db directories by environment variables
> ****************************************************************
> Starting circus deamon

I tried the example you provided moving the fermentrack root to /data, but it had an issue with the following:

The command '/bin/bash -o pipefail -c groupadd -g 2000 fermentrack && useradd -m -u 2001 -g fermentrack -d /data/fermentrack fermentrack' returned a non-zero code: 12

**Comment by thorrak** [comment]
Try making the /data directory first

**Comment by mcinnes01** [comment]
Ok so just done a little more tweaking around your example, but I am having issues setting permissions on the mount point for the fermentrack user. I guess as this is essentially the directories on the host trying to change permissions on may not be possible and then when we switch to the fermentrack user and try clone it doesn't have the correct permissions and so fails: https://github.com/mcinnes01/addon-fermentrack/blob/fe83cc57bec1c50f0be3d48b9801415c815ad990/fermentrack/Dockerfile#L52

This is the error I get: 

Step 12/50 : RUN git clone --single-branch --branch dev https://github.com/thorrak/fermentrack.git /data/fermentrack/fermentrack
 ---> Running in 986e27691215
Cloning into '/data/fermentrack/fermentrack'...
/data/fermentrack/fermentrack/.git: Permission denied

**Comment by mp-se** [comment]
Check what uid values you have in the container and docker host and make sure you have the same values. Check both user and group, if you have the same numbers it should work.

**Comment by mcinnes01** [comment]
Closing, to be able to create a home assistant addon I would need to be able to independently specify the location of data and db directories so I can specify them within the data mount provided by home assistant. Currently changing either the data mount path from home assistant or the db and data folders from fermentrack independently of the rest of fermentrack is not possible. Additionally I think some of the permission granted over said folders by fermentrack may not work with the mount directory from home assistant, as it is a bind mount not a volume and so changes to that directory affect the host. I.e. users would need to exist on the host too.
