### ISSUE TITLE
Not sure where else to put this: looks like HomebrewTalk, where the forums are, has gotten owned

### ISSUE THREAD

**Issue by jdkruzr** [thorrak/fermentrack#588]
http://www.homebrewtalk.com/showthread.php?t=586476

Guessing you guys know who to talk to about this.

**Comment by lbussy** [comment]
Not really sure what you mean - it looks fine to me.  What are you seeing?

**Comment by jdkruzr** [comment]
I suspect this probably isn't what they were going for :P 

![image](https://user-images.githubusercontent.com/618198/105740378-2845b980-5f07-11eb-999c-91234b144c42.png)

I just checked on my phone and got the same thing. Maybe there was a DNS poisoning attack if you're not seeing it?

**Comment by jdkruzr** [comment]
ah, I see the issue. it's not quite as bad as it could be. the link on the main Fermentrack website points to http instead of https. if you go to https you get the right site.
![image](https://user-images.githubusercontent.com/618198/105742493-925f5e00-5f09-11eb-851a-e7f35029dc14.png)

**Comment by lbussy** [comment]
Too funny!

**Comment by thorrak** [comment]
I actually don't get that issue - it properly redirects to https as expected. I'm wondering if maybe it's a MitM attack on your side?

**Comment by thorrak** [comment]
Out of curiousity, if you view source on that page, what domain is the image served from?

**Comment by jdkruzr** [comment]
so, it's stopped. loads normally and redirects normally now. 🤷🏻‍♂️

**Comment by lbussy** [comment]
Sunspots.
