### ISSUE TITLE
Installation fails and produces a 504 error on first access

### ISSUE THREAD

**Issue by CapitalOverlord** [thorrak/fermentrack#597]
I'm having an issue with installing Fermentrack on a fresh install of Raspbian. I have tried both Stretch along with Buster. Same issue with the webpage not loading. I have reinstalled multiple times. Fresh install each time. Ran the curl line for simplicity sake, but each time with the same outcome. I went through the log file and cant seem to find anything the jumps out. I did a search for "error" but no luck. Any ideas where to start? Or something that I am doing incorrectly? 

Fresh install with SSH along with wpa_suplicant. SHH to pi, update and upgrade. Password changed, allow VNC. Then curl install. Install completes.

**Comment by CapitalOverlord** [comment]
I also want to add I do have another Fermentrack running well so I don't think this is a network issue with the router. This is a new system I am building for my brother.

**Comment by thorrak** [comment]
Are you installing the docker version or the non-docker version?

**Comment by CapitalOverlord** [comment]
Of Raspbian?

**Comment by thorrak** [comment]
No - of Fermentrack —

which command exactly did you use to install?

**Comment by CapitalOverlord** [comment]
curl -L install.fermentrack.com | sudo bash

**Comment by thorrak** [comment]
Try `curl -L https://raw.githubusercontent.com/thorrak/fermentrack-tools/docker/automated_install/auto-install.sh | bash`

You may need to log out/back in midway through installation and re-run the command, but I tested it yesterday and it worked.

I don't know what is going on with installs like you're doing -- I did one successfully as of as recently as a month ago, yet someone else was complaining about them not working on homebrewtalk. If I get some time this weekend I'll try to figure out what is going on, but for now the docker installation should work.

**Comment by CapitalOverlord** [comment]
I did end up using that code you suggested, everything seemed to work fine and Fermentrack seems to have been installed properly. Thanks for your help. I appreciate it.

**Comment by CapitalOverlord** [comment]
I tried using the same commend after finishing up my build and am getting the error unable to install subversion.

**Comment by thorrak** [comment]
Can you copy and paste a log of exactly what you are seeing? That's a strange error.

**Comment by CapitalOverlord** [comment]
pi@************:~ $ curl -L https://raw.githubusercontent.com/thorrak/fermentrack-tools/docker/automated_install/auto-install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7236  100  7236    0     0  44944      0 --:--:-- --:--:-- --:--:-- 45225

<<>><<>><<>><<>><<>><<>><<>><<>><<>><<>><<>><<>><<>><<>><<>><<>><<>>
:: Checking user
::: This script was called without root privileges, which is recommended. The script will, however,
::: need root privileges periodically in order to install certain packages. Please be ready to
::: enter your password if prompted to allow installation to continue.
:::
:: Verifying free disk space...
::: Sufficent free space for installation
:: Installing dependencies using apt-get
::: installing git and build-essential.
::: (This may take a few minutes during which everything will be silent)
:::: All packages installed successfully.
:: Cloning fermentrack-tools repo from GitHub into /home/pi/fermentrack-tools
::: Existing instance of fermentrack-tools found at /home/pi/fermentrack-tools
::: Pulling from Git rather than re-cloning
:::: Pull from Git was successful
:: This script will now attempt to install Fermentrack using the script that has been created at
::: /home/pi/fermentrack-tools/install.sh
::: If the install script does not complete successfully, please relaunch the script above directly.
:::
:::: Launching Fermentrack installer.
::: Checking for Internet connection:
::: Internet connection Success!
::: Verifying free disk space...
::: Sufficient free disk space is available
::: Checking/installing Docker prerequisites using apt-get
*** ERROR: Unable to install subversion

**Comment by CapitalOverlord** [comment]
The install seemed to push through after a few reboots, along with a network reboot.

**Comment by CapitalOverlord** [comment]
I tried to run the alternate install on a pi zero w. And doesnt run. The original install posted on the website was doing the same 504 issue. Is it an issue with the pi zero and its power?

**Comment by thorrak** [comment]
The subversion issue is very strange - basically that means your Pi wasn't able to access either the network or the Raspberry Pi package repo. I'm glad you were able to get it up and running after a network reboot. 

The Pi Zeros are not supported, unfortunately. Although they are woefully underpowered, the real concern I have is that they happen to be a different processor architecture vs. the RPi 2/3/4/400 which creates issues with creating precompiled binaries. Although a bare-metal Fermentrack install should still work on an RPi Zero W, I would recommend upgrading to a 3 if possible.
