### ISSUE TITLE
Cached mDNS record not updated

### ISSUE THREAD

**Issue by jalim** [thorrak/fermentrack#598]
I'm not sure if this is a Fermentrack or Avahi issue but it seems that my temperature controller is correctly reporting its new IP address but fermentrack is still using the old one.

The results of debugging the connection show it is still trying to use the cached IP rather than the new one:

Test | Parameter | Pass/Fail | Output
-- | -- | -- | --
Device Status Test | active | Passed | Device active & managed by Circus
DNS Lookup Test | esp14510865.local | Passed | 192.168.8.60
Connection Test | esp14510865.local | Passed | Connected
Controller Response Test | esp14510865.local | Passed | b'N:{"v":"0.2.4","n":0,"c":"00000000","s":0,"y":0,"b":"e","l":"3"}'
Cached IP Test | 192.168.0.77 | Passed | Available
Connection Test | 192.168.0.77 | Failed | Unable to connect

**Comment by jalim** [comment]
I was able to manually update the cached IP via the Django admin panel but this doesn't seem intuitive.  It seems that when DNS Lookup returns a new IP that should replace the cached address.

**Comment by thorrak** [comment]
You shouldn't need to update the cached IP (though it should update automatically). I'll take a look to see what is going on.

Were you having issues actually reaching/using your controller?

**Comment by jalim** [comment]
Yes the connection failed, admittedly I was editing my network and changing the subnet that these devices were on so I expected a little bit of resetting but ideally mDNS should be able to cope with changes like this.

Interestingly, after manually updating the cached address in Django, the controller came online as expected and then a short time later seemed to reset its EEPROM and lost all sensor and pin allocations.  Haven't tried troubleshooting what caused this but was surprising.  I've managed to replicate this entire behaviour twice when changing subnet and updating the cached IP.

**Comment by thorrak** [comment]
I think that this is fixed with the BrewPi script refactoring that took place alongside #724 . If not, then it’s a networking issue up the stack which makes it a bit more difficult to fix. Going to tag this against the PR for now — if it reoccurs after that PR is merged, we can revisit.
