### ISSUE TITLE
iSpindel: Battery in dashboard and send battery in push (Brewerfriend)

### ISSUE THREAD

**Issue by mtrepanier** [thorrak/fermentrack#599]
Hello,

I noticed that you collect the battery info into the gravitypoint model for the iSpindel and that it's available in the settings of the iSpindel  as extra data.

It would be cool to have it available in the dashboard.

And extra, it would be cool to have it sent to BrewersFriend too. It's an optional data point that can be sent.  

Do you accept PR?  Maybe I can modify the code to send it to BF

https://docs.brewersfriend.com/api/stream

**Comment by thorrak** [comment]
Sure thing.

**Comment by thorrak** [comment]
I've added code to a new branch that handles sending iSpindel battery readings to Brewers Friend, but don't have an iSpindel here to test with. If you're willing to test this branch, I'd appreciate it.

To switch to the branch:
#. Log into fermentrack
#. Click the gear

1. Log into Fermentrack and click the gear in the upper right
2. Click "Django Admin Panel"
3. Under the "Constance" heading, click "Config"
4. Click the check box next to "ALLOW_GIT_BRANCH_SWITCHING" and click "Save" in the lower right corner
5. After the page reloads, make sure the message "Live settings updated successfully." appears at the top of the page. If it doesn't, you may need to click save more than once to get the settings change to take.
6. Click "View Site" at the top to go back to fermentrack, and click the gear in the upper right
7. Click "Update from GitHub"
8. At the bottom of the page, you should see a "Switch Branch" section, with a drop down menu. If you don't, repeat steps 1-5.
9. Select the "ispindel_battery" branch and click "Switch Branch"

After Fermentrack updates, it should now send your iSpindel's battery to Brewer's Friend. If it does, report back here and let me know, and I'll merge this change into dev.

**Comment by gieljnssns** [comment]
Can you also push it to generic push?

**Comment by thorrak** [comment]
> Can you also push it to generic push?

It should be pretty easy to add, but unlike the other push target types, "generic" by definition is leveraged by an unknown downstream consumer whose interface I know nothing about. My fear is that someone wrote a consumer which is incapable of gracefully handling additional keys beyond those provided today and which would crash as a result of this change. That said, I opened #600 to allow anyone who wants to comment -- If I don't hear any complaints in the next few weeks then I'll get this change added (and try to just add all the extras to the message for both Tilts and iSpindels).

**Comment by mtrepanier** [comment]
Thanks, I was about to start working on this.  But thanks!  I will test later today

**Comment by mtrepanier** [comment]
This is just perfect.  Thanks
<img width="548" alt="Screen Shot 2021-02-15 at 2 31 23 PM" src="https://user-images.githubusercontent.com/2464116/107986692-99bed800-6f9a-11eb-9c4b-cc367cb92848.png">

**Comment by thorrak** [comment]
Awesome - glad it worked!

This is now merged into the `dev` branch - Make sure to switch back to it whenever you have a moment. You can leave the "branch switching" flag set if you like (or change it back to save some screen space if you prefer!)

**Comment by mtrepanier** [comment]
I will keep the feature on, because I'm planning on adding the battery info in the gravity sensor dashboard page for the iSpindel too.  Thanks
