### ISSUE TITLE
Add battery (and other "extras") to Generic Push message

### ISSUE THREAD

**Issue by thorrak** [thorrak/fermentrack#600]
There was a request in a [comment on another issue](https://github.com/thorrak/fermentrack/issues/599#issuecomment-778910205_) to add iSpindel battery to the generic push target. I'm thinking it might make sense to add all of the "extras" for both iSpindel and Tilt sensors to the generic push payload (and then the consumer can decide what data he/she wants). That said, as the whole idea of the "generic" target is that I don't know what is consuming this data, I'm hesitant to make changes without providing ample time to comment/complain. 

Does anyone have any strong thoughts/opinions? For what it's worth, this would be adding keys to the message, so I'm hoping that anyone who wrote a consumer would discard extra keys (rather than crasing if they showed up).

**Comment by lbussy** [comment]
I've not heard of anyone using this with a commercial service which should be impacted. That leaves poorly-written local endpoints under the control of the end-user.  I think additional keys should be fine for what my opinion is worth.

**Comment by uSlackr** [comment]
Could there be a configuration to turn on/off fields?

\\Greg

**Comment by thorrak** [comment]
I mean, there _could_ but is there anyone out there that has an implementation that can't discard extra keys? 🤷

**Comment by lbussy** [comment]
If there is, you'll find it. :)

**Comment by uSlackr** [comment]
Doesn’t seem likely.

\\Greg

**Comment by rejeanc** [comment]
Brewfather, just added it : 

https://docs.brewfather.app/integrations/custom-stream
https://gitlab.com/warpkode/public/brewfather/-/issues/1011#notes

**Comment by thorrak** [comment]
@rejeanc - Thanks for mentioning that - I'll track the addition of battery to the Brewfather message in its own issue.
