### ISSUE TITLE
Add Battery to the Brewfather push message for iSpindel devices

### ISSUE THREAD

**Issue by thorrak** [thorrak/fermentrack#603]
Brewfather, just added it : 

https://docs.brewfather.app/integrations/custom-stream
https://gitlab.com/warpkode/public/brewfather/-/issues/1011#notes

_Originally posted by @rejeanc in https://github.com/thorrak/fermentrack/issues/600#issuecomment-782754756_

**Comment by thorrak** [comment]
@rejeanc - Do you use BrewFather push support in Fermentrack? If so, would you be willing to test this change?

**Comment by thorrak** [comment]
I've added code to a new branch that handles sending iSpindel battery readings to Brewfather, but don't have an iSpindel here to test with. If you're willing to test this branch, I'd appreciate it.

**To switch to the branch:**

1. Log into Fermentrack and click the gear in the upper right
2. Click "Django Admin Panel"
3. Under the "Constance" heading, click "Config"
4. Click the check box next to "ALLOW_GIT_BRANCH_SWITCHING" and click "Save" in the lower right corner
5. After the page reloads, make sure the message "Live settings updated successfully." appears at the top of the page. If it doesn't, you may need to click save more than once to get the settings change to take.
6. Click "View Site" at the top to go back to fermentrack, and click the gear in the upper right
7. Click "Update from GitHub"
8. At the bottom of the page, you should see a "Switch Branch" section, with a drop down menu. If you don't, repeat steps 1-5.
9. Select the "brewfather_battery" branch and click "Switch Branch"

After Fermentrack updates, it should now send your iSpindel's battery to Brewfather. If it does, report back here and let me know, and I'll merge this change into dev.

**Comment by rejeanc** [comment]
Did the update, not sure updated in brewfather yet, will post when it works.

Thanks.

**Comment by mp-se** [comment]
@thorrak I've put together a ispindel simulator (based on the tilt-sim) that you can use for testing iSpindel communication. You can find it here, https://github.com/mp-se/ispindel-sim. I kept the same command structure as the tilt-sim....

**Comment by rejeanc** [comment]
Hi,

I confirm I now see battery info in chart 👍 

Thanks!

**Comment by thorrak** [comment]
Thank you! I've merged this into Dev.

**Comment by rejeanc** [comment]
Hi, seems css is missing 

cd /home/fermentrack/fermentrack
cp app/static/css/dashboard_revised.css collected_static/css/

Thanks.

**Comment by thorrak** [comment]
Which page are you seeing as missing the CSS?

**Comment by rejeanc** [comment]
gravity sensor page, battery info is white on white, if copy as above it corrects.

**Comment by rejeanc** [comment]
![410FEE96-9629-4307-BDBF-B55BC3C362F1](https://user-images.githubusercontent.com/35567375/113531850-da4cd200-9597-11eb-8246-45c838f3bdbc.jpeg)

**Comment by thorrak** [comment]
Everything looks right in the code - It appears that the static files didn't collect properly in your installation. I'll keep an eye on this, but I don't think any changes are necessary to get this working at this time.
