### ISSUE TITLE
Temperatures reported as zero

### ISSUE THREAD

**Issue by zoroch** [thorrak/fermentrack#610]
Hello,
I have a problem with my fermentation fridge. I apologize if this is the wrong place to post the issue.
The issue is that oftenly, my temperature sensors (ds18b20) report a temperature of 0°C. It causes the software to stop heating or cooling.
 
![image](https://user-images.githubusercontent.com/80644355/111080684-eba63f80-84ff-11eb-9b25-babbdafce37f.png)
![image](https://user-images.githubusercontent.com/80644355/111080726-1c867480-8500-11eb-9f3f-400df6f2418f.png)
![image](https://user-images.githubusercontent.com/80644355/111080740-28723680-8500-11eb-89cd-5c1ec5f2503a.png)

Do you know what may cause an issue like this ?
My sensors cable length is no more than 2m, even less. I use a dedicated 5V power supply and don't use the parasite mode.
I don't think the issue is a bad sensor, because this bug touches every sensor (beer, room and fridge). But surprisingly it seems that the beer sensor is the most affected.

Thank you very much

**Comment by thorrak** [comment]
Unfortunately, this is definitely a hardware issue of some sort - let's try to figure out what is causing it.

What microcontroller & firmware are you using for your BrewPi firmware? (Classic BrewPi on Arduino, BrewPi-Remix on Arduino, BrewPi-ESP8266?)

What resistor value are you using for your OneWire Pullup? (2k2, 4k7, 10k, Other?)

What voltage are you powering your temp sensors with? (5v or 3v3?)

**Comment by zoroch** [comment]
I'm using the Wemos D1 mini (ESP-8266), running the latest firmware (I don't know how to check)
I think the Pullup resistor is a 2.2k. (I'm using this board : https://www.pcbs.io/board/16ae1eefeed65bace792770a7bbd9e09f8d6ba682905d999b3fe9e16d0117465)
The sensors are powered with 5V

**Comment by lbussy** [comment]
Do you have other sensors with which to test?

**Comment by zoroch** [comment]
Yes I do, I bought a pack of 5 sensors so they should be identical.
I tried switching the sensor used as beer of fridge, but it doesn't help

**Comment by lbussy** [comment]
What board are you using for the sensors?

**Comment by zoroch** [comment]
I use this board : https://www.pcbs.io/board/16ae1eefeed65bace792770a7bbd9e09f8d6ba682905d999b3fe9e16d0117465
Then I run the wire from the RJ45 jack to the sensors (not using an actual RJ45 cable)

**Comment by lbussy** [comment]
> Then I run the wire from the RJ45 jack to the sensors (not using an actual RJ45 cable)

I'd remove the sensor and make sure you get ~5.0VDC from the power to the ground, and ~3.3VDC from data to ground.

**Comment by zoroch** [comment]
Thanks, I'll check that tomorrow.
I saw in the logs that the 0°C readings are reported as "null". Is it possible to implement a rule in the software that ignores these readings ? It would "solve" my problem (not solving the real hardware issue).

**Comment by zoroch** [comment]
I'm reading 5.06 V from GND to V.
And 3.37V from DATA to GND, jumping to 3.16V every 5 seconds

**Comment by lbussy** [comment]
There's an outside chance that you have a sensor that doesn't like the higher voltage.  That's odd because [Maxim says](https://datasheets.maximintegrated.com/en/ds/DS18B20.pdf) 3.0 - 5.5 VDC, but Chinese knock-offs may be less agreeable.

There's a couple of ways to go:

* Voltage divider on the end of your cable
* Scab 3V3 to one of your unused pins on the RJ45 and use that for power

### Voltage Divider

Use a 4k7 and 2k2 resistor in series between the power and ground.  It should be Power -> 2k2 -> Sensor Power -> 4k7 -> ground.  In this picture, the (-) is ground, R1 is 2K2 and R2 is 4K7:
![voltage-divider-calculator-2](https://user-images.githubusercontent.com/9092188/111143979-73b63480-8554-11eb-9e8d-98ba3f3415fd.png)

### Scab in 3V3

You can pull 3V3 from the lower-left pin on the D1 (the corner closest to the RJ45) and connect that to one of the unused pins on the RJ45.  That would be 1, 2, 7, 8.  Using 8 (upper pin row closest to D1) may be safest as those are tiny pins, and only an unused and the Door pin would be very close to it.)

I'd be very interested to hear if this fixes it.  I can always add a selectable power header on the board, but I'd never come across a sensor that was not happier with 5V, especially given wire length losses.  @thorrak has, and he added a selector.

**Comment by zoroch** [comment]
These last hours, I've been rewiring all my sensors. Before I used quick connectors (wago) to connect all the sensors wire. So I thought that maybe the issue comes from here. Then I removed the quick connectors and soldered all the wires. The sensors are now connected with an RJ45 cable (1 pair for data/gnd, 1 pair for V+/gnd). Didn't fix the issue.
I replaced the beer sensor, didn't help.
I switched the sensor voltage from 5V to 3.3V (using the PCB's 3.3V dupont header), didn't fix the issue (although it doesn't happen so often)
![image](https://user-images.githubusercontent.com/80644355/111165758-b2251100-859f-11eb-88f3-4b80cb86f345.png)

**Comment by lbussy** [comment]
With 3V3 you may need a stronger pull-up.  I've found 2K2 to be effective.

**Comment by zoroch** [comment]
I think that I finally (after 6 months) found the culprit !

I noticed that sometimes my Wemos D1 mini disconnected, and the only way to regain connection is to reset the power. 
Probably some sort of malfunction with the power delivery.
Also, if you look in my first screen you can see that the errors are frequent when there is a need to cool or heat, but when the temperature is correct there are fewer errors (first half of the graph).

In the past, I rewired all the electronics to separate the high voltage components (relay, 5V power supply) and the low voltage components (pcb with wemos D1 mini).
After that, the D1 mini stopped disconnecting and for me the issue was solved.
However, after I tweaked the wires today the D1 mini started to randomly disconnect again.

So the issue has something to do with the the power supply or the relay board.
Maybe when there is a need to heat or cool, some voltage spikes occur and causes the D1 mini to shut down, and the sensor to report a "null" temperature.

I already tried replacing the relay board with SSRs yesterday, so it isn't because of the relay board.
The only possible explanation is a bad power supply.
Hense, I decided to leave my cheap 5V 2A PSU connected to the relay board, and power my D1 mini and the sensors with a separate PSU (some cheap power outlet with a USB port). 

It seems to be working now ! It's functioning for an hour without showing 0°C readings. 
![image](https://user-images.githubusercontent.com/80644355/111187210-18b42a00-85b4-11eb-8c22-283d6ec53890.png)
The heating has never been on so long !

I'll post tomorrow again to let it run some time and make sure that it solved the issue.

PS : I'm powering my DS18B20 with 5V again, as powering them with 3.3V didn't solve the issue

**Comment by lbussy** [comment]
That's Dave's classic answer:  The power supply.  I suppose working as an EE for so long, he's learned that's generally the culprit.

**Comment by zoroch** [comment]
Hi, just wanted to give a quick update.
Everything is sorted, no more temperature errors.
If something similar happen to you try to power the sensors with another power supply separated from the relay board.
