### ISSUE TITLE
Add Link to Root

### ISSUE THREAD

**Issue by lbussy** [thorrak/fermentrack#620]
When you open the Django admin, there is no (obvious) link to get back to the root.

**Comment by thorrak** [comment]
<img width="336" alt="Screen Shot 2021-03-24 at 6 22 57 PM" src="https://user-images.githubusercontent.com/2457900/112391287-0c278400-8cce-11eb-8739-ff230ad39148.png">

?

**Comment by lbussy** [comment]
![image](https://user-images.githubusercontent.com/9092188/112391447-ebf3c700-8cc5-11eb-816a-13d347442bed.png)

? back atcha :)

**Comment by thorrak** [comment]
That to me looks like you're already on the root. Unless you mean "add a link back to the site" in which case it's in the upper right?

**Comment by Garzlok** [comment]
I’m normally confused pretty easily, but where do you want to go? Now....I’m not ready to get into the philosophical debate on if these are obvious...but I tend to think that what is obvious is very relative.
![F063F2ED-9112-41E6-A69D-A988CC74EACF](https://user-images.githubusercontent.com/60665719/112407539-a5659300-8cec-11eb-8914-b0d1bcc46dcd.jpeg)

**Comment by thorrak** [comment]
> I’m normally confused pretty easily, but where do you want to go? Now....I’m not ready to get into the philosophical debate on if these are obvious...but I tend to think that what is obvious is very relative.
> ![F063F2ED-9112-41E6-A69D-A988CC74EACF](https://user-images.githubusercontent.com/60665719/112407539-a5659300-8cec-11eb-8914-b0d1bcc46dcd.jpeg)

If we ever meet in person, I'm buying you a beer. <3

**Comment by Garzlok** [comment]
> If we ever meet in person, I'm buying you a beer. <3

Pick-up the Uber tab, and will split the drinking tab! 🤣

**Comment by lbussy** [comment]
"Root" is "/" which is the website.  And I said "obvious" but that could also mean I have no business being in Django admin if I did't see that link. :)
