### ISSUE TITLE
Brewpi-script gets stuck intermittently

### ISSUE THREAD

**Issue by jaisoh** [thorrak/fermentrack#635]
For reasons unknown to me brewpi-script gets stuck sometimes and only rebooting the raspberry pi will help. I'm using ESP8266 controller through WiFi for the fermentation chamber and it has been working well so far.

Where to start debugging the issue? I looked at the logs but there is no clear root cause for brewpi-script getting stuck. The reason why I'm thinking the issues is with brewpi-script is that the web interface works and states that it cannot connect to brewpi-script.

Below is a snapshot from stderr log when the issue occured. I only restarted the raspberry pi so it would indicate there is no issues with the ESP controller?

> May 21 2021 14:32:16   Controller debug message: INFO MESSAGE 17: Positive peak detected:  20.1, estimated:  20.2. Previous heat estimator:  9.719, New heat estimator:  9.719.
 May 21 2021 14:49:37   Error: controller is not responding to new data requests. Exiting.
 May 21 2021 14:49:42   Refreshing dbConfig
 May 21 2021 14:49:42   Connection type WiFi selected.  Trying TCP serial (WiFi)
 May 21 2021 14:49:42   Connecting to BrewPi esp359988.local (via [IP]) on port 23
 May 21 2021 14:50:17   Unable to connect to BrewPi [IP] on port 23. Exiting.

**Comment by thorrak** [comment]
Although I hadn’t commented on it, this issue was the reason behind the refactoring in #724 . Once that is merged, this issue should be resolved.
