### ISSUE TITLE
Documentation around pin assignment is unclear

### ISSUE THREAD

**Issue by jjok** [thorrak/fermentrack#639]
Hi. I'm trying to set up a new ESP8266. I've flashed the firmware via the UI. Now, presumably, I need to assign the pins on it to the different functions that are available. There are two issues that I've come across:

1. With a NodeMCU, only 3 pins appear in the Available Devices section. I need at least 4 pins to do anything useful, right?
I also tried with a Wemos D1 Mini, but that only gave 2 pins. What's going on? Have I done something wrong? Are the devices faulty?
2. The Available Devices are listed like `Pin 16 ( D0 (Heat))`, `Pin 14 ( D5 (Cool))` and `Pin 13 ( D7 (Door))`. I'm not sure what the "Heat", "Cool" and "Door" mean here? Is that the suggested function that you should assign to it? I can assign those pins to those functions, but if I try and assign to a different type of function (eg Pin 13 to Chamber Temperature) I get the error message `Failed to write the configuration to the controller. If this continues, try resetting the EEPROM on the controller`. It seems that the interface is allowing me to assign a function that isn't possible, which doesn't seem right.
   
Thanks.

**Comment by jjok** [comment]
Is this the best place to get help with setting up the controllers? I can't find much information on the setup.

The README [here](https://github.com/thorrak/brewpi-esp8266) seems to suggest that maybe there's a default pin configuration, but maybe that's not the case when flashed via Fermentrack.

**Comment by jjok** [comment]
Aaahh! Progress made. You have to connect the temperature sensors in order for it to be able to detect them. Then you can assign it.

**Comment by uSlackr** [comment]
Did you find the docs?
Fermentrack — Fermentrack documentation<http://docs.fermentrack.com/en/master/>


\\Greg

**Comment by jjok** [comment]
Yes thanks. That was the first place I looked after UI didn't really give an explanation.

I think this is where it would be, if it was there. https://fermentrack.readthedocs.io/en/latest/controllers/controller_configuration.html

> 2. From the menu at the top with your device’s name, choose “Configure Sensors/Pins/Devices”
> 3. A screen will appear showing you the configuration status of your device. At a minimum, you need to have a heating pin, cooling pin, and chamber sensor set for your device to operate.
> 4. Configure each of the devices listed under “Available Devices” - so long as

That file doesn't seem to have any history, so I don't know what happened to the rest of that sentence.

**Comment by jjok** [comment]
I think it just needs a sentence or two adding to the UI of the Configure Sensors/Pins/Devices page to explain what's going on. I'll see if I can come up with something.
