### ISSUE TITLE
Tilt stopped work; setcap issue 

### ISSUE THREAD

**Issue by uSlackr** [thorrak/fermentrack#643]
My Tile hasn't logged the last two beers.  I tested the device and the app connects fine.  Fermentrack is reporting that setcap isn't set correctly.  
I ran getcap to display and they were there.
I ran `setcap -r /usr/bin/python3.7` to clear all caps; and
ran `sudo setcap cap_net_raw,cap_net_admin+eip /usr/bin/python3.7`

this appeared to fix the issue (I have a gravity reading now.

FT is still reporting setcap error.  When I run getcap, I see the settings are a bit different than what the script expects.
```
pi@raspi:~ $ getcap -v /usr/bin/python3.7
/usr/bin/python3.7
pi@raspi:~ $ sudo setcap cap_net_raw,cap_net_admin+eip /usr/bin/python3.7
pi@raspi:~ $ getcap -v /usr/bin/python3.7
/usr/bin/python3.7 = cap_net_admin,cap_net_raw+eip 
```
As you can see the +eip is attached to the net_raw instead of net_admin.  

Is this causing the erroneous report?

**Comment by NecroBrews** [comment]
I'm seeing the same issue on my side. 

Interestingly Fermentrack does occasionally recognise the Tilt and will log data - but it randomly disconnects.

**Comment by thorrak** [comment]
I've ended up removing this test as part of an upcoming release of Fermentrack that no longer targets non-containerized installs, as we have control (via the Dockerfile) of exactly what flags are set. Going to tag this as pending pull, and close once everything is merged to Master.
