### ISSUE TITLE
New ESP config tools from ESPhome/Home Assistant

### ISSUE THREAD

**Issue by thorrak** [thorrak/fermentrack#647]
### Discussed in https://github.com/thorrak/fermentrack/discussions/646

<div type='discussions-op-text'>

<sup>Originally posted by **uSlackr** June 18, 2021</sup>
This might be worth watching - easier path to device configuration & deployment:

https://www.home-assistant.io/blog/2021/06/16/power-up-your-esp-projects/</div>

**Comment by lbussy** [comment]
Yeah, I have one next to me I've been playing with.  It shows promise.  It's a different paradigm but we need to explore it across all of the projects.

**Comment by thorrak** [comment]
Wow, I completely forgot about this. This has been built! https://web.brewflasher.com/
