### ISSUE TITLE
Debugging / help

### ISSUE THREAD

**Issue by dbarrington** [thorrak/fermentrack#665]
Hi thorrak,

Happy new year, and thanks for all your work on this project.

I'm having a couple of issues getting my fermentrack working again after being away from the homebrew scene for awhile. 

I have an older setup based on fuzzewuzze's original build, and I have flashed the legacy 0.2.10 RevA onto the Arduino, with a success message.

I am having two, probably related issues.

1. Fermentrack does not seem to initiate the cooling relay, and just sits at Idling, even though the beer or fridge constant is set much lower.
![fermenter](https://user-images.githubusercontent.com/12245595/147893178-a8ba26db-a5f3-4d3f-bc62-ef87a439cb23.png)

2. After awhile, it seems to crash, and returns an error that it is running a very old version of BrewPi. Please upload a new version of BrewPi to your Arduino. I can't restart with the Restart Controller button under the device manager at this point, and need to restart it manually by powering the arduino off.

Sorry, this was a bit longer than intended. Can you give any advice on debugging this? 
Side note 1, This is running through a virtual box with linux mint, instead of raspberry pi, but I have previously not had an issue with this build.
Side note 2, I am planning on upgrading to a new esp8266 build, but I am really hoping to get this going so I can get a brew or two in before I get the upgraded version going.

**Comment by dbarrington** [comment]
Here is the full error text from dev-3-stderr.log:

 ```
Jan 03 2022 02:42:24   Refreshing dbConfig
 Jan 03 2022 02:42:24   Connection type Serial selected. Opening serial port.
 Jan 03 2022 02:42:24   Connected via serial to port /dev/ttyACM0
 Jan 03 2022 02:42:24   Notification: Script started, with no active beer being logged
 Jan 03 2022 02:42:34   Checking software version on controller... 
 Jan 03 2022 02:42:44   Warning: Cannot receive version number from controller. Your controller is either not programmed or running a very old version of BrewPi. Please upload a new version of BrewPi to your controller.
```

Additionally, the dashpanel is now displaying:
```
Cannot receive LCD text from Controller/Script
```

**Comment by thorrak** [comment]
> I have an older setup based on fuzzewuzze's original build, and I have flashed the legacy 0.2.10 RevA onto the Arduino, with a success message.
> 
> I am having two, probably related issues.
> 
> 1. Fermentrack does not seem to initiate the cooling relay, and just sits at Idling, even though the beer or fridge constant is set much lower.

Do you have a screen on the actual BrewPi hardware? If so, does it match what you see in Fermentrack (or - separately - are you actively seeing the timer tick up in Fermentrack)? 

Both the "LCD" display in Fermentrack and the control of the state of the relay are handled by the actual hardware - not Fermentrack - which would indicate a potential issue with either the hardware, hardware setup, or firmware. That said, let's try to debug --

On the device confguration/pin setup page, what do you see? (The page in Fermentrack with a bunch of icons)

> 2. After awhile, it seems to crash, and returns an error that it is running a very old version of BrewPi. Please upload a new version of BrewPi to your Arduino. I can't restart with the Restart Controller button under the device manager at this point, and need to restart it manually by powering the arduino off.
> 
> Sorry, this was a bit longer than intended. Can you give any advice on debugging this? Side note 1, This is running through a virtual box with linux mint, instead of raspberry pi, but I have previously not had an issue with this build. Side note 2, I am planning on upgrading to a new esp8266 build, but I am really hoping to get this going so I can get a brew or two in before I get the upgraded version going.

There could be a couple of sources of this issue. Again - do you have a screen on the BrewPi? If so, what does the screen show while disconnected from Fermentrack?

**Comment by dbarrington** [comment]
> Do you have a screen on the actual BrewPi hardware?  If so, does it match what you see in Fermentrack (or - separately - are you actively seeing the timer tick up in Fermentrack)?
No, there is not a screen. the "Idling for 00m00" does increase/tick up.

> On the device confguration/pin setup page, what do you see? (The page in Fermentrack with a bunch of icons)
With the error above, I get an error "Unable to reach brewpi-script. Try restarting the brewpi-script." With a restart, I get this:

**Comment by thorrak** [comment]
Try setting a heating pin, and see if that solves problem 1. I can't remember if - for the Arduino firmware - having it set is required (even if you don't hook up a heater).

Without a screen, we're slightly limited in how we can debug issue 2, but that's OK. What happens if you physically unplug & reconnect the Arduino. Does it start working again?

**Comment by dbarrington** [comment]
Thanks for the help so far!

> Try setting a heating pin, and see if that solves problem 1. I can't remember if - for the Arduino firmware - having it set is required (even if you don't hook up a heater).

I gave this a try just now, and reset the temps for the beer constant and fridge constant, but it still appears to be stuck on idling.

I have had trouble with this relay. The heating stopped working on it (which is why I had stopped using it and did not have it assigned).


> Without a screen, we're slightly limited in how we can debug issue 2, but that's OK. What happens if you physically unplug & reconnect the Arduino. Does it start working again?

Yes it does start working again.

**Comment by dbarrington** [comment]
Ok, following on your suspicion it was hardware related, I'm pretty sure I must have messed up on the wiring to the relay on the arduino. 

I plugged in a spare uno. Everything started up, got sensors assigned and the relay was triggering correctly. 

I then rewired the relay to try to get the heating relay to work. I used this diagram:
https://dotps1.github.io/img/2018-01-22-brewing-your-own-brewpi/schematic.jpg
This caused the 2nd arduino to die! :(

I have found the brewpi remix, which I will rework the parts with instead. Obviously a wiring issue on my part, then hardware. Cursing my stupidity today. I now have two uno bricks.

**Comment by thorrak** [comment]
> Ok, following on your suspicion it was hardware related, I'm pretty sure I must have messed up on the wiring to the relay on the arduino.
> 
> I plugged in a spare uno. Everything started up, got sensors assigned and the relay was triggering correctly.
> 
> I then rewired the relay to try to get the heating relay to work. I used this diagram: https://dotps1.github.io/img/2018-01-22-brewing-your-own-brewpi/schematic.jpg This caused the 2nd arduino to die! :(

What do you mean by "die"? Continue to sit at idling forever? I believe that's a firmware bug, but unfortunately don't have any hardware here to test with to be able to tell you for certain. (That said - see my note below about BrewPi Remix)

Looking at that wiring diagram, unless there is something wrong with the relay, nothing should end up frying the Arduino. The only reason I could see the relay causing issues is if the [JD-VCC jumper](https://electronics.stackexchange.com/questions/505318/how-to-properly-use-a-relay-module-with-jd-vcc-from-arduino-raspberry) was bridging the wrong two pins. 

> I have found the brewpi remix, which I will rework the parts with instead. Obviously a wiring issue on my part, then hardware. Cursing my stupidity today. I now have two uno bricks.

BrewPi-Remix is @lbussy 's project, and consists of two main components -- replacement arduino firmware, and a replacement web interface. The replacement [firmware](https://github.com/brewpi-remix/brewpi-firmware-rmx) is not only compatible with Fermentrack, but - I believe - [pin compatible](http://www.brewpiremix.com/brewpi-hardware/) with Fuzzewuzze's firmware port. That is: You may be able to just flash the firmware and have it start working.

This firmware is available through the firmware flash interface of Fermentrack as "BrewPi Remix" - You can use either the "RevC" or "I2C" variants and likely be fine (though RevC is most similar to what Fuzzewuzze published). Definitely worth a try if you think the hardware isn't functioning as expected!

**Comment by lbussy** [comment]
I just want to be extra careful to point out a significant item:  You said Rev A above, and we are talking about RevC.  Rev A was used for the older shield I believe and the pinouts are different.  If you are not using a shield anyway, I recommend using the I2C variant.  It is _mostly_ compatible with Rev C with the exception that it uses A0 for the OneWire.  The advantage to this variant is you can easily plug in an LCD with four wires compared to needing a pretty complicated shield with RevC.

Here is a post in the support thread for the wiring diagram:

https://www.homebrewtalk.com/threads/brewpi-remix-%E2%80%93-what%E2%80%99s-old-is-new-again.687633/page-9#post-9217104

**Comment by dbarrington** [comment]
Hello, apologies for the delay here, and thanks to the both of you for your help. 

The JD-VCC jumper looks fine.

I am able to reflash both of my arduinos, so I guess not dead after all. Honestly I think I needed a break to get fresh eyes on the problem! Sorry to give such scattered info! 🤣 🐙 

Following @lbussy's note, I flashed to Rev C, it was incorrectly on Rev A. The idle issues are gone now, and it is triggering cooling periodically. I am going to reflash to the I2C variant, and I've ordered a couple of the 2004 I2C LCD from aliexpress, but it will take a month or so to get to New Zealand. 

It does still periodically appear to crash. I did some testing over the course of the day today. Hopefully it will give a few insights.
It was set to around 55f, and was keeping solid on that temp for a number of hours. A few hours later rechecked and saw the "Cannot receive LCD text from Controller/Script" error. I unplugged the USB and plugged it back in, and the restarted. The temp at this point was around 65f.

**Comment by lbussy** [comment]
There are logs.  Use the ❓ icon and you can view the logs there. I expect it would be called something obvious, but I don't have a device attached right now to check.  If the controller crashes, you should be able to see something.

**Comment by dbarrington** [comment]
Progress!

I was able to find the logs under /home/fermentrack/fermentrack/log
Here is the crash from today:

```Jan 06 2022 19:41:16   Controller debug message: INFO MESSAGE 18: Negative peak detected:  55.8, estimated:  55.0. Previous cool estimator:  5.719, New cool estimator:  4.680.
 Jan 06 2022 20:28:34   Controller debug message: INFO MESSAGE 18: Negative peak detected:  54.8, estimated:  55.0. Previous cool estimator:  4.680, New cool estimator:  4.680.
 Jan 06 2022 21:12:23   Serial Error: Write timeout)
 Jan 06 2022 21:12:33   Serial Error: Write timeout)
 Jan 06 2022 21:12:43   Serial Error: Write timeout)
 Jan 06 2022 21:12:55   Serial Error: Write timeout)
 Jan 06 2022 21:13:05   Serial Error: Write timeout)
 Jan 06 2022 21:13:15   Serial Error: Write timeout)
 Jan 06 2022 21:13:23   Serial Error: Write timeout)
 Jan 06 2022 21:13:23   Error: controller is not responding to new data requests. Exiting.
 Jan 06 2022 21:13:28   Refreshing dbConfig
 Jan 06 2022 21:13:28   Connection type Serial selected. Opening serial port.
 Jan 06 2022 21:13:28   Connected via serial to port /dev/ttyACM0
 Jan 06 2022 21:13:28   Notification: Script started, with no active beer being logged
 Jan 06 2022 21:13:38   Checking software version on controller...
 Jan 06 2022 21:13:48   Warning: Cannot receive version number from controller. Your controller is either not programmed or running a very old version of BrewPi. Please upload a new version of BrewPi to your controller.
 Jan 06 2022 21:14:23   Refreshing dbConfig
 Jan 06 2022 21:14:23   Connection type Serial selected. Opening serial port.
 Jan 06 2022 21:14:23   Connected via serial to port /dev/ttyACM0
 Jan 06 2022 21:14:23   Notification: Script started, with no active beer being logged
 Jan 06 2022 21:14:33   Checking software version on controller...
 Jan 06 2022 21:14:43   Warning: Cannot receive version number from controller. Your controller is either not programmed or running a very old version of BrewPi. Please upload a new version of BrewPi to your controller.
 Jan 06 2022 21:15:18   Refreshing dbConfig
 Jan 06 2022 21:15:18   Connection type Serial selected. Opening serial port.
 Jan 06 2022 21:15:18   Connected via serial to port /dev/ttyACM0
 Jan 06 2022 21:15:18   Notification: Script started, with no active beer being logged
 Jan 06 2022 21:15:28   Checking software version on controller...
 Jan 06 2022 21:15:38   Warning: Cannot receive version number from controller. Your controller is either not programmed or running a very old version of BrewPi. Please upload a new version of BrewPi to your controller.
 Jan 06 2022 21:16:13   Refreshing dbConfig
 Jan 06 2022 21:16:13   Connection type Serial selected. Opening serial port.
 Jan 06 2022 21:16:13   Connected via serial to port /dev/ttyACM0
 Jan 06 2022 21:16:13   Notification: Script started, with no active beer being logged
 Jan 06 2022 21:16:23   Checking software version on controller...
 Jan 06 2022 21:16:33   Warning: Cannot receive version number from controller. Your controller is either not programmed or running a very old version of BrewPi. Please upload a new version of BrewPi to your controller.
 Jan 06 2022 21:17:08   Refreshing dbConfig
--- etc ---
```

**Comment by lbussy** [comment]
It looks like the reconnection doesn't work - I'd guess because the original thread doesn't stop. @thorrak does that seem likely?

**Comment by dbarrington** [comment]
Just a mini update here. I have installed a new version of Raspbian, Fermentrack and reflashed the arduino with BrewPi Remix - 0.2.13 - - RevC. I'm hoping that whatever issues were going on are now resolved. I will let it run for a day or two controlling the temp and see if it is stable, and report back. At least I am getting a slightly better understanding of how the software works!

Thanks to you both for your time/help. 🥂

**Comment by dbarrington** [comment]
Well it only got half an hour in last night and received the same error again. :(

Is it possible for USB cables or USB ports to be an issue here? 

Should the brewpi continue to regulate the temperature even if Fermentrack can't access it?

Any other logs I can check? 


```
Jan 09 2022 09:00:18   Notification: Started logging for beer 'Test beer'.
 Jan 09 2022 09:01:37   Refreshing dbConfig
 Jan 09 2022 09:01:37   Notification: Beer temperature set to 58.0 degrees in web interface
 Jan 09 2022 09:01:38   Controller debug message: INFO MESSAGE 12: Received new setting: mode = b
 Jan 09 2022 09:01:38   Controller debug message: INFO MESSAGE 12: Received new setting: beerSet = 58.0
 Jan 09 2022 09:35:48   Serial Error: Write timeout)
 Jan 09 2022 09:35:53   Serial Error: Write timeout)
 Jan 09 2022 09:36:04   Error: controller is not responding to new data requests. Exiting.
 Jan 09 2022 09:36:06   Refreshing dbConfig
 Jan 09 2022 09:36:06   Connection type Serial selected. Opening serial port.
 Jan 09 2022 09:36:06   Connected via serial to port /dev/ttyACM0
 Jan 09 2022 09:36:06   Notification: Script started for beer 'Test beer'
 Jan 09 2022 09:36:16   Checking software version on controller... 
 Jan 09 2022 09:36:26   Warning: Cannot receive version number from controller. Your controller is either not programmed or running a very old version of BrewPi. Please upload a new version of BrewPi to your controller.
```

**Comment by dbarrington** [comment]
I was able to get it running smoothly, finally. 

Here are the steps that worked.

1. Replaced relay module and Arduino. 
2. Click the 'Update/Install Missing Python Packages'
3. Removed all devices from Fermentrack, and readded 

No issues since. 👍

**Comment by lbussy** [comment]
Well, it was a nuclear option but I'm glad it worked.
