### ISSUE TITLE
AttributeError at /gravity/sensor/#/

### ISSUE THREAD

**Issue by StodgyWaif** [thorrak/fermentrack#673]
Hello. I recently installed Fermentrack on Ubuntu and am in the process of setting up my iSpindels on it.
I noticed the interface said there was an update available so I installed it.
I'm currently on the 3/30/22 version
When I try to click any of the gravity sensors I get this error page:

```
AttributeError at /gravity/sensor/4/
'NoneType' object has no attribute 'column_headers_to_graph_string'
Request Method:	GET
Request URL:	http://192.168.1.12/gravity/sensor/4/
Django Version:	3.0.14
Exception Type:	AttributeError
Exception Value:	
'NoneType' object has no attribute 'column_headers_to_graph_string'
Exception Location:	/app/gravity/views.py in gravity_dashboard, line 220
Python Executable:	/usr/local/bin/python
Python Version:	3.9.9
Python Path:	
['/usr/local/bin',
 '/home/django/.local/lib/python3.9/site-packages/git/ext/gitdb',
 '/app',
 '/usr/local/lib/python39.zip',
 '/usr/local/lib/python3.9',
 '/usr/local/lib/python3.9/lib-dynload',
 '/home/django/.local/lib/python3.9/site-packages',
 '/usr/local/lib/python3.9/site-packages',
 '.',
 '/usr/local/lib/python3.9/site-packages/gitdb/ext/smmap']
Server time:	Thu, 31 Mar 2022 20:01:33 +0000
```

There is additional info after this as well if it's needed.
I've tried rebooting the server but the error is the same.
Thanks.

EDIT:
I was able to fix it by switching the "Update preference" option to "Only upgrade when updates are officially released" and then upgrading it again.

**Comment by thorrak** [comment]
This actually is a bug in the dev code I released yesterday. Reopening this to track (though I'm about to push a fix).
