### ISSUE TITLE
RAPT Pill support

### ISSUE THREAD

**Issue by svestenik** [thorrak/fermentrack#674]
Hello,

any options or plans for RAPT Pill hydrometer support ?

**Comment by thorrak** [comment]
I actually haven't heard of this before. 

Is this available in the US? Do you have a link to the manufacturer? I can reach out to them to see what they offer and if this is something I could add.

**Comment by svestenik** [comment]
This one:

https://www.kegland.com.au/rapt-pill-hydrometer-thermometer-wifi-bluetooth.html

**Comment by lbussy** [comment]
The device currently only speaks to their cloud.  While they do have webhooks, Fermentrack (and BrewPi) are not open to the Internet and therefore cannot receive those.

I've spoken to their developers via email and while they don't yet have BLE available, they plan it for a future release.  At that point consuming the beacon would be fairly simple.

**Comment by Frits1980** [comment]
I've just got this device and it currently supports BLE. Don't know how that would work from a development point of view though.

**Comment by Frits1980** [comment]
They also have an API to get the telemetry data from. That way you can keep Fermentrack local behind your firewall. https://api.rapt.io/index.html

**Comment by thorrak** [comment]
Do they have local, Bluetooth support? 

I’m not a huge fan of cloud-locked brewing equipment ever since the Beer Bug.

**Comment by Frits1980** [comment]
Unfortunately no. The Bluetooth does not transmit a visible access point. According to the manual it will only connect to other RAPT devices from Kegland. To be honest I think the API is the most viable way of connecting to it. I don't know what the beer bug is. Just starting with this.

**Comment by thorrak** [comment]
The Beer Bug was a digital gravity sensor back in 2015 (or thereabouts) that used a weight suspended in your beer to measure fermentation. As the beer fermented the weight changed, which was being measured by a load cell. It connected to WiFi and sent gravity measurements to their cloud. 

Engineering concerns aside, the device was $250, and could only be set up/used with their cloud. When the company went under in 2016, I (and everyone else who bought one) ended up with a very expensive paperweight. 

This is a large part of why I love the Tilt — it is completely open, hence why I was able to build TiltBridge. 

I’ll reach out to the KegLand guys and see if they have any kind of documentation on the Bluetooth broadcasts.

**Comment by Frits1980** [comment]
Thank you if you would consider this. And thank you for explaining the beer bug to me. I guess the Rapt Pill is no different then the beer bug, but Kegland might be more reliable. For me the price difference (Pill 60 USD and Tilt 150 USD) is the reason I'll go for the Pill. I can't go for the iSpindel because you can't use these under pressure. And since I plan to build 4 chambers I need to have 4 Pills.
I can and will provide you a Pill if you need one for development. Just say so.
Also, I would like to buy you a beer for all the good work you and Stone do on this project. Is that possible?

**Comment by uSlackr** [comment]
I used a Tilt under pressure with no appreciable deviation in reported SG.  You typically ferment under so little pressure (< 1 bar) it will have little effect. I suspect the iSpindel would do likewise.

**Comment by Frits1980** [comment]
Multiple websites told me that an iSpindel is not capable of handling pressure. Maybe it leaks, maybe the readings are wrong. I'm not convinced it could handle the pressure.

**Comment by thorrak** [comment]
At this point, absent hardware to test with and an open API, I'm not likely to build RAPT Pill support into Fermentrack. Happy to revisit this if something changes in the future.

**Comment by Frits1980** [comment]
Ok, i think of abandon fermentrack anyway. Just because it has no development what so ever. And after a reaction like this just more reason to. Have a good one.

**Comment by thorrak** [comment]
Although I disagree that there has been [no development](https://github.com/thorrak/fermentrack/pull/724), I completely understand if Fermentrack is not the right software package for your needs given the lack of RAPT Pill support. As I said, if I had hardware (and if Kegland had an open API) things might be different -- but absent those two things, developing support would end up as an exercise in frustration.

Pull requests are always welcome, however, if anyone who has the hardware (and knows the API) is interested in building this out!

**Comment by Frits1980** [comment]
https://api.rapt.io/index.html

But I'm no programmer.

**Comment by lbussy** [comment]
> But I'm no programmer.

You're right.  If you were, you would understand the difference between an Open API for the device and an Open API for their cloud.  If Kegland shuts down that cloud, your connection stops as well.  This API is not a connection to/from your device; it is to/from their Cloud API.

**Comment by Frits1980** [comment]
You all think only one way. Assuming their cloud is going offline one day. But not all companies are the same. Kegland is big and has a lot depending on their cloud. If you keep assuming companies are going to go offline one day you would be better off not using the internet at all. We are now communicating on github, what if github went down. Being so sceptical about companies is keeping you from innovating. But that's your loss. I already have my solution without fermentrack.

**Comment by thorrak** [comment]
Noted. As this conversation is no longer productive, I have restricted your ability to reply. For anyone else interested in Rapt support, the offer above still remains.

**Comment by thorrak** [comment]
And for what it’s worth, I own raptbridge.com. Just saying, @Kegland

**Comment by greyghostbrewery** [comment]
> And for what it’s worth, I own raptbridge.com. Just saying, @KegLand ;)

You don't own domain names, you effectively lease them for a period of time. Also, why would having a domain name be of interest?

**Comment by thorrak** [comment]
Apologies - absent context, you're right, that statement doesn't make sense. I created the [TiltBridge](https://www.tiltbridge.com/) which is an open source bluetooth-to-wifi bridge for the Tilt Hydrometer. If Kegland was to open up the Bluetooth API for their device, I'd be interested in building the same for the RAPT Pill.

**Comment by plsecker** [comment]
Definitely keen to see it added, love Tiltbridge.  https://github.com/kbaggen/SPINDELMATE detects the BLE so seems a good stating point.

**Comment by uSlackr** [comment]
> Multiple websites told me that an iSpindel is not capable of handling pressure. Maybe it leaks, maybe the readings are wrong. I'm not convinced it could handle the pressure.

Updating my previous comment - I've now used the Tilt under 17 psi for more than 2 weeks with no issues.  (Wound up with a nice clean pilsner in the process)

**Comment by lbussy** [comment]
I have used an iSpindel many times with no issues.  Those containers are meant to handle quite a bit of pressure.  It's always possible for someone to not get it tight, or for the seal to deteriorate over time, but they cost pennies, and a person should not use a suspect one.

As far as the Home Assistant integration - this might be a good starting point, but my lack of HASS skills (even though I am implementing HASS support in my project with the help of @mp-se) prevents me from deciphering that before coffee.

**Comment by k-w-1** [comment]
> And for what it’s worth, I own raptbridge.com. Just saying, @KegLand ;)
 
~~FWIW, the pill is built around an ESP32, so it would be trivial to write custom firmware (although IDK how much faffery would be required to dial in the correct angle-to-SG calcs et al). HW has already been documented, e.g.: https://github.com/BestEnemies/pill~~

~~I'm probably going to go down this rabbit hole eventually, will find my way back here and report findings.~~

~~If anyone else who already has a pill is interested in sniffing around the BLE stuff, try something like [nRF Connect](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp) to see what it's putting out.~~

Hah, @plsecker already found the start of the breadcrumb trail. Looks like all the heavy lifting has already been done: https://github.com/sairon/rapt-ble
