### ISSUE TITLE
Migrate to a docker based install

### ISSUE THREAD

**Issue by gieljnssns** [thorrak/fermentrack#685]
I've triggered an update from fermentrack now it asked me to migrate to a docker based install, how can I do this?
<img width="1147" alt="Schermafbeelding 2022-04-07 om 13 24 36" src="https://user-images.githubusercontent.com/17234951/162188175-57fcb061-349e-4dc5-9fa1-3c8bf8d78c89.png">

When I click on `migrate to a docker-based installation` I can not find a way to migrate, only fresh install.

**Comment by thorrak** [comment]
The long version of instructions is coming shortly, but the short version for now:

1. Back up your current installation (Gear > bottom of page > create backup, let it finish, then download the .tar.xz file)
2. Install the new, docker based Fermentrack — ideally on a separate Pi or SD card (but you can install on the same Pi but on a different port if you need, in a pinch, but you’ll need to uninstall the old Fermentrack when you’re done)
3. Restore from your backup in the new, docker-based Fermentrack 
4. Check that everything is as you want (you will need to re-set sure wide settings) and decommission your old installation

**Comment by gieljnssns** [comment]
Thanks for your fast response.
I tried to add a backup 2 times, but 
<img width="411" alt="Schermafbeelding 2022-04-07 om 13 46 53" src="https://user-images.githubusercontent.com/17234951/162191718-f41624b1-734f-479b-a244-a68e9e76ecc8.png">

**Comment by thorrak** [comment]
> Thanks for your fast response.
> I tried to add a backup 2 times, but
> <img alt="Schermafbeelding 2022-04-07 om 13 46 53" width="411" src="https://user-images.githubusercontent.com/17234951/162191718-f41624b1-734f-479b-a244-a68e9e76ecc8.png">

Let it do it’s thing. Backups can take awhile for some reason. Eventually it will show up in the list.

**Comment by gieljnssns** [comment]
You are right, now it is there...
If I find some time I will try the migration later today or tomorrow

**Comment by gieljnssns** [comment]
All push targets are in the backup and will still work with docker version?
<img width="1165" alt="Schermafbeelding 2022-04-07 om 13 57 39" src="https://user-images.githubusercontent.com/17234951/162193424-cb52208d-ad3e-446f-b574-f994cd348d21.png">

All devices (esp) and gravity sensors (ispindel) stil work after backup?

**Comment by thorrak** [comment]
Yep, they should. The only thing not included are Constance settings (e.g. brewery name, dark mode. 

No rush on updating. I’m not going to push out the next version in a way that will conflict with this version for at least a few weeks.

**Comment by gieljnssns** [comment]
> The long version of instructions is coming shortly

Any update on this? I haven't made the switch yet.

i'm planning to make a second chamber and i don't know if it is the best to first migrate to docker or not

**Comment by gieljnssns** [comment]
I did the change. 
I installed fermentrack docker on another rpi. And restored a backup. 👍🏻
