### ISSUE TITLE
NGINX install error and 502 Bad Gateway

### ISSUE THREAD

**Issue by doubleAbrew** [thorrak/fermentrack#695]
I recently had some updates go through (primarily updating to Python 3.9.7) and I'm now getting a 502 Bad Gateway when trying to access Fermentrack. I believed I have traced it to an installation error with NGINX as shown by these results:

```
Traceback (most recent call last):
  File "/usr/bin/apt-listchanges", line 30, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'
Setting up nginx-full (1.14.2-2+deb10u4) ...
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
invoke-rc.d: initscript nginx, action "start" failed.
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2022-10-04 14:11:35 CDT; 60ms ago
     Docs: man:nginx(8)
  Process: 3077 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
  Process: 3078 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=1/FAILURE)

Oct 04 14:11:34 raspberrypi nginx[3078]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
Oct 04 14:11:34 raspberrypi nginx[3078]: nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
Oct 04 14:11:34 raspberrypi nginx[3078]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
Oct 04 14:11:34 raspberrypi nginx[3078]: nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
Oct 04 14:11:35 raspberrypi nginx[3078]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
Oct 04 14:11:35 raspberrypi nginx[3078]: nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
Oct 04 14:11:35 raspberrypi nginx[3078]: nginx: [emerg] still could not bind()
Oct 04 14:11:35 raspberrypi systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Oct 04 14:11:35 raspberrypi systemd[1]: nginx.service: Failed with result 'exit-code'.
Oct 04 14:11:35 raspberrypi systemd[1]: Failed to start A high performance web server and a reverse proxy server.
dpkg: error processing package nginx-full (--configure):
 installed nginx-full package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of nginx:
 nginx depends on nginx-full (<< 1.14.2-2+deb10u4.1~) | nginx-light (<< 1.14.2-2+deb10u4.1~) | nginx-extras (<< 1.14.2-2+deb10u4.1~); however:
  Package nginx-full is not configured yet.
  Package nginx-light is not installed.
  Package nginx-extras is not installed.
 nginx depends on nginx-full (>= 1.14.2-2+deb10u4) | nginx-light (>= 1.14.2-2+deb10u4) | nginx-extras (>= 1.14.2-2+deb10u4); however:
  Package nginx-full is not configured yet.
  Package nginx-light is not installed.
  Package nginx-extras is not installed.

dpkg: error processing package nginx (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 nginx-full
 nginx
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

I don't really know where to go from here. I tried to remove NGINX then reinstall, but it returned the same output when trying to uninstall. Any help for this NOOB is greatly appreciated.

**Comment by doubleAbrew** [comment]
I was able to resolve the apt_pkg issue I believe and now I get a 

“Welcome to nginx!

If you see this page, the nginx web server is successfully installed and working. Further configuration is required.”

**Comment by thorrak** [comment]
Are you using the containerized version of Fermentrack? If so, just reinstall the container and you should be good.

**Comment by doubleAbrew** [comment]
> Are you using the containerized version of Fermentrack? If so, just reinstall the container and you should be good.

Not sure. How can I tell, and if so, how to do reinstall the container?

**Comment by thorrak** [comment]
Yeah - you’re almost certainly using the non-containerized version then. 

Do you have a backup of your data (or do you not care about the data that you had in Fermentrack previously)? If so, then it should be pretty easy to migrate. If not, we’ll need to figure out a fix for your existing install first.

**Comment by doubleAbrew** [comment]
UPDATE: Still can't get past Redis needing port 6379 which is currently being used by Redis. 

`pi@raspberrypi:~ $ sudo lsof -t -i:6379
1519
pi@raspberrypi:~ $ ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 22:25 ?        00:00:06 /sbin/init splash
root         2     0  0 22:25 ?        00:00:00 [kthreadd]
root         3     2  0 22:25 ?        00:00:00 [rcu_gp]
root         4     2  0 22:25 ?        00:00:00 [rcu_par_gp]
root         8     2  0 22:25 ?        00:00:00 [mm_percpu_wq]
root         9     2  0 22:25 ?        00:00:00 [rcu_tasks_rude_]
root        10     2  0 22:25 ?        00:00:00 [rcu_tasks_trace]
root        11     2  0 22:25 ?        00:00:01 [ksoftirqd/0]
root        12     2  0 22:25 ?        00:00:03 [rcu_sched]
root        13     2  0 22:25 ?        00:00:00 [migration/0]
root        14     2  0 22:25 ?        00:00:00 [cpuhp/0]
root        15     2  0 22:25 ?        00:00:00 [cpuhp/1]
root        16     2  0 22:25 ?        00:00:00 [migration/1]
root        17     2  0 22:25 ?        00:00:00 [ksoftirqd/1]
root        20     2  0 22:25 ?        00:00:00 [cpuhp/2]
root        21     2  0 22:25 ?        00:00:00 [migration/2]
root        22     2  0 22:25 ?        00:00:00 [ksoftirqd/2]
root        25     2  0 22:25 ?        00:00:00 [cpuhp/3]
root        26     2  0 22:25 ?        00:00:00 [migration/3]
root        27     2  0 22:25 ?        00:00:00 [ksoftirqd/3]
root        30     2  0 22:25 ?        00:00:00 [kdevtmpfs]
root        31     2  0 22:25 ?        00:00:00 [netns]
root        34     2  0 22:25 ?        00:00:00 [kauditd]
root        36     2  0 22:25 ?        00:00:00 [khungtaskd]
root        37     2  0 22:25 ?        00:00:00 [oom_reaper]
root        38     2  0 22:25 ?        00:00:00 [writeback]
root        39     2  0 22:25 ?        00:00:01 [kcompactd0]
root        57     2  0 22:25 ?        00:00:00 [kblockd]
root        58     2  0 22:25 ?        00:00:00 [blkcg_punt_bio]
root        59     2  0 22:25 ?        00:00:00 [watchdogd]
root        60     2  0 22:25 ?        00:00:00 [kworker/2:1-cgroup_destroy]
root        62     2  0 22:25 ?        00:00:00 [rpciod]
root        63     2  0 22:25 ?        00:00:00 [kworker/u9:0-hci0]
root        64     2  0 22:25 ?        00:00:00 [xprtiod]
root        65     2  0 22:25 ?        00:00:05 [kswapd0]
root        66     2  0 22:25 ?        00:00:00 [nfsiod]
root        67     2  0 22:25 ?        00:00:00 [kworker/3:1-events]
root        69     2  0 22:25 ?        00:00:00 [iscsi_eh]
root        70     2  0 22:25 ?        00:00:00 [iscsi_destroy]
root        71     2  0 22:25 ?        00:00:00 [dwc_otg]
root        72     2  0 22:25 ?        00:00:00 [DWC Notificatio]
root        73     2  0 22:25 ?        00:00:07 [vchiq-slot/0]
root        74     2  0 22:25 ?        00:00:02 [vchiq-recy/0]
root        75     2  0 22:25 ?        00:00:00 [vchiq-sync/0]
root        76     2  0 22:25 ?        00:00:00 [zswap-shrink]
root        82     2  0 22:25 ?        00:00:00 [mmc_complete]
root        83     2  0 22:25 ?        00:00:01 [kworker/1:1H-kblockd]
root        85     2  0 22:25 ?        00:00:00 [jbd2/mmcblk0p2-]
root        86     2  0 22:25 ?        00:00:00 [ext4-rsv-conver]
root        88     2  0 22:25 ?        00:00:00 [ipv6_addrconf]
root        89     2  0 22:25 ?        00:00:00 [kworker/2:2-events]
root        93     2  0 22:25 ?        00:00:01 [kworker/3:2H-kblockd]
root       117     1  0 22:25 ?        00:00:01 /lib/systemd/systemd-journald
root       136     2  0 22:25 ?        00:00:07 [kworker/u8:2-events_unbound]
root       140     2  0 22:25 ?        00:00:00 [irq/199-usb-001]
root       153     1  0 22:25 ?        00:00:01 /lib/systemd/systemd-udevd
root       176     2  0 22:25 ?        00:00:00 [vchiq-keep/0]
root       177     2  0 22:25 ?        00:00:00 [SMIO]
root       185     2  0 22:25 ?        00:00:00 [mmal-vchiq]
root       188     2  0 22:25 ?        00:00:00 [mmal-vchiq]
root       190     2  0 22:25 ?        00:00:00 [mmal-vchiq]
root       191     2  0 22:25 ?        00:00:00 [mmal-vchiq]
root       193     2  0 22:25 ?        00:00:00 [mmal-vchiq]
root       227     2  0 22:25 ?        00:00:00 [cfg80211]
root       237     2  0 22:25 ?        00:00:00 [brcmf_wq/mmc1:0]
root       239     2  0 22:25 ?        00:00:02 [brcmf_wdog/mmc1]
systemd+   308     1  0 22:25 ?        00:00:00 /lib/systemd/systemd-timesyncd
nobody     347     1  0 22:25 ?        00:00:00 /usr/sbin/thd --triggers /etc/tr
root       350     1  0 22:25 ?        00:00:00 /lib/systemd/systemd-logind
root       351     1  0 22:25 ?        00:00:00 /usr/sbin/cron -f
root       363     1  0 22:25 ?        00:00:00 /usr/sbin/rsyslogd -n -iNONE
root       364     1  0 22:25 ?        00:00:00 /usr/sbin/alsactl -E HOME=/run/a
message+   368     1  0 22:25 ?        00:00:00 /usr/bin/dbus-daemon --system --
root       370     1  0 22:25 ?        00:00:00 /usr/sbin/rngd -r /dev/hwrng
root       374     1  0 22:25 ?        00:00:00 /sbin/wpa_supplicant -u -s -O /r
root       377     1  0 22:25 ?        00:00:00 /usr/lib/udisks2/udisksd
root       378     1  0 22:25 ?        00:00:00 /usr/sbin/cupsd -l
nobody     381     1  0 22:25 ?        00:00:00 /usr/local/bin/noip2
avahi      383     1  0 22:25 ?        00:00:00 avahi-daemon: running [raspberry
avahi      419   383  0 22:25 ?        00:00:00 avahi-daemon: chroot helper
root       436     1  0 22:25 ?        00:00:00 /sbin/dhcpcd -q -b
colord     460     1  0 22:25 ?        00:00:00 /usr/lib/colord/colord
root       461     1  0 22:25 ?        00:00:00 /usr/sbin/cups-browsed
root       473     1  0 22:25 ?        00:00:00 /usr/lib/policykit-1/polkitd --n
root       474     1  0 22:25 ?        00:00:01 /usr/bin/containerd
root       475     1  0 22:25 ?        00:00:00 /usr/sbin/lightdm
root       487     1  0 22:25 ?        00:00:00 wpa_supplicant -B -c/etc/wpa_sup
root       501   475  3 22:25 tty7     00:00:51 /usr/lib/xorg/Xorg :0 -seat seat
root       502     1  0 22:25 tty1     00:00:00 /bin/login -f
root       513     1  8 22:25 ?        00:02:02 /opt/teamviewer/tv_bin/teamviewe
root       531     1  0 22:25 ?        00:00:00 nginx: master process /usr/sbin/
www-data   532   531  0 22:25 ?        00:00:00 nginx: worker process
www-data   533   531  0 22:25 ?        00:00:00 nginx: worker process
www-data   534   531  0 22:25 ?        00:00:00 nginx: worker process
www-data   535   531  0 22:25 ?        00:00:00 nginx: worker process
root       541     1  0 22:25 ?        00:00:03 /usr/bin/dockerd -H fd:// --cont
root       544     2  0 22:25 ?        00:00:00 [kworker/u9:1-hci0]
root       545     1  0 22:25 ?        00:00:00 /usr/bin/hciattach /dev/serial1 
root       558     1  0 22:25 ?        00:00:00 /usr/lib/bluetooth/bluetoothd
pi         588     1  0 22:25 ?        00:00:00 /lib/systemd/systemd --user
pi         591   588  0 22:25 ?        00:00:00 (sd-pam)
pi         604   502  0 22:25 tty1     00:00:00 -bash
root       609   475  0 22:25 ?        00:00:00 lightdm --session-child 14 17
pi         613   609  0 22:25 ?        00:00:00 /usr/bin/lxsession -s LXDE-pi -e
pi         626   588  0 22:25 ?        00:00:12 /usr/bin/dbus-daemon --session -
pi         662   613  0 22:25 ?        00:00:00 /usr/bin/ssh-agent x-session-man
pi         676   588  0 22:25 ?        00:00:00 /usr/lib/gvfs/gvfsd
pi         683   588 13 22:25 ?        00:03:11 /opt/teamviewer/tv_bin/TeamViewe
pi         695   588  0 22:25 ?        00:00:00 /usr/lib/gvfs/gvfsd-fuse /run/us
pi         700   613  0 22:25 ?        00:00:01 openbox --config-file /home/pi/.
pi         705   613  0 22:25 ?        00:00:00 lxpolkit
pi         708   613  0 22:25 ?        00:00:04 lxpanel --profile LXDE-pi
pi         713   613 12 22:25 ?        00:03:03 pcmanfm --desktop --profile LXDE
pi         719     1  0 22:25 ?        00:00:00 /usr/bin/ssh-agent -s
pi         774   588  5 22:25 ?        00:01:17 /usr/bin/pulseaudio --daemonize=
rtkit      805     1  0 22:25 ?        00:00:00 /usr/lib/rtkit/rtkit-daemon
pi         809   588  0 22:25 ?        00:00:00 /usr/lib/gvfs/gvfs-udisks2-volum
pi         813   588  0 22:25 ?        00:00:00 /usr/lib/gvfs/gvfs-goa-volume-mo
pi         817   588  0 22:25 ?        00:00:00 /usr/lib/gvfs/gvfs-gphoto2-volum
pi         821   588  0 22:25 ?        00:00:00 /usr/lib/gvfs/gvfs-afc-volume-mo
pi         829     1  0 22:25 ?        00:00:00 /usr/lib/menu-cache/menu-cached 
pi         830   588  0 22:25 ?        00:00:00 /usr/lib/gvfs/gvfs-mtp-volume-mo
pi         841   676  0 22:25 ?        00:00:00 /usr/lib/gvfs/gvfsd-trash --spaw
root       847     2  0 22:25 ?        00:00:00 [krfcommd]
lp         860   378  0 22:25 ?        00:00:00 /usr/lib/cups/notifier/dbus dbus
root      1092     1  0 22:25 ?        00:00:00 /usr/bin/containerd-shim-runc-v2
root      1133  1092  0 22:25 ?        00:00:00 nginx: master process nginx -g d
systemd+  1201  1133  0 22:25 ?        00:00:00 nginx: worker process
systemd+  1202  1133  0 22:25 ?        00:00:00 nginx: worker process
systemd+  1203  1133  0 22:25 ?        00:00:00 nginx: worker process
systemd+  1204  1133  0 22:25 ?        00:00:00 nginx: worker process
pi        1212   588 16 22:25 ?        00:03:52 /opt/teamviewer/tv_bin/TeamViewe
pi        1243   708  0 22:26 ?        00:00:07 lxterminal
pi        1257  1243  0 22:26 pts/0    00:00:00 bash
root      1352     2  0 22:30 ?        00:00:01 [kworker/0:0-events]
root      1355     2  0 22:31 ?        00:00:02 [kworker/0:1H-mmc_complete]
root      1359     2  0 22:31 ?        00:00:01 [kworker/2:0H-kblockd]
pi        1360   588  3 22:31 ?        00:00:35 /usr/lib/gvfs/gvfsd-metadata
root      1385     2  0 22:33 ?        00:00:00 [kworker/1:1-mm_percpu_wq]
root      1439     2  0 22:39 ?        00:00:01 [kworker/u8:1-events_unbound]
root      1444     2  0 22:40 ?        00:00:00 [kworker/1:2-events]
root      1446     2  0 22:40 ?        00:00:00 [kworker/3:2-events]
root      1447     2  0 22:41 ?        00:00:00 [kworker/0:2-events]
root      1451     2  0 22:42 ?        00:00:00 [kworker/3:0H]
root      1452     2  0 22:42 ?        00:00:00 [kworker/1:0H]
root      1453     2  0 22:42 ?        00:00:00 [kworker/0:2H]
root      1463     2  0 22:43 ?        00:00:00 [kworker/2:1H]
root      1469     2  0 22:44 ?        00:00:00 [kworker/u8:0-events_unbound]
root      1499     1  0 22:44 ?        00:00:00 /usr/bin/containerd-shim-runc-v2
999       1519  1499  0 22:44 ?        00:00:01 redis-server 127.0.0.1:6379
root      1551     2  0 22:46 ?        00:00:00 [kworker/1:0-mm_percpu_wq]
root      1552     2  0 22:47 ?        00:00:00 [kworker/0:1-events]
pi        1558  1257  0 22:49 pts/0    00:00:00 ps -ef
pi@raspberrypi:~ $ 
`

Tried shutdown down the service with `sudo kill -9 1519`. But the service immediately reopens under a new PID. Deleted fermentrack-tools. Ran `sudo apt-get remove -y redis-server` then tried again with killing the Redis service. Still popping up on that port under a different PID each time. Ran a search for Redis files or folders and found a few folders remaining, but all are empty. Out of ideas.

**Comment by thorrak** [comment]
...doh! The fact that you have containerd in there means you were on the docker version. Weird.

Anyways, download fermentrack-tools again, and re-run the installation script. It should clean everything up (and ideally shut the container holding redis down). If it doesn't - and still gives you the error - run `docker ps` and let me know what it reads.

**Comment by doubleAbrew** [comment]
Okay here is the initialization script and docker ps results.

```
pi@raspberrypi:~ $ sudo fermentrack-tools/non_docker_install/install.sh
::: This script was launched as root. Continuing installation.
 _____                              _                  _    
|  ___|__ _ __ _ __ ___   ___ _ __ | |_ _ __ __ _  ___| | __
| |_ / _ \ '__| '_ ` _ \ / _ \ '_ \| __| '__/ _` |/ __| |/ /
|  _|  __/ |  | | | | | |  __/ | | | |_| | | (_| | (__|   < 
|_|  \___|_|  |_| |_| |_|\___|_| |_|\__|_|  \__,_|\___|_|\_\

Welcome to the installation of Fermentrack. This script will install fermentrack.
A new user will be created and Fermentrack will be installed in that users home directory.
When the installation is done with no errors Fermentrack is started and monitored automatically.

Please note - Any existing apps that require Apache (including RaspberryPints and BrewPi-www)
will be deactivated. If you want support for these apps it can be optionally installed later.
Please read http://apache.fermentrack.com/ for more information.

For more information about Fermentrack please visit: http://fermentrack.com/

Do you want to continue to install Fermentrack? [y/N] y
::: Ok, let's go!
::: To accept the default answer, just press Enter.
::: The default is capitalized in a Yes/No question: [Y/n]
::: or shown between brackets for other questions: [default]

The time is currently set to Thu 06 Oct 2022 10:56:27 AM CDT. Is this correct? [Y/n]y
::: All scripts associated with Fermentrack are now installed to a user's home directory
::: Hitting 'enter' will accept the default option in [brackets] (recommended).
*** WARNING: Any data in the user's home directory may be ERASED during install!

What user would you like to install Fermentrack under? [fermentrack]: y
fatal: not a git repository (or any of the parent directories): .git
::: Configuring under user fermentrack
::: Configuring in directory /home/fermentrack

::: Checking for Internet connection: 
::: Internet connection Success!

::: Installing dependencies using apt-get
::: apt is updated - installing git-core, nginx, python-dev, and a handful of other packages.
::: (This may take a few minutes during which everything will be silent) ...
::: All packages installed successfully.

::: Verifying free disk space...

Install directory is NOT empty, are you SURE you want to use this path? [y/N] y
::: Ok, we warned you!

::: Creating and configuring user accounts.
::: User 'fermentrack' already exists, skipping...

::: Checking install directories
::: Script install directory is NOT empty, backing up to this users home dir and then deleting contents...

::: Making sure everything is owned by fermentrack

::: Downloading most recent Fermentrack codebase...
Cloning into '/home/fermentrack/fermentrack'...

::: Making sure everything is owned by fermentrack

::: Creating virtualenv directory...
::: Python 3.7 is installed. Using Python 3.7 to create the venv.
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/home/fermentrack/venv/bin/python3.7', '-Im', 'ensurepip', '--upgrade', '--default-pip']

::: Forcing reinstallation of pip within the virtualenv
sudo: /home/fermentrack/venv/bin/pip: command not found
sudo: /home/fermentrack/venv/bin/pip: command not found
::: Manually installing PyZMQ and Circus - This could take ~10-15 mins.
/home/fermentrack/venv/bin/python3: No module named pip
/home/fermentrack/venv/bin/python3: No module named pip
::: Numpy and Scipy are available through system packages. Linking to those.
::: Venv has been created!

::: Enabling python to query bluetooth without being root
::: Running make_secretsettings.sh from the script repo
Generating SECRET_KEY and writing to fermentrack_django/secretsettings.py
secretsettings.py created!

::: Running upgrade.sh from the script repo to finalize the install.
::: This may take up to an hour during which everything will be silent...

::: Copying nginx configuration to /etc/nginx and activating.
::: Making sure everything is owned by fermentrack

::: Running updateCronCircus.sh from the script repo
ERROR: Could not find circusd
::: Starting circus process monitor.
ERROR: Could not find circusd

Waiting for Fermentrack install to initialize and become responsive.
Fermentrack may take up to 5 minutes to first boot as the database is being initialized.
....................................................................................................................................................................................missing.
*** ----------------------------------
*** ERROR ERROR ERROR ERROR ERROR ***
Unable to find an initialized, responsive instance of Fermentrack
 
*** ----------------------------------
*** See above lines for error message
*** Setup NOT completed
*** More information in the "install.log" file
pi@raspberrypi:~ $ docker ps
CONTAINER ID   IMAGE               COMMAND                  CREATED        STATUS                          PORTS     NAMES
48be3168e9f1   fermentrack_nginx   "/docker-entrypoint.…"   4 months ago   Restarting (1) 31 seconds ago             fermentrack-tools_nginx_1
c27ba9e66570   fermentrack_redis   "docker-entrypoint.s…"   4 months ago   Restarting (1) 51 seconds ago             fermentrack-tools_redis_1
pi@raspberrypi:~ $ 

```

**Comment by doubleAbrew** [comment]
> Try using the regular install script, as you seem to have a docker installation Message ID: ***@***.***>

Same issue with the Port 6379.

This was becoming too time consuming to figure out and I didn't really have anything I couldn't lose so I wiped my Raspberry Pi, fresh install of Raspi OS and Debian 11, then fresh install of Fermentrack. Everything back up and running UNTIL.........

My Tilt was not before and is not still communicating with Fermentrack. As before, and what began this problem, I ran the Troubleshoot Tilt connection and it says my Python flags are missing. The Troubleshoot says to run `sudo setcap cap_net_raw,cap_net_admin+eip /usr/local/bin/python3.9`. Did this, but as before, I got a 

"Failed to set capabilities on file 'usr/local/bin/python3.9' (No such file or directory)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file

I found no files of any kind in /usr/local/bin but I did find a file in usr/bin so I tried the command on that and now not only does the Tilt still not work. I hope to didn't goof anything up trying that option. Otherwise things are back up. I'd sure like to have my Tilt communicating again. Any ideas here?

**Comment by doubleAbrew** [comment]
Sorry to keep bothering you, I know you are very busy. Any thoughts on that
issue with Python being in /usr/bin instead of /usr/local/bin and
generating the missing Python flags? Everything else is working but this is
twice I've had this issue after a fresh install. Thanks again!

Aaron

**Comment by doubleAbrew** [comment]
The regular install script gives me the error message "Port 6379 is
required by Redis but is currently in use. Installation cannot continue."
Then it quits.

**Comment by vanosg** [comment]
@doubleAbrew sorry it took so long for you to get an answer- with only the context here, I think you have redis running on the host already, and then docker tries to run and grab the same port that the host redis is using. Try `systemctl status redis-server` (use tab complete on that, i think its redis-server)  to see if redis is running, and then `systemctl stop redis-server` to stop it. Using 'stop' just turns it off until restart, so i think (Google is smarter than me) to perm turn it off you want to use `systemctl disable redis-server` after stopping, but again I would suggest Googling to make sure. Hope this helps!

**Comment by thorrak** [comment]
I’m hoping that this is resolved at this point as I think it was environmental. If not, please feel free to comment here and we can reopen.
