### ISSUE TITLE
Cannot receiveLCD text fromController/Script

### ISSUE THREAD

**Issue by bitzebraeu** [thorrak/fermentrack#708]
Hi,

for some time now I frequently get the error Cannot receiveLCD text fromController/Script. I see this issue has been discussed here before, unfortunately I do not understand a word :-(   My error log tells me many things, among other that my version is too old. When I try to update from Gihub however it tells me that I am on the newest version.

What can I try to get fermentrack running stable again? I already reset the EEPROM and WIFI and re-loaded the controller. No effect.

Would my Stdout log or Stderr log help anyone to see the issue and tell me what's wrong?

Thanks,
Patrick

**Comment by thorrak** [comment]
What do you typically do to resolve this when it happens? Restart the controller, restart the Pi running Fermentrack, or both?

**Comment by bitzebraeu** [comment]
I've had this for about 2 weeks. Never had this before, so I have no experience. Occasionally it connects and works fine, but I guess 80% of the time I have the error.

**Comment by vanosg** [comment]
When I see this on mine, it means the Pi web server isn't getting data from the embedded controller. Most likely causes, either the wireless connection of the controller to the LAN is spotty, or it hit a bad state and is rebooting. I'd check the placement of the controller and make sure its not shielded from the router

**Comment by bitzebraeu** [comment]
sorry for the delay. Unfortunately that is not the case :-(  Although I do not understand that temporarily it connects with the controller.   What is the best way to re-flash the controller?

**Comment by thorrak** [comment]
Is this fixed or are you still having the issue @bitzebraeu ?

**Comment by bitzebraeu** [comment]
Re-flashed and all good now!

Thanks
