### ISSUE TITLE
Bad gateway - firmware and update page

### ISSUE THREAD

**Issue by cdnninja** [thorrak/fermentrack#751]
I am getting a bad gateway error on both the flash firmware page and the update page.  This is ever since the most recent tools update.  

I have been having disconnects to my Arduino so thought it was time to move away from 2.10 firmware but looks like I can't.

**Comment by cdnninja** [comment]
Yes running via docker.  Can't easily confirm version since the update page won't load but two days ago ran the install.sh script again which I assume should mean I am latest.  


It's prompting to update from GitHub though which makes me wonder if not on latest.

**Comment by thorrak** [comment]
I got an image booted on my end, but the firmware flash routines seem to be working as expected.

**Comment by cdnninja** [comment]
Interesting.  I can't even hit the page to start flashing firmware.   

This comes out of me trying to address it loosing connection every few days to the temp controller.   Good news is with this change the tilt is stable though.  

I'm not by a computer but will see what I can do with this in a few days.

**Comment by cdnninja** [comment]
Same gateway error after the update.    I don't have the prompt to update from github anymore.  Most likely because I used to be set to the dev mode in fermentrack and now running that branch. 

As a note I ran sudo ./install  as I have that old permissions issue that won't let it install without sudo.

**Comment by thorrak** [comment]
This is admittedly the most asinine way I could have solved the flashing problem, but I just released a new version of BrewFlasher that works on the command line called BrewFlasher CLI edition. It’s available on[PyPI](https://pypi.org/project/brewflasher-cli/) and the announcement post is [here on HBT](https://www.homebrewtalk.com/threads/brewflasher-windows-macos-app-for-flashing-esp8266-esp32-brewing-projects.674823/page-3#post-10285851) . 

I’m now back home with my Pi’s so I should be able to debug a bit further.

**Comment by cdnninja** [comment]
It's been stable since pulling from dev.  All works now.  Going to close this.

**Comment by thorrak** [comment]
Cheers - thank you!
