### ISSUE TITLE
Fermentrack will not start after installing docker image running on Unraid

### ISSUE THREAD

**Issue by jmaill** [thorrak/fermentrack#772]
Fermentrack will not start after installing docker image, running on Unraid

When running
Code:
docker pull jdbeeler/fermentrack
I get an error
Code:
/entrypoint: line 9: POSTGRES_USER: unbound variable

**Comment by thorrak** [comment]
The fermentrack image is intended to be used as part of a docker compose stack. You’ll need to either use the fermentrack tools install script or follow how it creates the environment variable files for use by docker compose when configuring the stack. Unfortunately, you can’t just pull the image and have it work.
